import test from 'node:test';
import assert from 'node:assert/strict';
import { parseCommand, MAX_COMMAND_LENGTH } from '../assets/js/debian-server/command-parser.js';
import { ShellEngine } from '../assets/js/debian-server/shell-engine.js';
import { clearState, defaultState, loadState, saveState, STORAGE_KEY } from '../assets/js/debian-server/session-state.js';

const setup = () => { const state=defaultState(); return {state,engine:new ShellEngine(state)}; };
const run = (engine, state, command) => { if(command.trim())state.commandHistory.push(command.trim()); return engine.execute(command); };

test('navigation, identity, listing, and reading are Debian-like',()=>{const {state,engine}=setup();assert.deepEqual(run(engine,state,'pwd').stdout,['/home/visitor']);run(engine,state,'cd /etc');assert.equal(run(engine,state,'pwd').stdout[0],'/etc');run(engine,state,'cd');run(engine,state,'cd ..');run(engine,state,'cd visitor');assert.equal(state.currentDirectory,'/home/visitor');assert.match(run(engine,state,'ls').stdout[0],/README/);assert.match(run(engine,state,'ls -a').stdout[0],/\.session-note/);assert.match(run(engine,state,'ls -l /etc').stdout[1],/root root/);assert.match(run(engine,state,'ls /root').stderr[0],/Permission denied/);assert.match(run(engine,state,'ls missing').stderr[0],/No such/);assert.match(run(engine,state,'cat /etc/os-release').stdout[0],/Debian GNU\/Linux 13/);assert.match(run(engine,state,'cat /home/visitor/README').stdout[0],/Welcome/);assert.match(run(engine,state,'cat /etc').stderr[0],/Is a directory/);assert.equal(run(engine,state,'head /var/log/syslog').stdout.length,3);assert.equal(run(engine,state,'tail -n 2 /var/log/syslog').stdout.length,2);assert.equal(run(engine,state,'whoami').stdout[0],'visitor');assert.match(run(engine,state,'id').stdout[0],/uid=1000/);assert.equal(run(engine,state,'hostname').stdout[0],'lab-node');assert.match(run(engine,state,'uname -a').stdout[0],/x86_64/);assert.match(run(engine,state,'date').stdout[0],/UTC/);});

test('mutations and quoted paths remain consistent',()=>{const {state,engine}=setup();run(engine,state,'mkdir test');run(engine,state,'cd test');run(engine,state,'touch note.txt');assert.match(run(engine,state,'ls').stdout[0],/note.txt/);run(engine,state,'cd ..');run(engine,state,'cp test/note.txt copied.txt');assert.deepEqual(run(engine,state,'cat copied.txt').stdout,['']);run(engine,state,'mv copied.txt renamed.txt');assert.match(run(engine,state,'ls').stdout[0],/renamed.txt/);run(engine,state,'rm renamed.txt');run(engine,state,'rm -r test');assert.doesNotMatch(run(engine,state,'ls').stdout[0],/test/);run(engine,state,'mkdir "test space"');run(engine,state,'touch "test space/note file.txt"');assert.match(run(engine,state,'ls "test space"').stdout[0],/note file.txt/);run(engine,state,'rm -r "test space"');});

test('permissions, safety, parsing, and history',()=>{const {state,engine}=setup();for(const command of ['cd /root','touch /etc/test','rm /etc/hostname','mkdir /usr/test'])assert.match(run(engine,state,command).stderr[0],/Permission denied/);assert.match(run(engine,state,'rm -r /').stderr[0],/Permission denied/);assert.match(run(engine,state,'not-a-command').stderr[0],/command not found/);assert.match(parseCommand('echo "no').error,/unexpected EOF/);assert.match(parseCommand('ls | cat').error,/operators/);assert.match(parseCommand('x'.repeat(MAX_COMMAND_LENGTH+1)).error,/too long/);assert.deepEqual(parseCommand('mkdir "a b"').tokens,['mkdir','a b']);assert.equal(run(engine,state,'history').stdout.length,state.commandHistory.length);});

test('malformed or outdated session storage resets safely',()=>{const data=new Map([[STORAGE_KEY,'{broken']]);const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const recovered=loadState(storage);assert.equal(recovered.currentDirectory,'/home/visitor');data.set(STORAGE_KEY,JSON.stringify({...recovered,schemaVersion:0}));assert.equal(loadState(storage).schemaVersion,2);});

test('state and history reload in-tab, while exit clearing removes them',()=>{const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const state=defaultState();state.commandHistory.push('pwd','ls -a');state.currentDirectory='/etc';saveState(state,storage);const restored=loadState(storage);assert.equal(restored.currentDirectory,'/etc');assert.deepEqual(restored.commandHistory,['pwd','ls -a']);clearState(storage);assert.equal(storage.getItem(STORAGE_KEY),null);});

test('recursive copies honor object limits',()=>{const {state,engine}=setup();for(let i=0;i<500;i++){const output=run(engine,state,`touch /tmp/f${i}`);if(output.stderr.length)break;}assert.match(run(engine,state,'cp -r /home/visitor /tmp/visitor').stderr[0],/No space left/);});
