const test=require('node:test'), assert=require('node:assert/strict');const {Enigma,Rotor,refs}=require('../museum/cryptography-lab/enigma-machine/enigma.js');
test('rotor and reflector wiring is deterministic',()=>{assert.equal(new Rotor('I').forward(0),4);assert.equal(new Rotor('I').backward(4),0);assert.equal(refs.B[0],'Y')});
test('plugboard is symmetric and rejects invalid pairs',()=>{let e=new Enigma({pairs:['AM','FI']});assert.equal(e.plug[0],12);assert.equal(e.plug[12],0);assert.throws(()=>e.setPlugboard(['AA']));assert.throws(()=>e.setPlugboard(['AM','AZ']))});
test('right rotor steps and carries at notch',()=>{let e=new Enigma({positions:'AAU'});e.encipher('A');assert.equal(e.positions(),'AAV');e.encipher('A');assert.equal(e.positions(),'ABW')});
test('double stepping advances middle twice on consecutive presses',()=>{let e=new Enigma({positions:'ADV'});e.encipher('A');assert.equal(e.positions(),'AEW');e.encipher('A');assert.equal(e.positions(),'BFX')});
test('reciprocal encryption and reset',()=>{let a=new Enigma({order:['I','II','III'],positions:'AAA',pairs:['AM','FI']});let c=[...'HELLOWORLD'].map(x=>a.encipher(x).output).join('');a.reset();assert.equal([...c].map(x=>a.encipher(x).output).join(''),'HELLOWORLD');assert.notEqual(c,'HELLOWORLD')});

test('guided training configuration is deterministic and makes the LL lesson visible',()=>{const config={order:['I','II','III'],reflector:'B',rings:[0,0,0],positions:'AAA',pairs:[]};const a=new Enigma(config);const cipher=[...'HALLO'].map(letter=>a.encipher(letter).output).join('');assert.equal(cipher,'IDBDA');assert.notEqual(cipher[2],cipher[3]);a.reset();assert.equal([...cipher].map(letter=>a.encipher(letter).output).join(''),'HALLO')});
test('restoring training start resets every relevant machine setting',()=>{const config={order:['I','II','III'],reflector:'B',rings:[0,0,0],positions:'AAA',pairs:[]};const e=new Enigma(config);[...'HALLO'].forEach(x=>e.encipher(x));e.order=['V','IV','III'];e.reflector='C';e.rings=[4,5,6];e.starts=[3,2,1];e.setPlugboard(['AM','GL']);e.reset();Object.assign(e,{order:[...config.order],reflector:config.reflector,rings:[...config.rings],starts:[0,0,0]});e.setPlugboard([]);e.reset();assert.deepEqual(e.order,config.order);assert.equal(e.reflector,config.reflector);assert.deepEqual(e.rings,config.rings);assert.equal(e.positions(),config.positions);assert.deepEqual(e.pairs,config.pairs)});
test('UI uses one-time static construction instead of rendering machine controls repeatedly',()=>{const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../museum/cryptography-lab/enigma-machine/lab-ui.js'),'utf8');assert.match(source,/function buildStatic\(\)/);assert.match(source,/buildStatic\(\);render\(\);missionPanel\(\);/);assert.doesNotMatch(source,/machine\.reset\(\);build\(/);assert.match(source,/replaceChildren\(\.\.\.all\.filter/)});
