import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {correlateUsbReports} from '../assets/linux-hardware-explorer/usb-topology.js';
import {usbInterfacePresentation} from '../assets/linux-hardware-explorer/usb-presentation.js';
import {matchKernelAliases,usbClassContext} from '../assets/linux-hardware-explorer/kernel-alias-matcher.js';
import {enrichKernelResults,INDEX_STATIC_REQUEST_PATHS} from '../assets/linux-hardware-explorer/kernel-index-loader.js';
const dir=new URL('../assets/linux-hardware-explorer/kernel-index/',import.meta.url);
const indexes=Object.fromEntries(['pci','usb','hid'].map(bus=>[bus,JSON.parse(readFileSync(new URL(bus+'.json',dir),'utf8'))]));
const manifest=JSON.parse(readFileSync(new URL('manifest.json',dir),'utf8'));
const brio=[
'Bus 006 Device 003: ID 046d:085e Logitech, Inc. BRIO Ultra HD Webcam',
'/:  Bus 006.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 10000M',
' |__ Port 001: Dev 003, If 0, Class=Video, Driver=uvcvideo, 5000M',
' |__ Port 001: Dev 003, If 1, Class=Video, Driver=uvcvideo, 5000M',
' |__ Port 001: Dev 003, If 2, Class=Video, Driver=uvcvideo, 5000M',
' |__ Port 001: Dev 003, If 3, Class=Audio, Driver=snd-usb-audio, 5000M',
' |__ Port 001: Dev 003, If 4, Class=Audio, Driver=snd-usb-audio, 5000M',
' |__ Port 001: Dev 003, If 5, Class=Human Interface Device, Driver=usbhid, 5000M'
].join('\n');
const device=(vendor='046d',product='085e',address='006:003')=>({bus:'usb',vendor,device:product,usbAddress:address,origins:['lsusb'],usbInterfaceClasses:[],usbInterfaceTriplets:[],binding:'unreported',boundDriver:null});
const parse=(raw,devices=[device()])=>correlateUsbReports({devices,formats:['lsusb'],warnings:[]},raw);
test('BRIO has six interface bindings and three driver names in German and English',()=>{const d=parse(brio).devices[0],p=usbInterfacePresentation(d);assert.equal(d.interfaceBindings.length,6);assert.equal(p.bound,6);assert.equal(p.distinctDrivers,3);assert.equal(d.boundDriver,null);assert.equal(p.status,'6 USB interfaces with reported driver bindings');assert.equal(usbInterfacePresentation(d,'de').status,'6 USB-Schnittstellen mit gemeldeter Treiberbindung');});
test('Video, Audio and HID classes have no invented descriptor subclass or protocol',()=>{const d=parse(brio).devices[0];assert.deepEqual(d.usbInterfaces.map(i=>i.classCode),['0e','0e','0e','01','01','03']);assert.ok(d.usbInterfaces.every(i=>i.reportedClassEvidence==='lsusb -t'&&!i.subClass&&!i.protocol));assert.equal(d.usbInterfaceTriplets.length,0);assert.deepEqual(usbClassContext(d).filter(i=>i.classCode==='0e').map(i=>i.number),[0,1,2]);});
test('BRIO groups 0–2 video, 3–4 audio and 5 HID without duplication',()=>{const d=parse(brio).devices[0];for(const lang of ['en','de']){const s=usbInterfacePresentation(d,lang);assert.deepEqual(s.groups.map(g=>g.range),['0–2','3–4','5']);assert.deepEqual(s.groups.map(g=>g.driver),['uvcvideo','snd-usb-audio','usbhid']);assert.deepEqual(s.groups.map(g=>g.label),['Video','Audio','HID']);}});
test('observed uvcvideo/audio is not a kernel alias match without necessary descriptors',()=>{const d=parse(brio).devices[0];const a=matchKernelAliases(d,indexes.usb);assert.ok(a.candidates.some(c=>c.module==='usbhid'));assert.ok(!a.candidates.some(c=>c.module==='uvcvideo'||c.module==='snd_usb_audio'));assert.ok(indexes.usb.generic.some(r=>r[1]==='uvcvideo'&&r[0].includes('ic0Eisc01ip00')));assert.ok(indexes.usb.generic.some(r=>r[1]==='snd_usb_audio'&&r[0].includes('ic01isc01')));d.usbInterfaces[0].subClass='01';d.usbInterfaces[0].protocol='00';d.usbInterfaces[3].subClass='01';const full=matchKernelAliases(d,indexes.usb);assert.ok(full.candidates.some(c=>c.module==='uvcvideo'));assert.ok(full.candidates.some(c=>c.module==='snd_usb_audio'));});
test('partial, unbound, unknown and conflicting observations remain distinguishable',()=>{const root='/:  Bus 006.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 5000M\n';const rows=[' |__ Port 001: Dev 003, If 0, Class=Audio, Driver=usbhid, 5000M',' |__ Port 001: Dev 003, If 1, Class=Audio, Driver=(none), 5000M',' |__ Port 001: Dev 003, If 2, Class=Video, Driver=, 5000M'];const d=parse(root+rows.join('\n')).devices[0];const s=usbInterfacePresentation(d);assert.equal(s.kind,'partial');assert.deepEqual([s.bound,s.unbound,s.missing],[1,1,1]);const u=parse(root+rows.join('\n').replace('Driver=usbhid','Driver=none').replace('Driver=,','Driver=none')).devices[0];assert.equal(usbInterfacePresentation(u).kind,'unbound');const c=parse(root+rows.join('\n')+'\n'+rows[0].replace('usbhid','other')).devices[0];assert.equal(usbInterfacePresentation(c).kind,'conflicting');assert.equal(usbInterfacePresentation(device()),null);});
test('bus number prevents separate composite devices from cross-correlating',()=>{const second=brio.replaceAll('Bus 006','Bus 007');const a=device(),b=device('1234','abcd','007:003');parse(brio+'\n'+second,[a,b]);assert.equal(a.interfaceBindings.length,6);assert.equal(b.interfaceBindings.length,6);});
test('CH340 has independent ch341 alias and reported interface binding',()=>{const d=device('1a86','7523','001:009');parse('/:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 480M\n |__ Port 004: Dev 009, If 0, Class=Vendor Specific Class, Driver=ch341, 12M',[d]);assert.equal(usbInterfacePresentation(d).bound,1);assert.ok(matchKernelAliases(d,indexes.usb).candidates.some(c=>c.module==='ch341'));assert.equal(d.boundDriver,null);});
test('Navi44 observed amdgpu remains independent of older kernel alias snapshot',async()=>{const d={bus:'pci',vendor:'1002',device:'7590',boundDriver:'amdgpu'};const r=await enrichKernelResults([{device:d,boundDriver:'amdgpu',matches:[{profileId:'amd-navi44',reason:'family-id'}]}],{snapshot:{manifest,indexes}});assert.equal(r[0].boundDriver,'amdgpu');assert.deepEqual(r[0].kernelEvidence.candidates,[]);assert.equal(r[0].kernelEvidence.kernelRelease,manifest.kernelRelease);});
test('index URLs remain fixed and untrusted class strings remain plain data',()=>{assert.deepEqual(INDEX_STATIC_REQUEST_PATHS,['manifest.json','pci.json','usb.json','hid.json']);const d=parse('/:  Bus 006.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 5000M\n |__ Port 001: Dev 003, If 0, Class=<img onerror=x()>, Driver=usbhid, 5000M').devices[0];assert.equal(usbInterfacePresentation(d).bound,1);});
