'use strict';
const assert = require('assert'); const fs = require('fs'); const terminal = require('../museum/linux-game-install/terminal.js');
let state = terminal.freshState(), r;
r=terminal.execute('ls /usr/games',state);assert.equal(r.output,'');state=r.state;
r=terminal.execute('nebustrike',state);assert.match(r.output,/command not found/);state=r.state;
r=terminal.execute('vectorstrike',state);assert.match(r.output,/command not found/);state=r.state;
r=terminal.execute('apt update',state);assert.match(r.output,/local exhibit catalog/);state=r.state;
const searchStarted=process.hrtime.bigint();r=terminal.execute('apt search games',state);const searchElapsedMs=Number(process.hrtime.bigint()-searchStarted)/1e6;assert.ok(searchElapsedMs<100,'apt search games must terminate promptly');assert.equal(r.action,'searched');assert.match(r.output,/nebustrike/);assert.match(r.output,/Computer Museum Interactive Repository/);assert.match(r.output,/PLAYABLE/);assert.ok(r.output.length<500,'apt search games output must remain bounded');assert.ok(r.output.split('\n').length<=6,'apt search games output must remain bounded');assert.doesNotMatch(r.output,/openttd/i);state=r.state;
r=terminal.execute('apt search nebustrike',state);assert.match(r.output,/Deep-space vector combat arcade game/);state=r.state;
r=terminal.execute('apt install nebustrike',state);assert.equal(r.action,'confirm');assert.equal(r.state.awaitingConfirmation,true);assert.match(r.output,/\[Y\/n\]/);state=r.state;
r=terminal.execute('y',state);assert.equal(r.action,'installed');assert.equal(r.state.installed,true);assert.match(r.output,/Setting up nebustrike/);state=r.state;
r=terminal.execute('which nebustrike',state);assert.equal(r.output,'/usr/games/nebustrike');state=r.state;
r=terminal.execute('ls /usr/games',state);assert.equal(r.output,'nebustrike');state=r.state;
r=terminal.execute('nebustrike',state);assert.equal(r.action,'launch');assert.match(r.output,/STARTING NEBU STRIKE/);assert.match(r.output,/MISSION COMPLETE/);state=r.state;
r=terminal.execute('/usr/games/nebustrike',state);assert.equal(r.action,'launch');state=r.state;
r=terminal.execute('chmod 700 /usr/games/nebustrike',state);assert.equal(r.output,'');state=r.state;
r=terminal.execute('cd /usr',state);assert.equal(r.state.system.cwd,'/usr');state=r.state;
r=terminal.execute('cd games',state);assert.equal(r.state.system.cwd,'/usr/games');state=r.state;
r=terminal.execute('ls',state);assert.equal(r.output,'nebustrike');state=r.state;
r=terminal.execute('cd /usr/games',state);assert.equal(r.state.system.cwd,'/usr/games');state=r.state;
r=terminal.execute('help',state);assert.match(r.output,/apt update/);assert.match(r.output,/apt search nebustrike/);assert.match(r.output,/apt install nebustrike/);assert.match(r.output,/which nebustrike/);assert.match(r.output,/cd = change directory/);assert.match(r.output,/cd \/usr\/games/);assert.match(r.output,/ls = list directory contents/);assert.match(r.output,/after visitor@nebunix:~\$/);state=r.state;
r=terminal.execute('reset',state);assert.equal(r.state.installed,false);state=r.state;
r=terminal.execute('ls /usr/games',state);assert.equal(r.output,'');
const source=fs.readFileSync(require.resolve('../museum/linux-game-install/terminal.js'),'utf8');assert.equal(/vectorstrike/.test(source),false,'legacy package must not be canonical');assert.equal(/\b(fetch|XMLHttpRequest|WebSocket|child_process|exec)\b/.test(source),false);console.log('linux game installation terminal tests passed');
