'use strict';
const assert = require('assert');
const terminal = require('../museum/linux-game-install/terminal.js');
let state = terminal.freshState();
let r = terminal.execute('cd /usr', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('pwd', state); assert.equal(r.output, '/usr'); state = r.state;
r = terminal.execute('cd games', state); assert.equal(r.state.system.cwd, '/usr/games'); state = r.state;
r = terminal.execute('ls', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('cd ..', state); assert.equal(r.state.system.cwd, '/usr'); state = r.state;
r = terminal.execute('cd /', state); assert.equal(r.state.system.cwd, '/'); state = r.state;
r = terminal.execute('cd ~', state); assert.equal(r.state.system.cwd, '/home/visitor'); state = r.state;
r = terminal.execute('mkdir playground', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('touch playground/notes.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('cp playground/notes.txt playground/copy.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('mv playground/copy.txt playground/moved.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('rm playground/moved.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('chmod 600 playground/notes.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('cat playground/notes.txt', state); assert.equal(r.output, ''); state = r.state;
r = terminal.execute('cd /does-not-exist', state); assert.match(r.output, /No such directory/); state = r.state;
r = terminal.execute('openttd', state); assert.match(r.output, /command not found/); state = r.state;
r = terminal.execute('sudo apt update', state); assert.match(r.output, /Reading package lists/); assert.equal(r.state.updated, true); state = r.state;
r = terminal.execute('apt search openttd', state); assert.match(r.output, /openttd-opengfx/); state = r.state;
r = terminal.execute('sudo apt install openttd', state); assert.equal(r.state.awaitingConfirmation, true); assert.match(r.output, /Do you want to continue/); state = r.state;
r = terminal.execute('y', state); assert.equal(r.state.installed, true); assert.match(r.output, /Setting up openttd/); state = r.state;
r = terminal.execute('which openttd', state); assert.equal(r.output, '/usr/games/openttd'); state = r.state;
r = terminal.execute('ls /usr/games', state); assert.equal(r.output, 'openttd'); state = r.state;
r = terminal.execute('cd /usr/games', state); assert.equal(r.state.system.cwd, '/usr/games'); state = r.state;
r = terminal.execute('ls', state); assert.equal(r.output, 'openttd'); state = r.state;
r = terminal.execute('dpkg -l | grep openttd', state); assert.match(r.output, /ii  openttd/); state = r.state;
r = terminal.execute('openttd', state); assert.equal(r.action, 'launch'); assert.equal(r.state.launched, true); state = r.state;
r = terminal.execute('not-a-command', state); assert.match(r.output, /^not-a-command: command not found/);
r = terminal.execute('reset', state); assert.equal(r.state.installed, false); assert.equal(r.state.system.cwd, '/home/visitor'); state = r.state;
r = terminal.execute('ls /usr/games', state); assert.equal(r.output, '');
console.log('linux game installation terminal tests passed');
const fs = require('fs');
const source = fs.readFileSync(require.resolve('../museum/linux-game-install/terminal.js'), 'utf8');
assert.equal(/\b(fetch|XMLHttpRequest|WebSocket|child_process|exec)\b/.test(source), false, 'terminal engine must not access network or shell APIs');
console.log('no network or shell API references found');
