import test from 'node:test';
import assert from 'node:assert/strict';
import { ShellEngine } from '../assets/js/debian-server/shell-engine.js';
import { defaultWorkstationState } from '../assets/js/lost-administrator/workstation-state.js';
import { completeTerminalInput } from '../assets/js/debian-server/tab-completion.js';
import { commands } from '../assets/js/debian-server/command-registry.js';
import { TerminalRenderer } from '../assets/js/debian-server/terminal-renderer.js';

const run=(engine,state,source)=>{state.commandHistory.push(source);return engine.execute(source);};
test('Michael has an independent Debian identity and home',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);assert.equal(run(engine,state,'whoami').stdout[0],'michael');assert.equal(run(engine,state,'hostname').stdout[0],'workstation');assert.equal(run(engine,state,'pwd').stdout[0],'/home/michael');assert.match(run(engine,state,'uname -a').stdout[0],/Linux workstation/);});
test('the starter archive is small, coherent, and explorable',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);const listing=run(engine,state,'ls').stdout.join('\n');for(const name of ['Desktop','Documents','Downloads','Mail','Notes','Projects','Scripts','Photos','Emma','Arthur','Tickets','Archive','Books','Research'])assert.match(listing,new RegExp(name));assert.match(run(engine,state,'cat Notes/terminal-cheatsheet.md').stdout.join('\n'),/Future Michael/);assert.match(run(engine,state,'tree Projects/monitoring -L 2').stdout.join('\n'),/README\.md/);assert.match(run(engine,state,'cat Scripts/cleanup.sh').stdout.join('\n'),/does not delete automatically/);assert.equal(run(engine,state,'find Tickets -type f').stdout.length,1);});
test('workstation writes stay in Michael home',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);assert.equal(run(engine,state,'touch Notes/today.txt').exitCode,0);assert.equal(run(engine,state,'touch /etc/nope').exitCode,1);run(engine,state,'cd Projects');run(engine,state,'cd');assert.equal(state.currentDirectory,'/home/michael');});
test('shared completion handles unique, ambiguous, missing, home, and spaced paths',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state),input={value:'cat No',selectionStart:6,selectionEnd:6},seen=[];engine.fs.add('/tmp/completion',{name:'',type:'directory',owner:'michael',group:'michael',mode:'drwxr-xr-x',children:{'Notes.txt':{name:'Notes.txt',type:'file',owner:'michael',group:'michael',mode:'-rw-r--r--',content:'',created:'',modified:''}},created:'',modified:''});state.currentDirectory='/tmp/completion';completeTerminalInput(input,state,engine.fs,Object.keys(commands),x=>seen.push(x));assert.equal(input.value,'cat Notes.txt');state.currentDirectory='/home/michael';input.value='cd Pro';input.selectionStart=6;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cd Projects/');input.value='cd ~/Pho';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cd ~/Photos/');input.value='cat missing';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cat missing');input.value='cat D';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands),x=>seen.push(x));assert.equal(input.value,'cat D');assert.ok(seen.at(-1).length>1);state.currentDirectory='/home/michael/Downloads';input.value='cat RFC';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cat RFC\\ notes.txt');});
test('workstation prompts abbreviate Michael home without duplicating paths',()=>{const renderer=Object.create(TerminalRenderer.prototype);renderer.user='michael';renderer.hostname='workstation';renderer.home='/home/michael';assert.equal(renderer.promptText('/home/michael'),'michael@workstation:~$');assert.equal(renderer.promptText('/home/michael/Downloads'),'michael@workstation:~/Downloads$');assert.equal(renderer.promptText('/home/michael/Projects/monitoring'),'michael@workstation:~/Projects/monitoring$');});
test('ls keeps logical output alongside presentation metadata and fastfetch stays fictional',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state),listing=engine.execute('ls');assert.match(listing.stdout[0],/Projects/);assert.ok(listing.styledLines[0].some(token=>token.type==='directory'&&token.text.includes('Projects')));const info=engine.execute('fastfetch').stdout.join('\n');assert.match(info,/Fictional browser-only workstation/);assert.doesNotMatch(info,/CPU:|Memory:|Uptime:|IP:/);});
