import test from 'node:test';
import assert from 'node:assert/strict';
import { ShellEngine } from '../assets/js/debian-server/shell-engine.js';
import { defaultWorkstationState } from '../assets/js/lost-administrator/workstation-state.js';
import { completeTerminalInput } from '../assets/js/debian-server/tab-completion.js';
import { commands } from '../assets/js/debian-server/command-registry.js';
import { TerminalRenderer } from '../assets/js/debian-server/terminal-renderer.js';
import { readFile } from 'node:fs/promises';
import { WORKSTATION_STORAGE_KEY, loadWorkstationState } from '../assets/js/lost-administrator/workstation-state.js';

const run=(engine,state,source)=>{state.commandHistory.push(source);return engine.execute(source);};
test('Michael has an independent Debian identity and home',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);assert.equal(run(engine,state,'whoami').stdout[0],'m.weber');assert.equal(run(engine,state,'hostname').stdout[0],'workstation');assert.equal(run(engine,state,'pwd').stdout[0],'/home/m.weber');assert.match(run(engine,state,'uname -a').stdout[0],/Linux workstation/);});
test('workstation timestamps reflect the abandoned Friday session',async()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state),controller=await readFile(new URL('../assets/js/lost-administrator/workstation-controller.js',import.meta.url),'utf8');assert.equal(run(engine,state,'date').stdout[0],'Fri Jul 31, 2026, 19:18:43 UTC');assert.match(controller,/Last login: Fri Jul 31 17:41:26 UTC 2026 on tty1/);});
test('the lived-in archive is coherent and explorable',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);const listing=run(engine,state,'ls').stdout.join('\n');for(const name of ['Desktop','Documents','Downloads','Mail','Notes','Projects','Scripts','Photos','Tickets','Archive','Books','Research'])assert.match(listing,new RegExp(name));assert.match(run(engine,state,'cat Notes/terminal-cheatsheet.md').stdout.join('\n'),/Future Michael/);assert.match(run(engine,state,'tree Projects/monitoring -L 2').stdout.join('\n'),/CHANGELOG\.md/);assert.match(run(engine,state,'cat Scripts/cleanup.sh').stdout.join('\n'),/nothing has been deleted/);assert.ok(run(engine,state,'find Tickets -type f').stdout.length>=10);assert.match(run(engine,state,'cat Tickets/2023/TKT-2023-041.md').stdout.join('\n'),/Printer-03/);assert.match(run(engine,state,'cat Documents/office/printer-03-service.md').stdout.join('\n'),/TKT-2023-041/);assert.deepEqual(run(engine,state,'find Mail -type f').stdout,['/home/m.weber/Mail/Archive/README','/home/m.weber/Mail/Inbox/2026-07-29-new-printer-cartridge.eml']);assert.match(run(engine,state,'cat Mail/Inbox/2026-07-29-new-printer-cartridge.eml').stdout.join('\n'),/From: Emma Weber <robodad@michamailgate.com>[\s\S]*To: Michael Weber <michael.weber@chesapeakesignaltech.com>[\s\S]*Subject: New printer cartridge\?[\s\S]*Hey Robodad,[\s\S]*Emma/);assert.ok(run(engine,state,'cat .bash_history').stdout.length>200);});
test('personal and email archives are distinct filesystem locations',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);run(engine,state,'cd ~/Archive');const personal=run(engine,state,'ls').stdout.join('\n');for(const name of ['README','2019','2020','2021','2022','2023','2024','Projects','Photos','Documents'])assert.match(personal,new RegExp(`\\b${name}\\b`));assert.match(run(engine,state,'cat README').stdout.join('\n'),/personal archive for older files and finished projects/);run(engine,state,'cd ~/Mail/Archive');assert.deepEqual(run(engine,state,'ls').stdout,['README']);const mailReadme=run(engine,state,'cat README').stdout.join('\n');assert.equal(mailReadme,'Older email is stored in the encrypted company archive.\n\nThis workstation keeps only the active local mailbox.\n\nHistorical mail can be restored if required.');assert.deepEqual(run(engine,state,'find . -type f').stdout,['/home/m.weber/Mail/Archive/README']);});
test('workstation writes stay in Michael home',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);assert.equal(run(engine,state,'touch Notes/today.txt').exitCode,0);assert.equal(run(engine,state,'touch /etc/nope').exitCode,1);run(engine,state,'cd Projects');run(engine,state,'cd');assert.equal(state.currentDirectory,'/home/m.weber');});
test('shared completion handles unique, ambiguous, missing, home, and spaced paths',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state),input={value:'cat No',selectionStart:6,selectionEnd:6},seen=[];engine.fs.add('/tmp/completion',{name:'',type:'directory',owner:'m.weber',group:'m.weber',mode:'drwxr-xr-x',children:{'Notes.txt':{name:'Notes.txt',type:'file',owner:'m.weber',group:'m.weber',mode:'-rw-r--r--',content:'',created:'',modified:''}},created:'',modified:''});state.currentDirectory='/tmp/completion';completeTerminalInput(input,state,engine.fs,Object.keys(commands),x=>seen.push(x));assert.equal(input.value,'cat Notes.txt');state.currentDirectory='/home/m.weber';input.value='cd Pro';input.selectionStart=6;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cd Projects/');input.value='cd ~/Pho';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cd ~/Photos/');input.value='cat missing';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cat missing');input.value='cat D';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands),x=>seen.push(x));assert.equal(input.value,'cat D');assert.ok(seen.at(-1).length>1);state.currentDirectory='/home/m.weber/Downloads';input.value='cat RFC';input.selectionStart=input.value.length;completeTerminalInput(input,state,engine.fs,Object.keys(commands));assert.equal(input.value,'cat RFC\\ notes.txt');});
test('workstation prompts abbreviate Michael home without duplicating paths',()=>{const renderer=Object.create(TerminalRenderer.prototype);renderer.user='m.weber';renderer.hostname='workstation';renderer.home='/home/m.weber';assert.equal(renderer.promptText('/home/m.weber'),'m.weber@workstation:~$');assert.equal(renderer.promptText('/home/m.weber/Downloads'),'m.weber@workstation:~/Downloads$');assert.equal(renderer.promptText('/home/m.weber/Projects/monitoring'),'m.weber@workstation:~/Projects/monitoring$');});
test('ls keeps logical output alongside presentation metadata and fastfetch uses a fixed workstation profile',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state),listing=engine.execute('ls');assert.match(listing.stdout[0],/Projects/);assert.ok(listing.styledLines[0].some(token=>token.type==='directory'&&token.text.includes('Projects')));const info=engine.execute('fastfetch').stdout.join('\n');assert.match(info,/OS: Debian GNU\/Linux 13 \(trixie\)/);assert.match(info,/Kernel: Linux 6\.12\.38\+deb13-amd64/);assert.match(info,/Terminal: tty1/);assert.match(info,/Uptime: 1 day, 1 hour, 30 minutes/);assert.doesNotMatch(info,/fictional browser|browser-only|simulated bash|Web Terminal|local browser state|navigator|deviceMemory|hardwareConcurrency/i);});

test('workstation shell exposes immersive exit, help, and guarded reset commands',()=>{const state=defaultWorkstationState(),engine=new ShellEngine(state);assert.equal(engine.execute('exit').exit,true);assert.equal(engine.execute('logout').exit,true);assert.equal(engine.execute('reset-workstation').resetWorkstation,true);const help=engine.execute('help').stdout.join('\n');for(const text of ['Tab completes commands and paths','Arrow Up and Down navigate history','Ctrl+L clears the terminal','Ctrl+C cancels current input','exit leaves the workstation','reset-workstation'])assert.match(help,new RegExp(text.replace('+','\\+')));assert.doesNotMatch(help,/browser|localStorage|webpage|button/i);assert.match(engine.execute('Leave workstation').stderr[0],/bash: Leave: command not found/);});

test('workstation route is terminal-only while the project page retains disclosure',async()=>{const workstation=await readFile(new URL('../lost-administrator/workstation/index.html',import.meta.url),'utf8'),landing=await readFile(new URL('../lost-administrator/index.html',import.meta.url),'utf8'),registry=await readFile(new URL('../assets/js/debian-server/command-registry.js',import.meta.url),'utf8');for(const text of ['>Home<','THE LOST ADMINISTRATOR','MICHAEL\'S WORKSTATION','LOCAL SESSION','LEAVE WORKSTATION','RESET LOCAL WORKSTATION','Fictional browser-only environment','<footer','Impressum','Datenschutz'])assert.doesNotMatch(workstation,new RegExp(text,'i'));assert.match(workstation,/workstation-viewport/);for(const text of ['fictional','locally inside the browser','no real shell','access to the visitor’s computer'])assert.match(landing,new RegExp(text,'i'));assert.doesNotMatch(registry,/navigator\.|deviceMemory|hardwareConcurrency|performance\.memory/);});

class MockElement {
  constructor(doc){this.ownerDocument=doc;this.children=[];this.listeners=new Map();this.value='';this.textContent='';this.scrollTop=0;this.scrollHeight=0;}
  addEventListener(type,listener){this.listeners.set(type,listener);}
  dispatchEvent(event){event.target=this;this.listeners.get(event.type)?.(event);}
  append(...children){this.children.push(...children);}
  replaceChildren(...children){this.children=[...children];}
  focus(){this.ownerDocument.activeElement=this;}
  blur(){this.ownerDocument.activeElement=null;}
  set className(value){this._className=value;}
}
const enter=element=>element.dispatchEvent({type:'keydown',key:'Enter',ctrlKey:false,preventDefault(){}});
test('controller navigates without erasing state and reset requires exact YES',async()=>{const elements=new Map(),doc={activeElement:null,querySelector:s=>elements.get(s)||null,createElement:()=>new MockElement(doc),defaultView:{}};for(const selector of ['#debian-terminal','#terminal-history','#terminal-input','#terminal-prompt-text'])elements.set(selector,new MockElement(doc));const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};let destination=null,reloads=0;const view={localStorage:storage,location:{assign:value=>destination=value,reload:()=>reloads++}};globalThis.document=doc;globalThis.window=view;const {initializeWorkstation}=await import(`../assets/js/lost-administrator/workstation-controller.js?test=${Date.now()}`);initializeWorkstation(doc,view,storage);const input=elements.get('#terminal-input');input.value='touch Notes/persistent.txt';enter(input);input.value='exit';enter(input);assert.equal(destination,'/lost-administrator/');assert.ok(JSON.parse(data.get(WORKSTATION_STORAGE_KEY)).filesystem.children.home.children['m.weber'].children.Notes.children['persistent.txt']);assert.doesNotMatch(elements.get('#terminal-history').children.map(x=>x.textContent).join('\n'),/Leave workstation|remains available in the browser/i);
  input.value='reset-workstation';enter(input);assert.ok(data.has(WORKSTATION_STORAGE_KEY));input.value='yes';enter(input);assert.ok(data.has(WORKSTATION_STORAGE_KEY));assert.equal(reloads,0);input.value='reset-workstation';enter(input);input.value='YES';enter(input);assert.equal(data.has(WORKSTATION_STORAGE_KEY),false);assert.equal(reloads,1);const restored=loadWorkstationState(storage);assert.equal(restored.currentDirectory,'/home/m.weber');assert.equal(restored.filesystem.children.home.children['m.weber'].children.Notes.children['persistent.txt'],undefined);assert.equal(doc.activeElement,input);delete globalThis.document;delete globalThis.window;});

test('controller uses the existing terminal for mail, quit, and Ctrl+C',async()=>{const elements=new Map(),doc={activeElement:null,querySelector:s=>elements.get(s)||null,createElement:()=>new MockElement(doc),defaultView:{}};for(const selector of ['#debian-terminal','#terminal-history','#terminal-input','#terminal-prompt-text'])elements.set(selector,new MockElement(doc));const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const view={localStorage:storage,location:{assign(){},reload(){}}};globalThis.document=doc;globalThis.window=view;const {initializeWorkstation}=await import(`../assets/js/lost-administrator/workstation-controller.js?mail=${Date.now()}`);initializeWorkstation(doc,view,storage);const input=elements.get('#terminal-input'),prompt=elements.get('#terminal-prompt-text');input.value='mail';enter(input);assert.equal(prompt.children[0].textContent,'mail>');assert.match(elements.get('#terminal-history').children.map(x=>x.textContent).join('\n'),/michael\.weber@chesapeakesignaltech\.com/);input.value='quit';enter(input);assert.equal(prompt.children.map(x=>x.textContent).join(''),'m.weber@workstation:~$');input.value='mail';enter(input);input.dispatchEvent({type:'keydown',key:'c',ctrlKey:true,preventDefault(){}});assert.equal(prompt.children.map(x=>x.textContent).join(''),'m.weber@workstation:~$');delete globalThis.document;delete globalThis.window;});
