const assert = require('assert');
const pcxt = require('../museum/ibm-pc-xt/pcxt.js');
const state = pcxt.defaultState();
assert.strictEqual(pcxt.STORAGE_KEY, 'computerMuseum.pcXtCommandDesk.v1');
assert.ok(pcxt.validateState(state));
assert.deepStrictEqual(pcxt.normalizePath('C:\\GAMES\\DOOM', []).parts, ['GAMES','DOOM']);
assert.deepStrictEqual(pcxt.normalizePath('..', []).parts, []);
assert.deepStrictEqual(pcxt.normalizePath('..', ['GAMES']).parts, []);
assert.deepStrictEqual(pcxt.normalizePath('\\WINDOWS', ['GAMES']).parts, ['WINDOWS']);
assert.deepStrictEqual(pcxt.normalizePath('..\\README.TXT', ['WINDOWS']).parts, ['README.TXT']);
assert.deepStrictEqual(pcxt.normalizePath('"README.TXT"', []).parts, ['README.TXT']);
assert.strictEqual(pcxt.lookup(state.filesystem, ['GAMES','WOLF3D']).type, 'directory');
assert.strictEqual(pcxt.lookup(state.filesystem, ['AUTOEXEC.BAT']).type, 'file');
assert.strictEqual(pcxt.bytes('ABC'), 3);
assert.strictEqual(pcxt.bytes('é'), 2);
assert.ok(pcxt.stats(state.filesystem).files >= 12);
state.cwd = ['GAMES'];
assert.strictEqual(pcxt.renderPromptFormat(state), 'C:\\GAMES>');
assert.deepStrictEqual(pcxt.splitCommand('TYPE C:\\README.TXT'), { command:'TYPE', args:'C:\\README.TXT' });
assert.strictEqual(pcxt.validateState({ schemaVersion:1, filesystem:{ type:'file' } }), false);

const autoexec = pcxt.lookup(state.filesystem, ['AUTOEXEC.BAT']);
const originalCreatedAt = autoexec.createdAt;
const originalModifiedAt = autoexec.modifiedAt;
assert.deepStrictEqual(pcxt.canEditNode(autoexec), { ok:true });
assert.strictEqual(pcxt.canEditNode(pcxt.lookup(state.filesystem, ['GAMES'])).reason, 'Cannot edit a directory');
assert.strictEqual(pcxt.canEditNode(null).reason, 'File not found');
assert.strictEqual(pcxt.canEditNode({ type:'file', content:'A\u0000B' }).reason, 'File type not supported by EDIT');
assert.strictEqual(pcxt.canEditNode({ type:'file', content:'A'.repeat(pcxt.EDIT_MAX_BYTES + 1) }).reason, 'File too large for EDIT v1 (64 KiB limit)');
assert.strictEqual(pcxt.isEditorDirty('same', 'same'), false);
assert.strictEqual(pcxt.isEditorDirty('same', 'changed'), true);
assert.strictEqual(pcxt.writeFileContent(autoexec, autoexec.content + 'SET MUSEUM=ONLINE\n', '1992-04-06T09:00:00.000Z'), true);
assert.strictEqual(autoexec.createdAt, originalCreatedAt);
assert.notStrictEqual(autoexec.modifiedAt, originalModifiedAt);
assert.strictEqual(autoexec.modifiedAt, '1992-04-06T09:00:00.000Z');
assert(autoexec.content.includes('SET MUSEUM=ONLINE'));
assert(pcxt.stats(state.filesystem).used > 0);
assert.doesNotThrow(() => JSON.stringify(state));
console.log('pcxt-command-desk tests passed');
