const fs = require('fs');
const assert = require('assert');
const page = fs.readFileSync('world-observer/time-observer.html', 'utf8');
const script = fs.readFileSync('world-observer/time-observer.js', 'utf8');
const css = fs.readFileSync('world-observer/time-observer.css', 'utf8');
const tech = fs.readFileSync('world-observer/technology.html', 'utf8');
const snapshot = JSON.parse(fs.readFileSync('world-observer/dashboard/latest/time-observer.json', 'utf8'));
assert.match(page, /LOCAL SYSTEM CLOCK/);
['TAI', 'UTC', 'UT1', 'NTP'].forEach(term => assert.match(page, new RegExp(term)));
assert.match(page, /EDUCATIONAL SIMULATION/);
assert.match(page, /UTC already differed from TAI by 10 seconds/);
assert.doesNotMatch(page + script, /ATOMIC ACCURACY|synchronized to atomic clock|measured UTC offset/i);
assert.match(script, /\/world-observer\/dashboard\/latest\/time-observer\.json/);
assert.match(script, /earth_orientation/); assert.match(script, /leap_seconds/); assert.match(script, /DATA UNAVAILABLE/);
assert.doesNotMatch(script, /https?:\/\/(?:[^"']*\.)?(?:iers|bipm|nist|ptb)/i);
assert.match(script, /renderLeap\(d\?\.leap_seconds\)/);
assert.match(script, /provenanceSummary\(d\?\.provenance\)/);
assert.match(script, /IERS — Earth Orientation Parameters \(UT1−UTC\)/);
assert.doesNotMatch(script, /JSON\.stringify\(d\.provenance\)/);
assert.match(css, /#provenance\{white-space:pre-line\}/);
assert.match(script, /String\(eo.status/); assert.match(css, /prefers-reduced-motion/);
assert.match(tech, /time-observer\.html[\s\S]*AVAILABLE/);
assert.equal(snapshot.earth_orientation.status, 'predicted');
assert.equal(snapshot.leap_seconds[0].tai_minus_utc_seconds, 10);
assert.equal(snapshot.leap_seconds.length, 28);
console.log('Time Observer regression checks passed');
assert.match(script, /generated_at_utc/);
assert.match(css, /max-width:1180px/);
assert.match(css, /@media\(max-width:760px\)/);
assert.match(page, /UTC DISPLAY · DERIVED FROM DEVICE CLOCK/);
assert.match(page, /NO NETWORK REQUEST/);
assert.equal((tech.match(/>Time Observer</g) || []).length, 1, 'Technology page must expose one Time Observer card');
assert.match(tech, /Time &amp; Synchronization[\s\S]*time-observer\.html[\s\S]*AVAILABLE/);
assert.match(fs.readFileSync('sitemap.xml', 'utf8'), /world-observer\/time-observer\.html/);
