import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {UnixSimulation} from '../museum/unix-time-sharing-center/unix-simulation.js';
import {COMMANDS,UnixShell} from '../museum/unix-time-sharing-center/unix-shell.js';
import {HANDSHAKE_MAKEUP_GAIN} from '../museum/bbs-system/bbs.js';
import {BRIDGE_HANDSHAKE_GAIN,CONNECTION_TIMING,REMOTE_TARGET,REMOTE_TARGETS,parseDialCommand,createBbsBridge,createHandshakeAudio} from '../museum/unix-time-sharing-center/unix-remote.js';
const shell=()=>new UnixShell(()=>new UnixSimulation({random:()=>.5}));
test('dial registry is a single fictional allowlist',()=>{assert.equal(REMOTE_TARGETS.length,1);assert.deepEqual(REMOTE_TARGET,{name:'midnight-relay',aliases:['research-net'],number:'5550194',displayNumber:'555-0194',device:'/dev/cu1',speed:9600,format:'8N1',service:'The Midnight Relay BBS'});assert.equal(parseDialCommand('tip',['example']).error,'tip: unknown host example');assert.equal(parseDialCommand('cu',['123']).error,'NO CARRIER');assert.match(parseDialCommand('cu',['-l','/dev/cu2','5550194']).error,/No such device/);assert.match(parseDialCommand('cu',['-s','19200','5550194']).error,/unsupported speed/)});
test('tip and cu are registry commands and enter explicit dialing mode',()=>{for(const name of ['tip','cu'])assert(COMMANDS.has(name));let s=shell(),r=s.execute('tip midnight-relay');assert.equal(s.mode,'dialing');assert.equal(r.dial.target,REMOTE_TARGET);s=shell();r=s.execute('cu -l /dev/cu1 -s 9600 5550194');assert.equal(s.mode,'dialing');assert.equal(r.dial.program,'cu');assert.match(s.execute('help cu').lines.join('\n'),/browser-only/)});
test('BBS bridge reuses real dispatcher and isolated ANSI screens',()=>{const a=createBbsBridge(),b=createBbsBridge();assert.equal(a.runtime.context,'logon');assert.equal(a.screen.columns,80);assert.equal(a.screen.rows,25);a.input('GUEST');assert.equal(a.runtime.context,'main');assert.equal(b.runtime.context,'logon');a.input('?');assert.match(a.screen.toString(),/MAIN|Command/i);a.destroy();b.destroy()});
test('BBS module only auto-starts on the standalone workstation',()=>{const source=fs.readFileSync(new URL('../museum/bbs-system/bbs.js',import.meta.url),'utf8');assert.match(source,/getElementById\('terminal-form'\)\)new BBSApp/);assert.doesNotMatch(source,/getElementById\('terminal'\)\)new BBSApp/)});
test('blocked modem audio uses the one configured handshake fallback duration',async()=>{let scheduled;const view={performance:{now:()=>0},setTimeout(callback,delay){scheduled={callback,delay};return 1},clearTimeout(){},Audio:class{addEventListener(){}play(){return Promise.reject(new Error('blocked'))}pause(){}removeAttribute(){}}};let finished=false;createHandshakeAudio(view).start().then(()=>{finished=true});await Promise.resolve();await Promise.resolve();assert.equal(CONNECTION_TIMING.handshakeFallbackMs,12000);assert.equal(scheduled.delay,CONNECTION_TIMING.handshakeFallbackMs);assert.equal(finished,false);scheduled.callback();await Promise.resolve();assert.equal(finished,true)});
test('bridge handshake doubles its old level through the protected Web Audio chain',async()=>{
 const contexts=[];const makeNode=()=>({connect(next){this.next=next;return next},disconnect(){this.disconnected=true},gain:{value:0}});
 class Context{constructor(){this.destination={};this.gains=[];contexts.push(this)}createMediaElementSource(){return this.source=makeNode()}createGain(){const node=makeNode();this.gains.push(node);return node}createDynamicsCompressor(){return this.limiter=Object.assign(makeNode(),{threshold:{},knee:{},ratio:{},attack:{},release:{}})}resume(){return Promise.resolve()}close(){this.closed=true;return Promise.resolve()}}
 const audios=[];const view={performance:{now:()=>0},Audio:class{constructor(){const audio={volume:0,addEventListener(type,fn){if(type==='ended')this.ended=fn},play(){return Promise.resolve()},pause(){this.paused=true},removeAttribute(){}};audios.push(audio);return audio}},AudioContext:Context,setTimeout(){return 1},clearTimeout(){}};
 const playback=createHandshakeAudio(view),first=playback.start();assert.equal(BRIDGE_HANDSHAKE_GAIN,.88);assert.equal(contexts[0].gains[0].gain.value,BRIDGE_HANDSHAKE_GAIN);assert.equal(contexts[0].gains[1].gain.value,HANDSHAKE_MAKEUP_GAIN);assert.ok(HANDSHAKE_MAKEUP_GAIN<=1.5);assert.equal(contexts[0].limiter.threshold.value,-10);assert.equal(contexts[0].limiter.knee.value,12);assert.equal(contexts[0].limiter.ratio.value,4);
 const second=playback.start();await first;assert.equal(contexts.length,2);assert.equal(contexts[0].closed,true);assert.equal(audios[0].paused,true);audios[1].ended();await second;assert.equal(contexts[1].closed,true);playback.stop();
});
test('bridged banner forwards complete ANSI safely to the existing screen',()=>{const bridge=createBbsBridge(),text=bridge.screen.toString(),cyan=bridge.screen.cells.flat().find(cell=>cell.ch==='+');assert.doesNotMatch(text,/;36m/);assert.match(text,/^Checking terminal capabilities/m);assert.match(text,/^\+={20,}/m);assert.equal(cyan.fg,6);assert.equal(cyan.intense,true);bridge.screen.writeTrusted('[31malert(1)<script>[');assert.match(bridge.screen.toString(),/alert\(1\)<script>/);bridge.destroy()});
test('UNIX route is internal and contains no unsafe connection surface',()=>{const files=['../museum/unix-time-sharing-center/index.html','../museum/unix-time-sharing-center/unix-center.js','../museum/unix-time-sharing-center/unix-remote.js'].map(p=>fs.readFileSync(new URL(p,import.meta.url),'utf8')).join('\n');assert.doesNotMatch(files,/<iframe|WebSocket|WebRTC|fetch\(|location\s*=|document\.write|new Function|eval\(/);assert.match(files,/tip midnight-relay/);assert.match(files,/cu -l \/dev\/cu1 -s 9600 5550194/)});
