// Editorial decision trees. Commands are displayed, never executed.
const tr = (en, de) => ({ en, de });
const rows = [
  ['gpu-unbound', 'GPU detected, binding unclear', 'GPU erkannt, Bindung unklar',
    'Does lspci -nnk show the GPU with no reported driver or an explicit unclaimed state?', 'Zeigt lspci -nnk die GPU ohne gemeldeten Treiber oder meldet ein anderer Bericht ausdrücklich unclaimed?',
    'Does the kernel log show a probe, firmware or module rejection for this same PCI address?', 'Zeigt das Kernel-Log für genau diese PCI-Adresse einen Probe-, Firmware- oder Modulfehler?',
    'lspci -nnk', 'journalctl -b -k --no-pager',
    'A device-specific initialization error is evidence for investigating that binding path. Keep its PCI address and boot context separate from errors from another GPU. The absence of a driver line alone is not proof that a pasted excerpt is complete.',
    'Ein gerätebezogener Initialisierungsfehler spricht dafür, diesen Bindungsweg zu prüfen. Trenne PCI-Adresse und Boot-Kontext von Fehlern einer anderen GPU. Eine fehlende Treiberzeile beweist nicht, dass der eingefügte Auszug vollständig ist.',
    'A reported bound driver changes the next question: inspect the rendering stack and selected GPU rather than assuming a missing kernel module.',
    'Ein gemeldeter gebundener Treiber verändert die nächste Frage: Prüfe Grafikstack und ausgewählte GPU, statt ein fehlendes Kernelmodul anzunehmen.',
    ['mesa-software-rendering', 'vulkan-driver-discovery', 'hybrid-gpu-selection']],
  ['amdgpu-firmware', 'AMDGPU firmware request failed', 'AMDGPU-Firmware-Anfrage fehlgeschlagen',
    'Is there a named firmware-loading failure next to the AMD GPU initialization?', 'Steht beim Initialisieren der AMD-GPU ein Ladefehler für eine benannte Firmwaredatei?',
    'Does initialization still fail after the request, rather than proceeding with another firmware path?', 'Scheitert die Initialisierung anschließend weiter, statt mit einem anderen Firmwareweg fortzufahren?',
    'journalctl -b -k --no-pager', 'modinfo -F firmware amdgpu',
    'Compare the requested filename, running kernel and distribution payload. The module firmware list can include files for other AMD devices, so its full list is not a shopping list for your GPU. Early boot can need the matching file in the initramfs.',
    'Vergleiche angefragten Dateinamen, laufenden Kernel und Distributionspaket. Die Firmwareliste des Moduls kann Dateien für andere AMD-Geräte enthalten und ist keine Einkaufsliste für deine GPU. Beim frühen Start kann die passende Datei im Initramfs benötigt werden.',
    'Without a relevant failing request, do not label a freeze as missing firmware. Separate queue timeouts, virtual-memory faults and rendering fallback evidence.',
    'Ohne passende fehlgeschlagene Anfrage ist ein Freeze kein Nachweis fehlender Firmware. Trenne Queue-Timeouts, virtuelle Speicherfehler und Hinweise auf Software-Rendering.',
    ['amdgpu-missing-firmware', 'amdgpu-ring-timeout', 'amdgpu-vm-page-fault']],
  ['nvidia-module', 'NVIDIA module is not usable', 'NVIDIA-Modul nicht nutzbar',
    'Is the NVIDIA device enumerated while the expected NVIDIA kernel driver is not reported as bound?', 'Ist das NVIDIA-Gerät aufgelistet, während der erwartete NVIDIA-Kerneltreiber nicht als gebunden gemeldet wird?',
    'Does the log contain a module signature rejection or a kernel/module version error?', 'Enthält das Log eine abgelehnte Modulsignatur oder einen Fehler zur Kernel-/Modulversion?',
    'lspci -nnk', 'journalctl -b -k --no-pager',
    'Distinguish authentication rejection from a missing module and from a built module that targets another kernel. A driver release supporting an ID does not prove that its local build, signature and userspace libraries agree.',
    'Trenne Authentifizierungsablehnung, fehlendes Modul und ein für einen anderen Kernel gebautes Modul. Eine Treiberausgabe mit passender ID beweist nicht, dass lokaler Build, Signatur und Userspace-Bibliotheken zusammenpassen.',
    'If nvidia is bound, inspect a userspace library mismatch or suspend-specific fault; do not unload a working display driver during an active desktop session.',
    'Ist nvidia gebunden, prüfe einen Userspace-Bibliothekskonflikt oder einen Suspend-Fehler. Entlade keinen funktionierenden Anzeigetreiber während einer aktiven Desktopsitzung.',
    ['nvidia-module-signature-rejected', 'kernel-module-vermagic', 'nvidia-driver-library-mismatch', 'nvidia-nouveau-driver-conflict']],
  ['intel-initialization', 'Intel graphics initialization', 'Intel-Grafik initialisieren',
    'Does the Intel device appear in PCI output with i915 or xe binding evidence?', 'Erscheint das Intel-Gerät in der PCI-Ausgabe mit Bindungshinweisen auf i915 oder xe?',
    'Does the current boot contain a device-specific initialization error or GPU hang?', 'Enthält der aktuelle Start einen gerätebezogenen Initialisierungsfehler oder GPU-Hang?',
    'lspci -nnk', 'journalctl -b -k --no-pager',
    'Check the installed driver configuration and firmware request for this platform. The catalog distinguishes driver generations, but it cannot select force_probe parameters or promise that exchanging i915 and xe will fix a hang.',
    'Prüfe installierte Treiberkonfiguration und Firmwareanfrage für diese Plattform. Der Katalog trennt Treibergenerationen, kann aber keine force_probe-Parameter auswählen oder versprechen, dass ein Wechsel zwischen i915 und xe einen Hang behebt.',
    'If a driver is not reported, collect binding and modalias evidence first. Display routing on a hybrid laptop can make a working Intel device invisible to a particular application.',
    'Wird kein Treiber gemeldet, erfasse zuerst Bindung und Modalias. Die Anzeigeroute eines Hybrid-Laptops kann ein funktionierendes Intel-Gerät für eine bestimmte Anwendung unsichtbar machen.',
    ['intel-gpu-hang', 'hybrid-gpu-selection', 'mesa-software-rendering']],
  ['wifi-unavailable', 'Wi-Fi adapter unavailable', 'WLAN-Adapter nicht verfügbar',
    'Is the Wi-Fi adapter visible in PCI or USB output?', 'Ist der WLAN-Adapter in der PCI- oder USB-Ausgabe sichtbar?',
    'Is an rfkill block or failed device firmware request reported for the same adapter?', 'Wird für denselben Adapter eine rfkill-Sperre oder fehlgeschlagene Geräte-Firmware-Anfrage gemeldet?',
    'lspci -nnk', 'rfkill list',
    'A hard rfkill block and a firmware-load failure are different paths. Identify which observation is present before touching NetworkManager settings or selecting a firmware package.',
    'Eine harte rfkill-Sperre und ein Firmware-Ladefehler sind unterschiedliche Wege. Kläre zuerst den vorhandenen Befund, bevor du NetworkManager-Einstellungen änderst oder ein Firmwarepaket auswählst.',
    'If the adapter is absent from enumeration, inspect its bus, platform switch and USB connection first. No driver recommendation can replace a device that the guest or host never enumerated.',
    'Fehlt der Adapter in der Auflistung, prüfe zuerst Bus, Plattformschalter und USB-Verbindung. Eine Treiberempfehlung ersetzt kein Gerät, das Gast oder Host gar nicht aufgelistet hat.',
    ['network-wifi-rfkill', 'network-wifi-firmware-missing', 'network-unmanaged-interface']],
  ['ethernet-no-driver', 'Ethernet controller without usable link', 'Ethernet-Controller ohne nutzbare Verbindung',
    'Is a driver binding reported for the Ethernet controller?', 'Wird eine Treiberbindung für den Ethernet-Controller gemeldet?',
    'Does the interface exist but report no carrier or a watchdog timeout?', 'Existiert die Schnittstelle, meldet aber keinen Carrier oder einen Watchdog-Timeout?',
    'lspci -nnk', 'ip -br link',
    'Binding and link training are separate. Use the interface name from local output for ethtool checks, then compare cable, transceiver and negotiated link with the device capability. A PCI ID is not proof of a working carrier.',
    'Bindung und Link-Aufbau sind getrennt. Verwende für ethtool den Schnittstellennamen aus deiner lokalen Ausgabe und vergleiche Kabel, Transceiver und ausgehandelten Link mit den Fähigkeiten des Geräts. Eine PCI-ID beweist keinen funktionierenden Carrier.',
    'Without reported binding, collect the numeric ID and modalias before installing a similarly named vendor module. A virtual machine may intentionally bind the physical device to vfio-pci on the host.',
    'Ohne gemeldete Bindung erfasse numerische ID und Modalias, bevor du ein ähnlich benanntes Herstellermodul installierst. Bei einer VM kann das physische Gerät auf dem Host absichtlich an vfio-pci gebunden sein.',
    ['network-ethernet-carrier', 'network-driver-watchdog', 'network-unmanaged-interface']],
  ['pcie-link', 'PCIe speed or width below expectation', 'PCIe-Geschwindigkeit oder -Breite niedriger als erwartet',
    'Do LnkCap and LnkSta differ on the endpoint or one of its upstream bridges?', 'Unterscheiden sich LnkCap und LnkSta am Endgerät oder einer vorgeschalteten Brücke?',
    'Is the lower negotiated link persistent under the relevant load, or accompanied by AER errors?', 'Bleibt der niedriger ausgehandelte Link bei der relevanten Last bestehen oder treten zusätzlich AER-Fehler auf?',
    'lspci -vv -s BDF', 'lspci -t',
    'Compare each hop in the PCIe path and the documented slot topology. Capability is a maximum, not a guarantee; an intentional lane split, bridge limitation or power state may differ from a signal problem. AER adds evidence but does not identify the faulty part by itself.',
    'Vergleiche jeden Abschnitt des PCIe-Pfads und die dokumentierte Slot-Topologie. Eine Fähigkeit ist ein Maximum, keine Garantie. Absichtliche Lane-Aufteilung, Brückenbegrenzung oder Stromsparzustand sind von einem Signalproblem zu trennen. AER liefert Hinweise, benennt allein aber nicht das defekte Teil.',
    'Without a measured capability/state difference, a product label or marketing generation is insufficient. Collect the actual endpoint and bridge output; do not start with global ASPM or IOMMU changes.',
    'Ohne gemessene Abweichung zwischen Fähigkeit und Zustand reichen Produktname oder beworbene Generation nicht. Erfasse Endgerät und Brücken; beginne nicht mit globalen ASPM- oder IOMMU-Änderungen.',
    ['kernel-pcie-aer-errors', 'nvidia-gpu-fallen-off-bus']],
  ['usb-disconnect', 'Repeated USB disconnects', 'Wiederholte USB-Trennungen',
    'Does the current boot log show disconnect/reset events for the same USB port path?', 'Zeigt das aktuelle Boot-Log Trennungs- oder Reset-Ereignisse für denselben USB-Portpfad?',
    'Do the events also occur on a direct port with the same workload, rather than only on one hub?', 'Treten die Ereignisse bei derselben Last auch am direkten Port auf, statt nur an einem bestimmten Hub?',
    'journalctl -b -k --no-pager', 'lsusb -t',
    'Retain the port path and timestamps when comparing observations. A repeat on a direct port narrows the hub hypothesis but does not prove a driver bug; cable, power, device firmware and the controller remain separate possibilities.',
    'Behalte beim Vergleich Portpfad und Zeitstempel. Eine Wiederholung am direkten Port grenzt die Hub-Hypothese ein, beweist aber keinen Treiberfehler. Kabel, Versorgung, Gerätefirmware und Controller bleiben getrennte Möglichkeiten.',
    'Without matching disconnect evidence, distinguish an application permission problem from bus removal. Enumeration can survive an application losing access to a device.',
    'Ohne passende Trennungshinweise trenne ein Berechtigungsproblem der Anwendung von einer Bus-Entfernung. Ein Gerät kann weiterhin aufgelistet sein, obwohl eine Anwendung den Zugriff verliert.',
    ['storage-usb-uas-resets', 'audio-usb-rate-clock', 'audio-session-device-access']],
  ['nvme-timeout', 'NVMe timeout or controller reset', 'NVMe-Timeout oder Controller-Reset',
    'Does the log identify an NVMe controller timeout or reset?', 'Benennt das Log einen NVMe-Controller-Timeout oder -Reset?',
    'Is the observation tied to idle/resume rather than only to sustained I/O?', 'Ist der Befund an Leerlauf oder Resume gebunden, statt nur an anhaltende E/A?',
    'journalctl -b -k --no-pager', 'lsblk -o NAME,TYPE,TRAN,MODEL',
    'An idle/resume correlation is a reason to examine the documented power-management path. Keep the controller identity distinct from its namespaces and filesystem. Collect evidence before changing APST settings; do not format or update drive firmware from a generic recommendation.',
    'Ein Zusammenhang mit Leerlauf oder Resume ist ein Grund, den dokumentierten Stromsparweg zu prüfen. Trenne Controller-Identität, Namespaces und Dateisystem. Sammle Hinweise vor APST-Änderungen; formatiere nicht und aktualisiere keine Laufwerksfirmware aufgrund eines allgemeinen Hinweises.',
    'No NVMe reset evidence means application stalls or filesystem messages need their own investigation. A detected NVMe controller is not a drive-health certificate.',
    'Ohne NVMe-Reset-Hinweise brauchen Anwendungsruckler oder Dateisystemmeldungen eine eigene Prüfung. Ein erkannter NVMe-Controller ist kein Nachweis für einen gesunden Datenträger.',
    ['storage-nvme-idle-resume', 'storage-nvme-controller-reset', 'io-pressure-writeback-latency']],
  ['sata-crc', 'SATA CRC or link resets', 'SATA-CRC-Fehler oder Link-Resets',
    'Do libata messages include BadCRC, handshake errors or hard-resetting link for one ata port?', 'Enthalten libata-Meldungen BadCRC, Handshake-Fehler oder hard resetting link für einen ata-Port?',
    'Is there independent media-error evidence as well, instead of only interface error counters?', 'Gibt es zusätzlich unabhängige Hinweise auf Medienfehler statt nur Schnittstellen-Fehlerzähler?',
    'journalctl -b -k --no-pager', 'lsblk -o NAME,TYPE,TRAN,MODEL',
    'Interface transport errors and unreadable media can coexist. Map the ata port to the actual drive before comparing cable/port changes or health counters. Historical CRC totals need a before/after comparison; one nonzero counter does not establish a current fault.',
    'Schnittstellen-Transportfehler und unlesbare Medien können gleichzeitig auftreten. Ordne den ata-Port dem echten Laufwerk zu, bevor du Kabel-/Portwechsel oder Gesundheitszähler vergleichst. Historische CRC-Summen brauchen einen Vorher-/Nachher-Vergleich; ein einzelner Zählerstand beweist keinen aktuellen Fehler.',
    'Without transport-error evidence, do not explain every I/O stall as a SATA cable fault. Separate workload pressure, filesystem state and storage media observations.',
    'Ohne Transportfehler-Hinweise ist nicht jeder E/A-Ruckler ein SATA-Kabelfehler. Trenne Lastdruck, Dateisystemzustand und Beobachtungen zum Speichermedium.',
    ['storage-sata-crc-errors', 'storage-uncorrectable-sectors', 'io-pressure-writeback-latency']],
  ['bluetooth-firmware', 'Bluetooth firmware or transport', 'Bluetooth-Firmware oder Transport',
    'Is a Bluetooth controller visible on USB or a documented UART transport?', 'Ist ein Bluetooth-Controller über USB oder einen dokumentierten UART-Transport sichtbar?',
    'Does the same controller fail a named firmware download or initialization step?', 'Scheitert bei demselben Controller ein benannter Firmware-Download oder Initialisierungsschritt?',
    'lsusb', 'journalctl -b -k --no-pager',
    'Match the transport and controller revision before selecting a firmware file. A combo Wi-Fi card can expose Bluetooth separately over USB; the Wi-Fi PCI driver does not prove Bluetooth binding or firmware success.',
    'Ordne Transport und Controller-Revision zu, bevor du eine Firmwaredatei auswählst. Eine kombinierte WLAN-Karte kann Bluetooth separat über USB anbieten. Der WLAN-PCI-Treiber beweist weder Bluetooth-Bindung noch erfolgreichen Firmwarestart.',
    'If no controller is enumerated, investigate platform power and transport first. If it initializes successfully but headset audio is wrong, move to the audio profile/session path.',
    'Wird kein Controller aufgelistet, prüfe zuerst Plattformversorgung und Transport. Initialisiert er erfolgreich, aber der Headset-Ton ist falsch, folge dem Audioprofil- und Sitzungsweg.',
    ['network-wifi-rfkill', 'audio-bluetooth-headset-profile']],
  ['audio-missing', 'Audio controller but no usable card', 'Audio-Controller ohne nutzbare Karte',
    'Does the kernel expose an ALSA card for the expected controller?', 'Stellt der Kernel für den erwarteten Controller eine ALSA-Karte bereit?',
    'Is the missing output specific to HDMI/display audio or a selected PipeWire profile?', 'Betrifft der fehlende Ausgang HDMI-/Display-Audio oder ein ausgewähltes PipeWire-Profil?',
    'cat /proc/asound/cards', 'wpctl status',
    'A controller, codec, ALSA card and session output are different layers. HDMI audio also depends on the connected display and ELD information. Avoid replacing a kernel driver when the hardware is already exposed and the session selected another output.',
    'Controller, Codec, ALSA-Karte und Sitzungsausgang sind unterschiedliche Ebenen. HDMI-Audio hängt auch am angeschlossenen Display und seinen ELD-Daten. Ersetze keinen Kerneltreiber, wenn die Hardware bereits bereitsteht und die Sitzung nur einen anderen Ausgang gewählt hat.',
    'Without an ALSA card, inspect controller binding and initialization before treating this as a PipeWire volume issue. Some platforms use SOF and additional topology firmware instead of a simple HDA-only path.',
    'Ohne ALSA-Karte prüfe Controller-Bindung und Initialisierung, bevor du ein PipeWire-Lautstärkeproblem annimmst. Manche Plattformen verwenden SOF und zusätzliche Topologiefirmware statt eines einfachen HDA-Wegs.',
    ['audio-alsa-card-missing', 'audio-hdmi-eld-missing', 'audio-default-output-muted', 'audio-pipewire-user-service']],
  ['module-missing', 'Kernel module unavailable', 'Kernelmodul nicht verfügbar',
    'Does modinfo report that the selected module is unavailable for the running kernel?', 'Meldet modinfo, dass das gewählte Modul für den laufenden Kernel nicht verfügbar ist?',
    'Does the running kernel configuration show the driver built in, rather than a loadable module?', 'Zeigt die Konfiguration des laufenden Kernels den Treiber fest eingebaut statt als ladbares Modul?',
    'modinfo MODULE', 'uname -r',
    'A built-in driver has no ordinary module file to load. Compare the installed kernel configuration and binding before concluding that a package is missing. If a loadable module exists but fails, vermagic and unresolved-symbol evidence require separate checks.',
    'Ein fest eingebauter Treiber hat keine normale Moduldatei zum Laden. Vergleiche Kernelkonfiguration und Bindung, bevor du ein fehlendes Paket annimmst. Existiert ein ladbares Modul, das scheitert, brauchen vermagic und ungelöste Symbole getrennte Prüfungen.',
    'If module information is available, its presence alone still does not establish device binding. Collect the kernel log around probe time; do not run force-load or unload commands based on a catalog candidate.',
    'Sind Modulinformationen verfügbar, beweist die bloße Anwesenheit weiterhin keine Gerätebindung. Erfasse das Kernel-Log beim Probe-Vorgang; lade oder entlade nichts erzwungen aufgrund eines Katalogkandidaten.',
    ['kernel-module-vermagic', 'kernel-module-unknown-symbol']],
  ['suspend-disappearance', 'Device disappears after suspend', 'Gerät verschwindet nach Suspend',
    'Does the device enumerate before suspend but disappear or fail binding afterward?', 'Wird das Gerät vor Suspend aufgelistet, verschwindet danach aber oder verliert seine Bindung?',
    'Do before/after logs identify one controller or transport, rather than only an application losing access?', 'Benennen Vorher-/Nachher-Logs einen Controller oder Transport, statt nur verlorenen Anwendungszugriff?',
    'lspci -nnk', 'journalctl -b -k --no-pager',
    'Record the device identity and exact transition before testing one change. A transport disappearing, a firmware reload failing and a userspace session restarting are different hypotheses. Keep a known working boot entry and save work before further suspend trials.',
    'Erfasse Geräteidentität und genauen Übergang, bevor du eine Änderung testest. Verschwundener Transport, fehlgeschlagener Firmware-Neustart und neu gestartete Userspace-Sitzung sind unterschiedliche Hypothesen. Behalte einen funktionierenden Boot-Eintrag und sichere Arbeit vor weiteren Suspend-Tests.',
    'If the device remains enumerated and bound, examine the affected session or application. Do not assume PCI removal solely from a black window or silent output.',
    'Bleibt das Gerät aufgelistet und gebunden, prüfe betroffene Sitzung oder Anwendung. Ein schwarzes Fenster oder stummer Ausgang beweist keine PCI-Entfernung.',
    ['kernel-suspend-aborted', 'nvidia-suspend-memory-preservation', 'storage-nvme-idle-resume']],
  ['firmware-request', 'Find a missing firmware payload', 'Fehlende Firmware-Nutzlast finden',
    'Does a driver request identify a concrete firmware filename and a loading failure?', 'Benennt eine Treiberanfrage einen konkreten Firmwaredateinamen und Ladefehler?',
    'Does the requested file match the driver/kernel generation and the installed distribution package contents?', 'Passt die angefragte Datei zur Treiber-/Kernelgeneration und zum Inhalt des installierten Distributionspakets?',
    'journalctl -b -k --no-pager', 'modinfo -F firmware MODULE',
    'A correct payload may be absent from early boot even when present on the root filesystem. Verify the requested path and distribution guidance before rebuilding an initramfs or changing packages. Never download a random similarly named binary.',
    'Eine richtige Datei kann beim frühen Start fehlen, obwohl sie im Root-Dateisystem liegt. Prüfe angefragten Pfad und Distributionsanleitung, bevor du Initramfs oder Pakete änderst. Lade niemals eine zufällige ähnlich benannte Binärdatei.',
    'Without a concrete failed request, an old package version or the word firmware in modinfo is insufficient evidence of a missing payload.',
    'Ohne konkrete fehlgeschlagene Anfrage reichen eine alte Paketversion oder das Wort firmware in modinfo nicht als Nachweis einer fehlenden Datei.',
    ['amdgpu-missing-firmware', 'network-wifi-firmware-missing', 'boot-root-uuid-missing']],
  ['windows-linux', 'Windows detects it, Linux does not', 'Windows erkennt es, Linux nicht',
    'Is the same physical device absent from Linux PCI/USB enumeration, rather than merely absent from an application?', 'Fehlt dasselbe physische Gerät in der Linux-PCI-/USB-Auflistung, statt nur in einer Anwendung?',
    'Is the comparison from the same bare-metal machine and physical connection, with virtualization and saved power state excluded?', 'Stammt der Vergleich vom selben physischen Rechner und Anschluss, wobei Virtualisierung und gespeicherter Stromzustand ausgeschlossen sind?',
    'lspci -nn', 'lsusb',
    'Compare enumeration before choosing a Linux driver. A guest may not receive a device, and platform power state may differ between boots. Save work before any cold-boot comparison and do not treat one Windows success as proof of the Linux failure cause.',
    'Vergleiche die Auflistung, bevor du einen Linux-Treiber auswählst. Ein Gast bekommt ein Gerät möglicherweise nicht zugewiesen; Plattformzustände können zwischen Starts abweichen. Sichere Arbeit vor einem Kaltstartvergleich. Ein Erfolg unter Windows beweist nicht die Ursache des Linux-Fehlers.',
    'If Linux enumerates the device, identify the bound driver and failed layer. PCI/USB identity, kernel initialization and application support answer different questions.',
    'Listet Linux das Gerät auf, kläre gebundenen Treiber und fehlerhafte Ebene. PCI-/USB-Identität, Kernelinitialisierung und Anwendungsunterstützung beantworten unterschiedliche Fragen.',
    ['network-wifi-firmware-missing', 'qemu-kvm-acceleration-unavailable', 'hybrid-gpu-selection']],
  ['rfkill', 'Hardware or software radio block', 'Funk per Hardware oder Software gesperrt',
    'Does rfkill list show a blocked radio?', 'Zeigt rfkill list eine gesperrte Funkeinheit?',
    'Is Hard blocked reported, rather than only Soft blocked?', 'Wird Hard blocked statt ausschließlich Soft blocked gemeldet?',
    'rfkill list', 'ip -br link',
    'A hard block points to a platform switch or firmware/embedded-controller path and is not removed by a software-unblock command. A soft block is a different state. Record which radio is affected before changing session networking.',
    'Eine harte Sperre verweist auf Plattformschalter oder Firmware-/Embedded-Controller-Weg und verschwindet nicht durch einen Software-Entsperrbefehl. Eine weiche Sperre ist ein anderer Zustand. Erfasse die betroffene Funkeinheit vor Änderungen am Sitzungsnetzwerk.',
    'No rfkill block does not certify connectivity. A recognized adapter can still fail firmware loading, authentication or address configuration.',
    'Keine rfkill-Sperre bescheinigt keine Verbindung. Ein erkannter Adapter kann weiterhin an Firmwareladung, Authentifizierung oder Adresskonfiguration scheitern.',
    ['network-wifi-rfkill', 'network-wifi-authentication', 'network-dhcp-no-lease']],
  ['iommu-initialization', 'IOMMU or PCIe initialization fault', 'IOMMU- oder PCIe-Initialisierungsfehler',
    'Does the kernel report a DMA/IOMMU fault or PCIe AER event with a device requester?', 'Meldet der Kernel einen DMA-/IOMMU-Fehler oder ein PCIe-AER-Ereignis mit Geräte-Anforderer?',
    'Can that requester be mapped to a device and boot-time driver binding in this host or guest?', 'Lässt sich dieser Anforderer einem Gerät und einer Treiberbindung beim Start dieses Hosts oder Gasts zuordnen?',
    'journalctl -b -k --no-pager', 'lspci -nnk',
    'An identified requester narrows the device path but not the cause. Keep IOMMU translation faults separate from physical-link AER categories. Disabling IOMMU globally can change isolation and passthrough behavior; collect a minimal reproducible record first.',
    'Ein zugeordneter Anforderer grenzt den Geräteweg ein, nicht die Ursache. Trenne IOMMU-Übersetzungsfehler von AER-Kategorien des physischen Links. Globales Abschalten der IOMMU verändert Isolation und Passthrough; erfasse zuerst einen kleinen reproduzierbaren Ablauf.',
    'Without such a device-related message, do not infer an IOMMU problem from a general freeze. Read the exact initialization or watchdog evidence instead.',
    'Ohne entsprechende gerätebezogene Meldung lässt ein allgemeiner Freeze keinen IOMMU-Fehler ableiten. Prüfe die genaue Initialisierungs- oder Watchdog-Meldung.',
    ['kernel-iommu-dma-fault', 'kernel-pcie-aer-errors', 'kernel-hard-lockup']],
];

export const workflows = rows.map(([id, en, de, qe, qd, followEn, followDe, firstCommand, secondCommand, yesEn, yesDe, noEn, noDe, problemIds]) => ({
  id, title: tr(en, de), start: 'start', problemIds,
  nodes: {
    start: { question: tr(qe, qd), explanation: tr('Check this observation before selecting a cause. The command is read-only and is never run by this website.', 'Prüfe diesen Befund, bevor du eine Ursache auswählst. Der Befehl liest Daten und wird von der Website niemals ausgeführt.'),
      command: firstCommand, choices: [{ label: tr('Yes, this is in my evidence', 'Ja, das steht in meinen Befunden'), next: 'qualify' }, { label: tr('No, my observation is different', 'Nein, mein Befund ist anders'), next: 'different' }, { label: tr('I have not checked yet', 'Das habe ich noch nicht geprüft'), next: 'collect' }] },
    qualify: { question: tr(followEn, followDe), explanation: tr('Compare the same device, workload and boot. A report from another device is not confirmation.', 'Vergleiche dasselbe Gerät, dieselbe Last und denselben Start. Ein Bericht zu einem anderen Gerät bestätigt diesen Befund nicht.'),
      command: secondCommand, choices: [{ label: tr('Yes, this additional observation matches', 'Ja, dieser zusätzliche Befund passt'), next: 'evidence' }, { label: tr('No, it does not match', 'Nein, er passt nicht'), next: 'uncertain' }, { label: tr('The report is incomplete', 'Der Bericht ist unvollständig'), next: 'collect' }] },
    evidence: { heading: tr('Follow the evidence for this path', 'Diesem Befundweg folgen'), explanation: tr(yesEn, yesDe), problemIds,
      hypothesis: tr('This narrows the investigation; it does not establish a single root cause or a guaranteed fix.', 'Das grenzt die Prüfung ein, bestätigt aber weder eine einzelne Ursache noch eine sichere Lösung.') },
    different: { heading: tr('Use the observation you actually have', 'Den tatsächlich vorhandenen Befund nutzen'), explanation: tr(noEn, noDe), problemIds },
    uncertain: { heading: tr('Keep competing explanations separate', 'Konkurrierende Erklärungen getrennt halten'), explanation: tr('The extra condition is not established. Keep both observations in your local notes and compare the related guides before changing configuration.', 'Die zusätzliche Bedingung ist nicht belegt. Halte beide Befunde in deinen lokalen Notizen fest und vergleiche die passenden Anleitungen vor Konfigurationsänderungen.'), problemIds },
    collect: { heading: tr('Collect a minimal local record', 'Einen kleinen lokalen Befund erfassen'), explanation: tr('Run the displayed read-only checks one at a time. Use the current boot and the affected device. Replace uppercase placeholders manually; logs and reports can contain private identifiers. You may paste a relevant excerpt into the local tools, but nothing is uploaded.', 'Führe die angezeigten lesenden Prüfungen einzeln aus. Verwende den aktuellen Start und das betroffene Gerät. Ersetze Großbuchstaben-Platzhalter von Hand. Logs und Berichte können private Kennungen enthalten. Ein passender Auszug lässt sich in den lokalen Werkzeugen prüfen; nichts wird hochgeladen.'), commands: [firstCommand, secondCommand], problemIds },
  },
}));
