export const STORAGE_KEY='museum-build-your-first-computer-v1';
export const STAGES=[
['Prepare the workbench',['Inspect organized parts','Confirm AC power disconnected','Prepare screw tray and work surface'],'Work unpowered, keep fasteners organized, and consult the board labels. Anti-static precautions reduce risk without replacing careful handling.'],
['Install the CPU',['Release socket retention arm','Open load plate','Align CPU orientation triangle','Lower CPU flat into socket','Close load plate','Lock retention arm'],'The LGA processor must sit flat without force. The socket and heat-spreader triangles identify orientation.'],
['Thermal interface & cooler',['Apply moderate thermal paste','Position mounting bridge','Lower tower cooler evenly','Tighten opposing mounts','Attach cooler fan','Connect CPU fan to CPU_FAN'],'Paste fills microscopic surface imperfections; mounting pressure spreads it. CPU_FAN detection is distinct from a case-fan header.'],
['Install memory',['Open A2 and B2 latches','Align DIMM one notch','Seat DIMM in A2','Align DIMM two notch','Seat DIMM in B2','Confirm dual-channel pair'],'On this board, A2 and B2 are the recommended two-module positions. Both ends must latch fully.'],
['Install M.2 NVMe storage',['Remove M.2 heatsink','Insert drive at an angle','Lower drive to standoff','Secure retention','Replace thermal pad and heatsink'],'M.2 is the form factor; this 2280 device communicates using NVMe over PCI Express.'],
['Prepare the case',['Remove side panel','Verify ATX standoff pattern','Remove incorrect extra standoff','Inspect routing grommets','Confirm rear I/O opening'],'Standoffs belong only beneath mounting holes. An extra standoff can contact the board.'],
['Install power supply',['Inspect bottom filtered intake','Orient PSU fan downward','Slide PSU into compartment','Secure PSU screws','Select ATX, EPS and two PCIe cables','Connect modular PSU ends'],'The modular cable labels matter. EPS CPU and PCIe GPU plugs are keyed differently and are not interchangeable.'],
['Mount the motherboard',['Align integrated rear I/O','Lower board onto standoffs','Place representative screws','Tighten in distributed sequence'],'Alignment comes before tightening. Screws should be secure, not excessively torqued.'],
['Connect case headers',['Connect power switch','Connect reset switch','Connect power LED with polarity','Connect drive LED with polarity','Connect front USB 3','Connect front USB-C','Connect HD_AUDIO','Connect front intake fan','Connect rear exhaust fan'],'Switch contacts have no polarity; LEDs do. Keyed USB/audio plugs match only their headers. Exact front-panel layouts vary—read the manual.'],
['Connect main power',['Route 24-pin through side grommet','Latch 24-pin ATX connector','Route EPS behind tray','Latch 8-pin EPS at board top'],'The 24-pin supplies motherboard rails; EPS supplies the CPU voltage regulators. Never force a similar-looking PCIe plug.'],
['Install graphics card',['Remove two slot covers','Open primary x16 latch','Seat GPU in upper x16 slot','Secure rear bracket','Connect PCIe power plug A','Connect PCIe power plug B'],'The bracket, edge connector, and slot must align together. Both power plugs are required and cables must clear the fans.'],
['Cable management & airflow',['Route bundles behind tray','Secure reusable cable straps','Clear every fan','Verify front-to-rear airflow'],'Good routing protects fans, avoids tension, and leaves a clear intake-to-cooler-to-exhaust path.'],
['Pre-flight inspection',['Run state-derived technician inspection','Connect monitor to graphics card','Attach keyboard','Set PSU switch ready','Confirm no loose screw'],'Inspection derives from the hardware state; it is not a manually ticked promise.'],
['First power-on & POST',['Connect external AC power','Turn on PSU rear switch','Press case power button','Observe CPU, DRAM, VGA, BOOT diagnostics'],'POST validates essential hardware before any operating system loads. A correct system proceeds deterministically.'],
['UEFI firmware setup',['Verify detected CPU','Verify 32 GB in A2/B2','Verify NVMe drive','Verify CPU and case fans','Enable Memory Performance Profile','Select prepared Linux drive first','Save settings and restart'],'Firmware enumerates hardware before drivers initialize. The neutral performance profile represents vendor features commonly called XMP or EXPO.'],
['First Linux boot',['Observe second POST','Select prepared Linux entry','Observe kernel and init sequence','Reach workbench login'],'The bootloader selects Linux; the kernel then initializes devices and starts the user environment.']];
export const CABLE_MATRIX={ATX24:['MB_ATX24'],EPS8:['MB_EPS8'],PCIE:['GPU_PCIE_A','GPU_PCIE_B'],CPU_FAN:['MB_CPU_FAN'],USB3:['MB_USB3'],USBC:['MB_USBC'],AUDIO:['MB_HD_AUDIO'],FAN:['MB_SYS_FAN_FRONT','MB_SYS_FAN_REAR']};
export function validCable(family,target){return (CABLE_MATRIX[family]||[]).includes(target)}
export function freshState(){return{version:1,started:false,currentStage:0,step:0,completedStages:[],history:[],installedComponents:{},cableConnections:{},headerConnections:{},fanConnections:{},inspectionResults:{},firmwareSettings:{profile:false,linuxFirst:false},postStatus:'off',bootStatus:'off',soundEnabled:false,completed:false}}
export function restoreState(raw){try{const s=JSON.parse(raw);if(s.version!==1||!Number.isInteger(s.currentStage)||s.currentStage<0||s.currentStage>=STAGES.length)return freshState();return Object.assign(freshState(),s)}catch{return freshState()}}
export function postDiagnostic(s){if(!s.headerConnections.power)return'POWER_SWITCH_OPEN';if(!s.cableConnections.eps)return'CPU_LED';if(!s.installedComponents.memory)return'DRAM_LED';if(!s.cableConnections.gpu)return'VGA_LED';if(!s.cableConnections.cpuFan)return'CPU_FAN_WARNING';return'PASS'}
let state=typeof localStorage==='undefined'?freshState():restoreState(localStorage.getItem(STORAGE_KEY));let selected=null;
const $=id=>document.getElementById(id);const browser=typeof document!=='undefined';
const partForStage=['screwdriver','cpu','cooler','memory','nvme','case','psu','motherboard','headers','power','gpu','straps','inspection','power-button','firmware','linux'];
const targetForStage=['case','socket','cpu-fan','dimm-a2','m2','case','case','case','front-panel','atx24','pcie-x16','case','case','case','monitor','monitor'];
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function snapshot(){state.history.push(JSON.stringify({...state,history:[]}));if(state.history.length>40)state.history.shift()}
function activate(){if(!state.started)return;const needed=partForStage[state.currentStage];if(selected!==needed){announce('Select the relevant part or instrument before using the highlighted target.',false);return}snapshot();state.step++;announce(STAGES[state.currentStage][1][Math.min(state.step-1,STAGES[state.currentStage][1].length-1)]+' — complete.',true);if(state.step>=STAGES[state.currentStage][1].length)completeStage();save();render()}
function completeStage(){const n=state.currentStage;state.completedStages.push(n);state.step=0;applyMilestone(n);if(n<15)state.currentStage++;else{state.completed=true;state.bootStatus='complete'}selected=null}
function applyMilestone(n){if(n===1)state.installedComponents.cpu=true;if(n===2){state.installedComponents.cooler=true;state.cableConnections.cpuFan=true}if(n===3)state.installedComponents.memory=true;if(n===4)state.installedComponents.nvme=true;if(n===5)state.installedComponents.caseReady=true;if(n===6)state.installedComponents.psu=true;if(n===7)state.installedComponents.motherboard=true;if(n===8){state.headerConnections={power:true,reset:true,powerLed:true,driveLed:true,usb3:true,usbc:true,audio:true};state.fanConnections={front:true,rear:true}}if(n===9){state.cableConnections.atx=true;state.cableConnections.eps=true}if(n===10){state.installedComponents.gpu=true;state.cableConnections.gpu=true}if(n===11)state.installedComponents.routed=true;if(n===12)state.inspectionResults={passed:true,monitor:true,keyboard:true,psuReady:true,noLooseScrew:true};if(n===13)state.postStatus=postDiagnostic(state);if(n===14){state.firmwareSettings={profile:true,linuxFirst:true};state.bootStatus='restarting'}}
function announce(msg,ok){if(!browser)return;const f=$('feedback');f.textContent=msg;f.className='feedback'+(ok?' ok':'')}
function inventory(){return[{id:partForStage[state.currentStage],name:['Workbench tools','Processor','Cooler assembly','Two DDR5 DIMMs','M.2 NVMe SSD','ATX chassis','Modular ATX PSU','Prepared motherboard','Case cable bundle','Power cable set','Dual-slot graphics card','Reusable cable straps','Inspection lamp','Case power controls','UEFI controls','Boot console'][state.currentStage],detail:'Required for current procedure'},{id:'wrong',name:state.currentStage===9?'PCIe GPU cable':'SATA power cable',detail:'Not valid for this connection'}]}
function drawInstalled(){const g=$('installed');let h='';if(state.installedComponents.cpu)h+='<rect class="installed-cpu" x="159" y="170" width="70" height="70"/><path class="marker" d="M159 240h10l-10-10z"/>';if(state.installedComponents.memory)h+='<rect class="installed-dimm" x="297" y="119" width="13" height="158"/><rect class="installed-dimm" x="341" y="119" width="13" height="158"/>';if(state.installedComponents.nvme)h+='<rect fill="#263f37" stroke="#c1a66c" x="137" y="286" width="170" height="17"/><circle fill="#c1a66c" cx="295" cy="294" r="3"/>';if(state.installedComponents.psu)h+='<g transform="translate(500 495)"><rect class="installed-psu" width="180" height="65"/><circle cx="45" cy="32" r="25" fill="#111" stroke="#777"/><text x="80" y="28" fill="#bbb">750 W MODULAR</text><text x="80" y="44" fill="#bbb">ATX POWER</text></g>';if(state.installedComponents.gpu)h+='<g transform="translate(485 345)"><rect class="installed-gpu" width="270" height="92" rx="5"/><circle class="installed-gpu-fan" cx="90" cy="46" r="32"/><circle class="installed-gpu-fan" cx="190" cy="46" r="32"/><rect fill="#bbb" x="-12" y="4" width="12" height="84"/><path stroke="#c6a65e" stroke-width="6" d="M30 94h190"/></g>';g.innerHTML=h;const c=$('cables');c.innerHTML=state.cableConnections.atx?'<path d="M675 525C790 475 805 340 777 250C750 220 500 255 390 210"/><path class="inner" d="M675 525C790 475 805 340 777 250C750 220 500 255 390 210"/>':'';if(state.cableConnections.eps)c.innerHTML+='<path d="M650 525C560 490 540 100 500 92C400 72 180 65 70 62"/><path class="inner" d="M650 525C560 490 540 100 500 92C400 72 180 65 70 62"/>';if(state.cableConnections.gpu)c.innerHTML+='<path d="M620 525C690 490 730 465 705 420"/><path class="inner" d="M620 525C690 490 730 465 705 420"/>'}
function screen(){const el=$('monitor').firstElementChild;el.className='screen';if(state.currentStage<13){el.textContent='DISPLAY / NO SIGNAL';return}if(state.currentStage===13){el.textContent=state.postStatus==='PASS'?'WB-FIRMWARE POST\nCPU ........ PASS\nDRAM 32 GB . PASS\nVGA ......... PASS\nNVMe ........ DETECTED':state.postStatus;return}if(state.currentStage===14){el.classList.add('uefi');el.textContent='WORKBENCH UEFI  01 JAN 2026 10:00\nCPU: 8-core processor   36°C\nMemory: 32768 MB · A2/B2\nNVMe: 1 TB PCIe drive\nCPU_FAN 920 RPM · SYS_FAN 680 / 710 RPM\nBoot mode: UEFI · Profile: '+(state.firmwareSettings.profile?'ENABLED':'DISABLED');return}if(state.completed){el.classList.add('linux');el.textContent='workbench login: museum\n\nWelcome to the completed system.\nCPU: detected\nMemory: dual-channel\nStorage: NVMe\nGraphics: PCI Express\nCooling: operational\n\nThe first boot is complete.'}else{el.classList.add('linux');el.textContent='Workbench Boot Manager\n> Prepared Linux system\n\nLoading kernel…\nStarting device manager…'}}
function preflight(){if(state.currentStage!==12)return'';const items=['CPU locked','Cooler mounted','CPU_FAN connected','Memory seated in A2/B2','M.2 secured','Motherboard screws installed','No extra standoff','24-pin ATX connected','EPS CPU connected','GPU seated and bracket secured','GPU power connected','Power switch header connected','Case fans connected','Cables clear of fans','Monitor on graphics card','Keyboard attached','No loose screw'];return'<h4>Technician checklist</h4>'+items.map(x=>'<div class="check-item pass">PASS · '+x+'</div>').join('')}
function render(){if(!browser)return;const st=STAGES[state.currentStage];$('stage-count').textContent='STAGE '+String(state.currentStage).padStart(2,'0')+' / 15';$('procedure-title').textContent=st[0];$('objective').textContent=st[1][state.step]||'Procedure complete';$('technical-note').textContent=st[2];$('inventory-list').innerHTML=inventory().map(p=>`<button data-part="${p.id}" class="${selected===p.id?'selected':''}" aria-pressed="${selected===p.id}"><strong>${p.name}</strong><small>${p.detail}</small></button>`).join('');$('action-list').innerHTML=`<button data-activate="1">Place / operate at: ${targetForStage[state.currentStage].replaceAll('-',' ')}</button>`;$('checklist').innerHTML=preflight();$('progress-list').innerHTML=STAGES.map((x,i)=>`<li class="${state.completedStages.includes(i)?'complete':i===state.currentStage?'current':''}">${i}. ${x[0]}</li>`).join('');$('inspect-system').hidden=!state.completed;$('completion').hidden=!state.completed;$('airflow').hidden=!(state.currentStage===11||state.completed);drawInstalled();screen();if(state.completed)renderCompletion()}
function renderCompletion(){const names=['Case','Airflow','Motherboard','Processor and cooling','Memory','Storage','Graphics','Power','Front-panel wiring','Firmware and startup'];$('layers').innerHTML=names.map(n=>`<button data-layer="${n}" aria-pressed="false">${n}</button>`).join('')}
function bind(){document.addEventListener('click',e=>{const part=e.target.closest('[data-part]');if(part){selected=part.dataset.part;announce(selected==='wrong'?'Connector family/keying mismatch. This part cannot be used at the current target.':'Part selected. Operate the highlighted installation point.',selected!=='wrong');render();return}if(e.target.closest('[data-activate]'))activate();const layer=e.target.closest('[data-layer]');if(layer){document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed','false'));layer.setAttribute('aria-pressed','true');$('layer-note').textContent=layer.dataset.layer==='Power'?'Conceptual path: mains → PSU → motherboard, CPU, and graphics. The case switch signals standby logic on the board; it does not carry full system load.':layer.dataset.layer==='Storage'?'Conceptual path: M.2 edge connector → PCIe/NVMe controller → firmware detection → bootloader → operating system.':'Focused inspection of '+layer.dataset.layer.toLowerCase()+'. Unrelated assemblies are visually secondary.'}const fault=e.target.closest('[data-fault]');if(fault){$('fault-note').textContent={power:'Power-switch plug removed: the button produces no board signal. Re-seat it on the manual-defined pins; completed machine restored.',dram:'One DIMM is lifted: fans run but DRAM LED stays active. Press both ends until the latches engage; completed machine restored.',video:'GPU power removed: VGA diagnosis and no image. Restore both keyed PCIe plugs and use the card output; completed machine restored.'}[fault.dataset.fault]}});$('start').onclick=()=>{state.started=true;save();$('workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});announce('Workbench prepared. Select the required item, then operate its target.',true);render()};$('undo').onclick=()=>{if(!state.history.length)return announce('No operation is available to undo.',false);state=restoreState(state.history.pop());save();render();announce('Last valid operation reversed.',true)};$('reset-stage').onclick=()=>{if(!confirm('Reset only the current procedure?'))return;state.step=0;selected=null;save();render();announce('Current procedure reset.',true)};$('reset-all').onclick=()=>{if(!confirm('Reset the complete exhibit and erase saved progress?'))return;state=freshState();save();render();announce('Exhibit returned to a clean workbench.',true)};$('sound').onclick=()=>{state.soundEnabled=!state.soundEnabled;$('sound').textContent='Sound: '+(state.soundEnabled?'on':'off');$('sound').setAttribute('aria-pressed',String(state.soundEnabled));save()};$('zoom').onclick=()=>{const on=$('machine').classList.toggle('zoomed');$('zoom').setAttribute('aria-pressed',String(on))};$('inspect-system').onclick=()=>{$('completion').scrollIntoView()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('machine').classList.remove('zoomed');$('zoom').setAttribute('aria-pressed','false')}})}
if(browser){bind();render()}
