(function () {
  const { VirtualSystem, Shell } = window.LinuxAcademy;
  const $ = selector => document.querySelector(selector); const output = $('#terminalOutput'), input = $('#terminalInput'), prompt = $('#prompt'), tree = $('#tree'), context = $('#context'), mission = $('#missionList'), guidance = $('#guidance'), announcer = $('#announcer');
  const labCommands = ['pwd', 'ls', 'cd', 'cat', 'mkdir', 'touch', 'cp', 'mv', 'rm', 'clear', 'help', 'man'];
  let system, shell, history, historyIndex, progress, hintLevel;
  const write = lines => { const block = document.createElement('pre'); block.className = 'terminal-text'; block.textContent = lines.join('\n'); output.append(block); };
  const promptText = () => `museum@linux:${system.cwd === system.homeDirectory ? '~' : system.cwd}$`;
  function renderTree() { tree.replaceChildren(); const visit = (node, path, depth) => { const line = document.createElement('div'); line.style.paddingLeft = `${depth * 1.05}em`; if (node.type === 'directory') { const button = document.createElement('button'); button.type = 'button'; button.textContent = path === '/' ? '/' : `├── ${path.split('/').pop()}`; button.dataset.path = path; if (path === system.cwd) { button.className = 'current'; button.setAttribute('aria-current', 'location'); } line.append(button); } else line.textContent = `├── ${path.split('/').pop()}`; tree.append(line); if (node.type === 'directory') Object.keys(node.children).sort((a, b) => a.localeCompare(b)).forEach(name => visit(node.children[name], path === '/' ? `/${name}` : `${path}/${name}`, depth + 1)); }; visit(system.fileSystem.root, '/', 0); context.textContent = `${system.cwd} — live state in the fictional Academy filesystem.`; }
  function finalState() { const fs = system.fileSystem; const ideas = fs.resolve('/home/museum/Projects/playground/ideas.txt', system.cwd, system.homeDirectory); const backup = fs.resolve('/home/museum/Projects/playground/backup.txt', system.cwd, system.homeDirectory); return ideas && ideas.node.type === 'file' && !backup; }
  function render() { prompt.textContent = promptText(); const labels = [['projects', 'ENTER PROJECTS'], ['playground', 'CREATE playground/'], ['inside', 'ENTER playground/'], ['notes', 'CREATE notes.txt'], ['backup', 'COPY → backup.txt'], ['ideas', 'RENAME → ideas.txt'], ['removed', 'REMOVE backup.txt'], ['verified', 'VERIFY FINAL DIRECTORY']]; mission.innerHTML = labels.map(([key, label]) => `<li class="${progress[key] ? 'complete' : ''}">[${progress[key] ? 'X' : ' '}] ${label}</li>`).join(''); const done = labels.every(([key]) => progress[key]); $('#completion').hidden = !done; const instructions = [
      'MISSION 1: ENTER THE PROJECTS DIRECTORY.\nTRY: cd Projects', 'MISSION 2: CREATE A DIRECTORY NAMED playground.\nTRY: mkdir playground', 'MISSION 3: ENTER playground.\nTRY: cd playground', 'MISSION 4: CREATE notes.txt.\nTRY: touch notes.txt', 'MISSION 5: COPY notes.txt TO backup.txt.\nTRY: cp notes.txt backup.txt', 'MISSION 6: RENAME notes.txt TO ideas.txt.\nTRY: mv notes.txt ideas.txt', 'MISSION 7: REMOVE backup.txt.\nTRY: rm backup.txt', 'MISSION 8: VERIFY THE RESULT.\nTRY: ls'];
    const next = labels.findIndex(([key]) => !progress[key]); guidance.textContent = next < 0 ? 'Explore safely: pwd · ls · cd .. · cat README.txt' : instructions[next]; renderTree(); }
  function updateProgress(result) { if (!result.success) return; const fs = system.fileSystem; const playground = fs.resolve('/home/museum/Projects/playground', system.cwd, system.homeDirectory); const notes = fs.resolve('/home/museum/Projects/playground/notes.txt', system.cwd, system.homeDirectory); const backup = fs.resolve('/home/museum/Projects/playground/backup.txt', system.cwd, system.homeDirectory); const ideas = fs.resolve('/home/museum/Projects/playground/ideas.txt', system.cwd, system.homeDirectory);
    if (system.cwd === '/home/museum/Projects') progress.projects = true;
    if (progress.projects && playground && playground.node.type === 'directory') progress.playground = true;
    if (progress.playground && system.cwd === '/home/museum/Projects/playground') progress.inside = true;
    if (progress.inside && notes && notes.node.type === 'file') progress.notes = true;
    if (progress.notes && backup && backup.node.type === 'file') progress.backup = true;
    if (progress.backup && ideas && ideas.node.type === 'file' && !notes) progress.ideas = true;
    if (progress.ideas && !backup && ideas) progress.removed = true;
    if (progress.removed && result.command === 'ls' && finalState() && system.cwd === '/home/museum/Projects/playground') progress.verified = true;
  }
  function welcome() { write(['LINUX TERMINAL ACADEMY', 'LAB 03 — FILES & DIRECTORIES', '', 'MISSION: BUILD AND CLEAN UP A SMALL PROJECT WORKSPACE.', 'Everything changes only in browser memory. RESET LAB restores the original fictional system.', '', 'You start in /home/museum.', 'Try: cd Projects']); }
  function reset() { system = new VirtualSystem(); shell = new Shell(system, { allowedCommands: labCommands }); history = []; historyIndex = 0; hintLevel = 0; progress = { projects: false, playground: false, inside: false, notes: false, backup: false, ideas: false, removed: false, verified: false }; output.replaceChildren(); welcome(); render(); input.value = ''; input.focus(); announcer.textContent = 'Lab reset. The fictional filesystem is restored.'; }
  function run(raw) { const value = raw.trim(); if (!value) return; write([`${promptText()} ${value}`]); history.push(value); historyIndex = history.length; const result = shell.execute(value); if (result.clear) output.replaceChildren(); else if (result.output.length) write(result.output); updateProgress(result); render(); input.value = ''; input.focus(); announcer.textContent = result.success ? `${result.command} completed. Current directory: ${system.cwd}.` : result.output.join(' '); }
  input.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); run(input.value); } if (event.key === 'ArrowUp') { event.preventDefault(); if (history.length) { historyIndex = Math.max(0, historyIndex - 1); input.value = history[historyIndex]; } } if (event.key === 'ArrowDown') { event.preventDefault(); historyIndex = Math.min(history.length, historyIndex + 1); input.value = history[historyIndex] || ''; } }); document.addEventListener('keydown', event => { if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); run('clear'); } }); $('#terminal').addEventListener('click', () => input.focus()); document.querySelectorAll('[data-command]').forEach(button => button.addEventListener('click', () => run(button.dataset.command))); tree.addEventListener('click', event => { const button = event.target.closest('button[data-path]'); if (button) run(`cd ${button.dataset.path}`); }); $('#hintButton').addEventListener('click', () => { const next = Object.keys(progress).find(key => !progress[key]); const hints = { projects: ['Use the command that changes directory.', 'The command is cd.', 'Try: cd Projects'], playground: ['You need a command that makes a directory.', 'The command is mkdir.', 'Try: mkdir playground'], inside: ['Change into the directory you just made.', 'Use cd followed by its name.', 'Try: cd playground'], notes: ['Create an empty file.', 'The command is touch.', 'Try: touch notes.txt'], backup: ['Duplicate the file into a new name.', 'The command is cp SOURCE DESTINATION.', 'Try: cp notes.txt backup.txt'], ideas: ['Rename the original file.', 'The command is mv SOURCE DESTINATION.', 'Try: mv notes.txt ideas.txt'], removed: ['Remove only the duplicate file.', 'The command is rm.', 'Try: rm backup.txt'], verified: ['List the directory to verify its contents.', 'The command is ls.', 'Try: ls'] }; announcer.textContent = (hints[next] || ['Mission complete.'])[Math.min(hintLevel++, 2)]; }); $('#resetButton').addEventListener('click', reset); reset();
})();
