(function () {
  const { VirtualSystem, Shell, commandProfiles } = window.LinuxAcademy;
  const $ = selector => document.querySelector(selector), output = $('#terminalOutput'), input = $('#terminalInput'), prompt = $('#prompt'), mission = $('#missionList'), guidance = $('#guidance'), announcer = $('#announcer'), decoder = $('#decoder');
  let system, shell, history, historyIndex, progress, hintLevel;
  const labPath = '/home/museum/Projects/permissions-lab';
  const write = lines => { const block = document.createElement('pre'); block.className = 'terminal-text'; block.textContent = lines.join('\n'); output.append(block); };
  const promptText = () => `museum@linux:${system.cwd === system.homeDirectory ? '~' : system.cwd}$`;
  function renderDecoder() { const selected = system.fileSystem.resolve(system.cwd === labPath ? 'notes.txt' : `${labPath}/notes.txt`, system.cwd, system.homeDirectory); const n = selected.node; decoder.textContent = `-${n.mode}\n\nOWNER   ${n.mode.slice(0, 3)}  ${n.mode.slice(0, 3).replace(/-/g, '') || 'no access'}\nGROUP   ${n.mode.slice(3, 6)}  ${n.mode.slice(3, 6).replace(/-/g, '') || 'no access'}\nOTHERS  ${n.mode.slice(6, 9)}  ${n.mode.slice(6, 9).replace(/-/g, '') || 'no access'}\n\nu = owner · g = group · o = others\nr = read · w = write · x = execute`; }
  function render() { prompt.textContent = promptText(); const labels = [['entered', 'ENTER permissions-lab/'], ['listed', 'INSPECT WITH ls -l'], ['public', 'READ public.txt'], ['private', 'DISCOVER PRIVATE DENIAL'], ['owner', 'INSPECT IDENTITY / OWNER'], ['execute', 'ADD OWNER EXECUTE TO script.sh'], ['verified', 'VERIFY CHANGED MODE'], ['notesDenied', 'DISCOVER notes.txt DENIAL'], ['repaired', 'REPAIR ONLY OWNER READ'], ['readNotes', 'READ REPAIRED notes.txt']]; mission.innerHTML = labels.map(([k, label]) => `<li class="${progress[k] ? 'complete' : ''}">[${progress[k] ? 'X' : ' '}] ${label}</li>`).join(''); $('#completion').hidden = !labels.every(([k]) => progress[k]); const next = labels.find(([k]) => !progress[k]); guidance.textContent = next ? `MISSION: ${next[1]}\n${next[0] === 'entered' ? 'TRY: cd Projects/permissions-lab' : next[0] === 'listed' ? 'TRY: ls -l' : next[0] === 'public' ? 'TRY: cat public.txt' : next[0] === 'private' ? 'TRY: cat private.txt' : next[0] === 'owner' ? 'TRY: id or ls -l' : next[0] === 'execute' ? 'TRY: chmod u+x script.sh' : next[0] === 'verified' ? 'TRY: ls -l' : next[0] === 'notesDenied' ? 'TRY: cat notes.txt' : next[0] === 'repaired' ? 'TRY: chmod u+r notes.txt' : 'TRY: cat notes.txt'}` : 'Mission complete. Practice reading modes; avoid broad permission changes.'; $('#context').textContent = `${system.cwd} — live metadata in fictional browser memory.`; renderDecoder(); }
  function update(result) { const fs = system.fileSystem, notes = fs.resolve(`${labPath}/notes.txt`, system.cwd, system.homeDirectory), script = fs.resolve(`${labPath}/script.sh`, system.cwd, system.homeDirectory); if (system.cwd === labPath) progress.entered = true; if (progress.entered && result.command === 'ls' && result.input.args[0] === '-l' && result.success) progress.listed = true; if (progress.listed && result.command === 'cat' && result.input.args[0] === 'public.txt' && result.success) progress.public = true; if (progress.public && result.command === 'cat' && result.input.args[0] === 'private.txt' && !result.success && /Permission denied/.test(result.output.join('\n'))) progress.private = true; if (progress.private && (result.command === 'id' || (result.command === 'ls' && result.input.args[0] === '-l')) && result.success) progress.owner = true; if (progress.owner && script.node.mode[2] === 'x') progress.execute = true; if (progress.execute && result.command === 'ls' && result.input.args[0] === '-l' && result.success) progress.verified = true; if (progress.verified && result.command === 'cat' && result.input.args[0] === 'notes.txt' && !result.success && /Permission denied/.test(result.output.join('\n'))) progress.notesDenied = true; if (progress.notesDenied && notes.node.mode[0] === 'r') progress.repaired = true; if (progress.repaired && result.command === 'cat' && result.input.args[0] === 'notes.txt' && result.success) progress.readNotes = true; }
  function run(raw) { const result = shell.execute(raw); write([`${promptText()} ${raw}`, ...result.output]); if (result.clear) output.replaceChildren(); if (raw.trim()) { history.push(raw); historyIndex = history.length; } update(result); render(); announcer.textContent = result.success ? 'Command completed.' : result.output.join(' '); input.value = ''; input.focus(); }
  function reset() { system = new VirtualSystem(); shell = new Shell(system, { allowedCommands: commandProfiles.lab04 }); history = []; historyIndex = 0; progress = {}; hintLevel = 0; output.replaceChildren(); write(['LINUX TERMINAL ACADEMY', 'LAB 04 — PERMISSIONS & USERS', '', 'MISSION: Inspect a real fictional permission problem, then make the smallest safe repair.', 'Everything here exists only in browser memory.']); render(); input.focus(); }
  input.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); run(input.value); } if (event.key === 'ArrowUp') { event.preventDefault(); if (history.length) input.value = history[Math.max(0, --historyIndex)]; } if (event.key === 'ArrowDown') { event.preventDefault(); input.value = historyIndex < history.length - 1 ? history[++historyIndex] : (historyIndex = history.length, ''); } if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); run('clear'); } });
  document.querySelectorAll('[data-command]').forEach(button => button.addEventListener('click', () => run(button.dataset.command)));
  $('#resetButton').addEventListener('click', reset); $('#hintButton').addEventListener('click', () => { hintLevel++; write([hintLevel === 1 ? 'Start with: cd Projects/permissions-lab then ls -l' : hintLevel === 2 ? 'private.txt belongs to root. Do not try to bypass it.' : 'notes.txt belongs to museum but lacks owner read: chmod u+r notes.txt']); input.focus(); }); reset();
})();
