(function(root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (root) root.NebuStrikeAudio = api;
})(typeof window !== 'undefined' ? window : globalThis, function() {
  'use strict';
  const BPM = 124, STEP = 60 / BPM / 4;
  // 52 bars / ~101 seconds. These are deliberate, original note and rhythm data, never random selection.
  const COMPOSITION = Object.freeze({
    sections: Object.freeze([['INTRO',4],['A',8],['B',8],['C',8],['BREAKDOWN',4],['D',8],['E',8],['RETURN',4]]),
    bass: Object.freeze([[38,38,45,38],[38,41,45,41],[36,36,43,36],[33,36,40,36],[38,45,41,38],[31,38,43,38],[36,43,40,36],[33,40,45,40]]),
    lead: Object.freeze([[null,null,69,72,74,null,72,69],[null,67,69,72,null,74,72,69],[65,69,72,null,74,76,74,null],[69,72,74,77,74,72,69,null],[67,null,69,72,74,72,69,67],[64,67,71,null,72,74,71,67],[69,72,null,74,76,74,72,69],[65,69,72,74,null,72,69,67]]),
    chords: Object.freeze([[50,53,57],[50,53,57],[48,52,55],[45,48,52],[50,53,57],[43,47,50],[48,52,55],[45,48,52]])
  });
  const hz = midi => 440 * Math.pow(2, (midi - 69) / 12);
  function finiteComposition() { return Object.values(COMPOSITION).every(value => Array.isArray(value) ? value.flat(Infinity).every(note => note === null || typeof note === 'string' || Number.isFinite(note)) : true); }
  function createAudio({ window: win = globalThis, storage = win.localStorage } = {}) {
    let context = null, master, music, sfxBus, compressor, scheduler = null, stepIndex = 0, musicOn = true, sfxOn = true, masterVolume = .76;
    const active = new Set(), metrics = { contexts: 0, schedulersStarted: 0, schedulersStopped: 0 };
    try { musicOn = storage?.getItem('nebu.music') !== '0'; sfxOn = storage?.getItem('nebu.sfx') !== '0'; masterVolume = Math.max(.4, Math.min(1, Number(storage?.getItem('nebu.master')) || .76)); } catch (_) {}
    function ensure() { if (context) return context; const Ctor = win.AudioContext || win.webkitAudioContext; if (!Ctor) return null; context = new Ctor(); metrics.contexts++; master = context.createGain(); music = context.createGain(); sfxBus = context.createGain(); compressor = context.createDynamicsCompressor(); master.gain.value = masterVolume; music.gain.value = musicOn ? .62 : 0; sfxBus.gain.value = sfxOn ? .84 : 0; compressor.threshold.value = -18; compressor.knee.value = 16; compressor.ratio.value = 8; compressor.attack.value = .004; compressor.release.value = .16; music.connect(master); sfxBus.connect(master); master.connect(compressor); compressor.connect(context.destination); return context; }
    function tone(bus, frequency, duration, gain, type = 'square', when = 0, endFrequency) { const c = ensure(); if (!c || !bus) return; const t = c.currentTime + when, o = c.createOscillator(), g = c.createGain(); o.type = type; o.frequency.setValueAtTime(frequency, t); if (endFrequency) o.frequency.exponentialRampToValueAtTime(Math.max(20, endFrequency), t + duration); g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(Math.max(.0001, gain), t + .006); g.gain.exponentialRampToValueAtTime(.0001, t + duration); o.connect(g); g.connect(bus); o.start(t); o.stop(t + duration + .02); active.add(o); o.onended = () => active.delete(o); }
    function noise(bus, duration, gain, when = 0, lowpass = 1800) { const c = ensure(); if (!c || !bus) return; const b = c.createBuffer(1, Math.ceil(c.sampleRate * duration), c.sampleRate), d = b.getChannelData(0); for (let i=0;i<d.length;i++) d[i] = Math.random()*2-1; const n=c.createBufferSource(), f=c.createBiquadFilter(), g=c.createGain(), t=c.currentTime+when; f.type='lowpass'; f.frequency.value=lowpass; g.gain.setValueAtTime(gain,t); g.gain.exponentialRampToValueAtTime(.0001,t+duration); n.buffer=b;n.connect(f);f.connect(g);g.connect(bus);n.start(t);n.stop(t+duration+.02); }
    function sfx(name, value = 0) { if (!sfxOn) return; const jitter = .96 + Math.random() * .08; if (name === 'fire') { tone(sfxBus, 180*jitter,.07,.16,'square',0,65); tone(sfxBus, 105,.12,.12,'triangle',0); noise(sfxBus,.035,.07,0,2800); tone(sfxBus, 620*jitter,.08,.055,'sawtooth',.008,220); } else if(name === 'hit') { noise(sfxBus,.06,.10,0,2400); tone(sfxBus,950*jitter,.045,.055,'triangle',.01,620); tone(sfxBus,2500,.025,.025,'square',.02); } else if(name === 'destroy') { const large=value==='large', medium=value==='medium'; tone(sfxBus,large?72:medium?105:165,large?.36:.18,large?.22:.14,'triangle',0,large?38:75); noise(sfxBus,large?.28:.13,large?.14:.08,0,large?1400:2300); if(large) tone(sfxBus,1800,.12,.045,'square',.09,1000); } else if(name === 'base') { tone(sfxBus,58,.5,.28,'sine',0,28); noise(sfxBus,.32,.16,0,700); tone(sfxBus,420,.12,.07,'square',.25,260); } else if(name === 'wave') [165,165,165,330].forEach((f,i)=>tone(sfxBus,f,.12,.09,'square',i*.15,f*(i===3?1.8:.8))); else if(name === 'clear') [523,659,784,1047].forEach((f,i)=>tone(sfxBus,f,.22,.07,'triangle',i*.16)); else if(name === 'combo') tone(sfxBus,420 + Math.min(4,value)*105,.09,.045,'square'); else if(name === 'warning') tone(sfxBus,220,.12,.07,'square',0,180); else if(name === 'gameover') [330,262,196,131].forEach((f,i)=>tone(sfxBus,f,.34,.10,'triangle',i*.22,f*.82)); }
    function musicTick() { if (!musicOn || !context) return; const bar = Math.floor(stepIndex / 16), within = stepIndex % 16, phrase = bar % 8, sectionBar = bar % 52, intensity = api.intensity || 1; const b = COMPOSITION.bass[phrase][Math.floor(within / 4)]; tone(music,hz(b),STEP*.82,.075,'triangle'); tone(music,hz(b+12),STEP*.45,.025,'square'); if (sectionBar >= 12 || intensity >= 3) tone(music,hz(COMPOSITION.chords[phrase][within%3]+12),STEP*.3,.024,'square'); if ((sectionBar >= 12 || intensity >=2) && within%2===0) { const note=COMPOSITION.lead[phrase][within/2]; if(note) tone(music,hz(note),STEP*1.55,.07,'sawtooth'); } if (within===0) tone(music,72, .08,.14,'sine'); if (within===4 || within===12) noise(music,.07,.035,0,2000); if (sectionBar >= 28 && within === 0) COMPOSITION.chords[phrase].forEach(n=>tone(music,hz(n),STEP*12,.015,'sine')); stepIndex=(stepIndex+1)%(52*16); }
    const api = { intensity: 1, start() { const c=ensure(); if(!c) return false; c.resume?.(); if(!musicOn || scheduler) return true; scheduler=win.setInterval(musicTick, STEP*1000); metrics.schedulersStarted++; musicTick(); return true; }, stopMusic() { if(scheduler !== null){win.clearInterval(scheduler);scheduler=null;metrics.schedulersStopped++;} }, stop() { api.stopMusic(); active.forEach(o=>{try{o.stop();}catch(_){}}); active.clear(); }, setMusic(on) { musicOn=!!on; try{storage?.setItem('nebu.music',musicOn?'1':'0');}catch(_){} if(music) music.gain.value=musicOn?.62:0; if(musicOn) api.start(); else api.stopMusic(); }, setSfx(on) { sfxOn=!!on; try{storage?.setItem('nebu.sfx',sfxOn?'1':'0');}catch(_){} if(sfx) sfxBus.gain.value=sfxOn?.84:0; }, setMaster(value) { masterVolume=Math.max(0,Math.min(1,Number(value)||0)); try{storage?.setItem('nebu.master',String(masterVolume));}catch(_){} if(master)master.gain.value=masterVolume; }, sfx, getState:()=>({contextCount:metrics.contexts,schedulerActive:scheduler!==null,schedulersStarted:metrics.schedulersStarted,schedulersStopped:metrics.schedulersStopped,musicOn,sfxOn,masterVolume,compositionBars:52,compositionFinite:finiteComposition()}) };
    return api;
  }
  return { BPM, COMPOSITION, finiteComposition, createAudio };
});
