(function(root, factory) { const api = factory(); if (typeof module !== 'undefined' && module.exports) module.exports = api; if (root) root.NebuStrikeView = api; })(typeof window !== 'undefined' ? window : globalThis, function() {
  'use strict'; const Lifecycle = Object.freeze({ UNINITIALIZED:'UNINITIALIZED', INITIALIZING:'INITIALIZING', RUNNING:'RUNNING', STOPPED:'STOPPED' });
  function createGameView({ window: win, document: doc, Core }) { let lifecycle=Lifecycle.UNINITIALIZED, game, canvas, ctx, screen, rafId=null, last=0, keys={}, attached=false, audio=null, musicTimer=null, musicRunning=false, musicEnabled=true, sfxEnabled=true, stars=[]; const counts={launchCount:0,gameInitCount:0,rafStartCount:0,resizeCount:0,renderCount:0}, musicCounts={start:0,stop:0};
    function audioBus() { if (audio) return audio; const A=win.AudioContext||win.webkitAudioContext; if (!A) return null; audio=new A(); const master=audio.createGain(), music=audio.createGain(), sfx=audio.createGain(), compressor=audio.createDynamicsCompressor(); master.gain.value=.72; music.gain.value=.24; sfx.gain.value=.72; music.connect(master);sfx.connect(master);master.connect(compressor);compressor.connect(audio.destination); audio._music=music;audio._sfx=sfx; return audio; }
    function tone(freq,duration,type='square',gain=.12,bus='sfx') { const a=audioBus(); if(!a)return; a.resume?.(); const o=a.createOscillator(),g=a.createGain(), now=a.currentTime; o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.55),now+duration);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(a[bus==='music'?'_music':'_sfx']);o.start(now);o.stop(now+duration+.02); }
    function sfx(kind) { if(!sfxEnabled)return; const map={fire:[620,.1,'square',.16],hit:[145,.11,'triangle',.13],destroy:[90,.25,'sawtooth',.17],wave:[760,.22,'square',.13],impact:[55,.35,'sawtooth',.22],over:[260,.5,'triangle',.18]}; const v=map[kind];if(v)tone(...v); }
    // Original 124 BPM, 28-bar sequenced loop: bass, arpeggio, lead and percussion.
    function startMusic() { if(!musicEnabled||musicRunning)return; if(!audioBus())return; musicRunning=true;musicCounts.start++;const bass=[48,null,48,51,48,null,55,51], arp=[72,75,79,75,74,77,81,77], lead=[null,null,79,null,82,null,79,84,null,82,79,null,75,null,77,79]; let step=0; musicTimer=win.setInterval(()=>{if(!musicRunning)return; const i=step++%32; if(bass[i%8])tone(440*Math.pow(2,(bass[i%8]-69)/12),.17,'square',.075,'music'); tone(440*Math.pow(2,(arp[i%8]-69)/12),.09,'triangle',.045,'music'); if(lead[i%16])tone(440*Math.pow(2,(lead[i%16]-69)/12),.2,'sawtooth',.055,'music'); if(i%4===0)tone(70,.07,'square',.045,'music');}, 60000/124/2); }
    function stopMusic(){if(musicTimer!==null){win.clearInterval(musicTimer);musicTimer=null;}if(musicRunning)musicCounts.stop++;musicRunning=false;}
    function resize(){if(!canvas||!game)return;counts.resizeCount++;const r=screen.getBoundingClientRect(),d=Math.min(win.devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(d,0,0,d,0,0);game.width=r.width;game.height=r.height;stars=Array.from({length:100},(_,i)=>({x:(i*97.31)%r.width,y:(i*53.17)%r.height*.84,a:.2+(i%5)*.12}));}
    function asteroid(a){ctx.beginPath();a.shape.forEach(([x,y],i)=>{const c=Math.cos(a.angle),s=Math.sin(a.angle),X=a.x+x*c-y*s;i?ctx.lineTo(X,Y):ctx.moveTo(X,Y);});ctx.closePath();}
    function drawTurret(){const t=game.turret;ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#152b37';ctx.beginPath();ctx.ellipse(0,18,58,17,0,0,7);ctx.fill();ctx.strokeStyle='#69e7ff';ctx.lineWidth=2;ctx.stroke();ctx.rotate(t.angle);ctx.fillStyle='#203e4b';ctx.fillRect(-5,-12-t.recoil*8,48,24);ctx.fillStyle=t.heat>.4?'#ffbd68':'#70eaff';ctx.fillRect(35,-5-t.recoil*8,20,10);ctx.restore();}
    function draw(){counts.renderCount++;const w=game.width,h=game.height;ctx.fillStyle='#020710';ctx.fillRect(0,0,w,h);const n=ctx.createRadialGradient(w*.72,h*.18,0,w*.72,h*.18,w*.7);n.addColorStop(0,'#19385b88');n.addColorStop(1,'#02071000');ctx.fillStyle=n;ctx.fillRect(0,0,w,h);for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle='#bceeff';ctx.fillRect(s.x,s.y,1,1);}ctx.globalAlpha=1;ctx.save();ctx.translate((Math.random()-.5)*game.shake*10,(Math.random()-.5)*game.shake*10);ctx.strokeStyle='#9eeaff';ctx.lineWidth=2;for(const a of game.enemies){asteroid(a);ctx.stroke();}for(const p of game.shots){ctx.strokeStyle='#ffe99a';ctx.beginPath();ctx.moveTo(p.px,p.py);ctx.lineTo(p.x,p.y);ctx.stroke();}for(const p of game.particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);}ctx.globalAlpha=1;ctx.fillStyle='#0a1820';ctx.beginPath();ctx.arc(w/2,h+220,w*.75,Math.PI,0);ctx.fill();ctx.strokeStyle='#3d9aab';ctx.stroke();drawTurret();ctx.restore();if(game.flash){ctx.fillStyle=`rgba(255,100,80,${game.flash*.25})`;ctx.fillRect(0,0,w,h);}hud();}
    function hud(){ctx.fillStyle='#c7eef2';ctx.font='600 12px ui-monospace,monospace';ctx.fillText(`SCORE ${String(game.score).padStart(6,'0')}`,24,30);ctx.fillText(`WAVE ${String(game.wave).padStart(2,'0')}`,24,50);ctx.fillText(`BASE ${'█'.repeat(game.base)}${'░'.repeat(Core.BASE_HEALTH-game.base)}`,24,70);ctx.textAlign='right';ctx.fillText(`COMBO x${game.combo}`,game.width-24,30);ctx.textAlign='center';if(game.state==='TITLE'||game.state==='COUNTDOWN'||game.state==='GAMEOVER'){const lost=game.state==='GAMEOVER';ctx.fillStyle='#e8fbff';ctx.font=`700 ${Math.min(70,game.width*.075)}px ui-monospace,monospace`;ctx.fillText(lost?'OUTPOST LOST':'NEBU STRIKE',game.width/2,game.height*.35);ctx.fillStyle='#8be8fb';ctx.font='15px ui-monospace,monospace';ctx.fillText(lost?`SCORE ${game.score} · WAVE ${game.wave} · ENTER TO RESTART`:'DEEP SPACE DEFENSE',game.width/2,game.height*.41);ctx.fillStyle='#ffd88e';ctx.fillText(game.state==='COUNTDOWN'?`SYSTEM ONLINE · INCOMING ${Math.ceil(game.countdown)}`:'PLANETARY DEFENSE SYSTEM ONLINE · ENTER / CLICK TO START',game.width/2,game.height*.49);if(game.state==='TITLE')ctx.fillText('MOUSE AIM · CLICK FIRE · A / D AIM · SPACE FIRE',game.width/2,game.height*.55);ctx.textAlign='left';}}
    function frame(now){rafId=null;if(lifecycle!==Lifecycle.RUNNING)return;const old=game.state,score=game.score,shot=game.shots.length;Core.update(game,keys,Math.min(.05,(now-last)/1000||0));last=now;if(game.shots.length>shot)sfx('fire');if(game.score>score)sfx('destroy');if(old==='COUNTDOWN'&&game.state==='PLAYING')sfx('wave');if(old!=='GAMEOVER'&&game.state==='GAMEOVER'){sfx('over');stopMusic();}draw();request();} function request(){if(lifecycle===Lifecycle.RUNNING&&rafId===null)rafId=win.requestAnimationFrame(frame);}
    function begin(){if(game&&(game.state==='TITLE'||game.state==='GAMEOVER')){Core.start(game);startMusic();sfx('wave');}} const pointer=e=>{const p=e.touches?.[0]||e;const r=canvas.getBoundingClientRect();keys.aimX=p.clientX-r.left;keys.aimY=p.clientY-r.top;};const down=e=>{pointer(e);keys.fire=true;begin();};const up=()=>keys.fire=false;
    const keydown=e=>{if(['ArrowLeft','ArrowRight',' ','a','d','Enter'].includes(e.key))e.preventDefault();if(e.key==='Enter')begin();if(e.key.toLowerCase()==='r'){Core.start(game);startMusic();}keys.left=keys.left||e.key==='ArrowLeft'||e.key.toLowerCase()==='a';keys.right=keys.right||e.key==='ArrowRight'||e.key.toLowerCase()==='d';keys.fire=keys.fire||e.key===' ';};const keyup=e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')keys.left=false;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')keys.right=false;if(e.key===' ')keys.fire=false;};
    const restart=()=>{Core.start(game);startMusic();}, fullscreen=()=>screen.requestFullscreen?.(), musicToggle=()=>{musicEnabled=!musicEnabled;if(!musicEnabled)stopMusic();else if(game?.state==='PLAYING'||game?.state==='COUNTDOWN')startMusic();const b=doc.querySelector('#gameMusic');if(b){b.textContent=`MUSIC ${musicEnabled?'ON':'OFF'}`;b.setAttribute('aria-pressed',musicEnabled);}}, sfxToggle=()=>{sfxEnabled=!sfxEnabled;const b=doc.querySelector('#gameSfx');if(b){b.textContent=`SFX ${sfxEnabled?'ON':'OFF'}`;b.setAttribute('aria-pressed',sfxEnabled);}};
    function attach(){if(attached)return;win.addEventListener('resize',resize);win.addEventListener('keydown',keydown);win.addEventListener('keyup',keyup);canvas.addEventListener('mousemove',pointer);canvas.addEventListener('mousedown',down);canvas.addEventListener('click',begin);win.addEventListener('mouseup',up);canvas.addEventListener('touchstart',down,{passive:true});canvas.addEventListener('touchmove',down,{passive:true});canvas.addEventListener('touchend',up);doc.querySelector('#gameRestart').addEventListener('click',restart);doc.querySelector('#gameFullscreen').addEventListener('click',fullscreen);doc.querySelector('#gameMusic')?.addEventListener('click',musicToggle);doc.querySelector('#gameSfx')?.addEventListener('click',sfxToggle);attached=true;}
    function detach(){if(!attached)return;win.removeEventListener('resize',resize);win.removeEventListener('keydown',keydown);win.removeEventListener('keyup',keyup);canvas.removeEventListener('mousemove',pointer);canvas.removeEventListener('mousedown',down);canvas.removeEventListener('click',begin);win.removeEventListener('mouseup',up);canvas.removeEventListener('touchstart',down);canvas.removeEventListener('touchmove',down);canvas.removeEventListener('touchend',up);doc.querySelector('#gameRestart').removeEventListener('click',restart);doc.querySelector('#gameFullscreen').removeEventListener('click',fullscreen);doc.querySelector('#gameMusic')?.removeEventListener('click',musicToggle);doc.querySelector('#gameSfx')?.removeEventListener('click',sfxToggle);attached=false;}
    function launch(){if(lifecycle===Lifecycle.INITIALIZING||lifecycle===Lifecycle.RUNNING)return false;counts.launchCount++;lifecycle=Lifecycle.INITIALIZING;canvas=doc.querySelector('#gameCanvas');screen=doc.querySelector('#gameScreen');ctx=canvas.getContext('2d');game=Core.createGame();keys={};last=0;attach();resize();lifecycle=Lifecycle.RUNNING;counts.gameInitCount++;counts.rafStartCount++;request();return true;}function stop(){if(lifecycle!==Lifecycle.RUNNING&&lifecycle!==Lifecycle.INITIALIZING)return;lifecycle=Lifecycle.STOPPED;if(rafId!==null)win.cancelAnimationFrame(rafId);rafId=null;stopMusic();detach();}return{launch,stop,destroy:stop,getLifecycle:()=>lifecycle,getCounts:()=>({...counts}),getMusicCounts:()=>({...musicCounts,running:musicRunning}),getGame:()=>game,Lifecycle};
  } return {createGameView,Lifecycle};
});
