(function(root, factory) { const api = factory(); if (typeof module !== 'undefined' && module.exports) module.exports = api; if (root) root.NebuStrikeView = api; })(typeof window !== 'undefined' ? window : globalThis, function() {
  'use strict';
  const Lifecycle=Object.freeze({UNINITIALIZED:'UNINITIALIZED',INITIALIZING:'INITIALIZING',RUNNING:'RUNNING',STOPPED:'STOPPED'});
  function createGameView({window:win,document:doc,Core}) {
    let lifecycle=Lifecycle.UNINITIALIZED,game,canvas,ctx,screen,rafId=null,last=0,keys={},attached=false,audio=null,musicTimer=null,musicRunning=false,musicEnabled=true,sfxEnabled=true,stars=[],terrain=[];
    const counts={launchCount:0,gameInitCount:0,rafStartCount:0,resizeCount:0,renderCount:0},musicCounts={start:0,stop:0};
    function audioBus(){if(audio)return audio;const A=win.AudioContext||win.webkitAudioContext;if(!A)return null;audio=new A();const master=audio.createGain(),music=audio.createGain(),sfx=audio.createGain(),comp=audio.createDynamicsCompressor(); master.gain.value=.92;music.gain.value=.42;sfx.gain.value=.88;comp.threshold.value=-16;comp.knee.value=16;comp.ratio.value=8;comp.attack.value=.003;comp.release.value=.16;music.connect(master);sfx.connect(master);master.connect(comp);comp.connect(audio.destination);audio._music=music;audio._sfx=sfx;return audio;}
    function tone(freq,duration,type='square',gain=.12,bus='sfx',end=.55){const a=audioBus();if(!a)return;a.resume?.();const o=a.createOscillator(),g=a.createGain(),now=a.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(32,freq*end),now+duration);g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(gain,now+.008);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(a[bus==='music'?'_music':'_sfx']);o.start(now);o.stop(now+duration+.03);}
    function noise(duration,gain=.08){const a=audioBus();if(!a||!a.createBuffer)return;const b=a.createBuffer(1,Math.max(1,a.sampleRate*duration),a.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const n=a.createBufferSource(),g=a.createGain(),now=a.currentTime;n.buffer=b;g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);n.connect(g).connect(a._sfx);n.start(now);}
    function sfx(kind){if(!sfxEnabled)return;const r=.92+Math.random()*.16;if(kind==='fire'){tone(980*r,.09,'square',.23,'sfx',.45);tone(230*r,.11,'triangle',.13,'sfx',.7);noise(.045,.055);}else if(kind==='hit'){tone(390*r,.08,'triangle',.14);noise(.055,.045);}else if(kind==='destroy'){tone(110*r,.27,'sawtooth',.25,'sfx',.35);tone(990*r,.12,'triangle',.08);noise(.16,.1);}else if(kind==='impact'){tone(68,.42,'sawtooth',.34,'sfx',.42);tone(120,.15,'square',.1);noise(.2,.12);}else if(kind==='wave'){tone(480,.16,'square',.16,'sfx',1.65);tone(720,.22,'triangle',.16,'sfx',1.3);}else if(kind==='combo'){tone(580*r,.12,'square',.11,'sfx',1.28);}else if(kind==='over'){tone(410,.2,'triangle',.18,'sfx',.7);setTimeout(()=>tone(245,.36,'sawtooth',.22,'sfx',.45),120);}}
    const hz=n=>440*Math.pow(2,(n-69)/12);
    // 40 bars at 124 BPM: intro, A/B/C, breakdown and full variation.
    function startMusic(){if(!musicEnabled||musicRunning||!audioBus())return;musicRunning=true;musicCounts.start++;let step=0;const chords=[[48,55,60],[46,53,58],[51,58,63],[43,50,55],[48,55,60],[53,60,65],[46,53,58],[43,50,55]],melodies=[[72,75,79,84,79,75,72,75],[74,77,81,86,81,77,74,77],[75,79,82,87,82,79,75,79],[70,74,77,82,77,74,70,74]];musicTimer=win.setInterval(()=>{if(!musicRunning)return;const bar=Math.floor(step/8)%40,beat=step%8,section=bar<4?0:bar<12?1:bar<20?2:bar<28?3:bar<32?4:5,chord=chords[bar%chords.length],intensity=Math.min(3,Math.floor((game?.wave||1)/3));if(beat%2===0)tone(hz(chord[0]),.18,'square',.105,'music',.72);if(section!==4||beat%4===0)tone(hz(chord[1+(beat%3)] + (beat%2?12:0)),.095,'triangle',.065,'music',.68);if(section>=2&&beat%2===1)tone(hz(melodies[(bar>>1)%melodies.length][beat]),.18,'sawtooth',.075,'music',.82);if((section===3||section===5||intensity>1)&&beat%4===0)tone(64,.08,'square',.08,'music',.72);if((section===3||section===5||intensity>2)&&beat%2===1)tone(1750,.025,'square',.025,'music',.9);step++;},60000/124/2);}
    function stopMusic(){if(musicTimer!==null){win.clearInterval(musicTimer);musicTimer=null;}if(musicRunning)musicCounts.stop++;musicRunning=false;}
    function resize(){if(!canvas||!game)return;counts.resizeCount++;const r=screen.getBoundingClientRect(),d=Math.min(win.devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(d,0,0,d,0,0);game.width=r.width;game.height=r.height;game.groundY=r.height-Math.round(r.height*.18);terrain=Array.from({length:18},(_,i)=>({x:i*r.width/17,y:game.groundY+((i*17)%23)-10}));stars=Array.from({length:100},(_,i)=>({x:(i*97.31)%r.width,y:(i*53.17)%(r.height*.76),a:.2+(i%5)*.12}));}
    function asteroid(a){ctx.beginPath();a.shape.forEach(([x,y],i)=>{const c=Math.cos(a.angle),s=Math.sin(a.angle),X=a.x+x*c-y*s,Y=a.y+x*s+y*c;i?ctx.lineTo(X,Y):ctx.moveTo(X,Y);});ctx.closePath();}
    function ground(){const w=game.width,h=game.height,y=game.groundY;ctx.save();ctx.fillStyle='#09151d';ctx.beginPath();ctx.moveTo(0,h);ctx.lineTo(0,terrain[0].y);terrain.forEach(p=>ctx.lineTo(p.x,p.y));ctx.lineTo(w,h);ctx.closePath();ctx.fill();ctx.strokeStyle='#4caec0';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#132a32';for(let i=1;i<terrain.length;i+=4){const p=terrain[i];ctx.beginPath();ctx.ellipse(p.x,p.y+22,18,5,0,0,7);ctx.fill();}ctx.fillStyle='#152e38';ctx.fillRect(w*.18,y+10,44,16);ctx.fillRect(w*.76,y+6,34,20);ctx.strokeStyle='#79eaff';ctx.beginPath();ctx.moveTo(w*.2,y+10);ctx.lineTo(w*.2,y-17);ctx.lineTo(w*.225,y+10);ctx.moveTo(w*.78,y+6);ctx.lineTo(w*.78,y-25);ctx.stroke();ctx.fillStyle='#7dfff0';for(const x of [w*.18,w*.22,w*.76,w*.8])ctx.fillRect(x,y+15,3,3);ctx.restore();}
    function drawTurret(){const t=game.turret;ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='rgba(76,220,255,.18)';ctx.beginPath();ctx.ellipse(0,18,72,20,0,0,7);ctx.fill();ctx.fillStyle='#152b37';ctx.beginPath();ctx.ellipse(0,18,58,17,0,0,7);ctx.fill();ctx.strokeStyle='#69e7ff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#74efff';ctx.fillRect(-42,13,7,5);ctx.fillRect(35,13,7,5);ctx.rotate(t.angle);ctx.fillStyle='#203e4b';ctx.fillRect(-5,-12-t.recoil*8,48,24);ctx.fillStyle=t.heat>.4?'#ffbd68':'#70eaff';ctx.fillRect(35,-5-t.recoil*8,20,10);ctx.restore();}
    function draw(){counts.renderCount++;const w=game.width,h=game.height;ctx.fillStyle='#020710';ctx.fillRect(0,0,w,h);for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle='#d5f7ff';ctx.fillRect(s.x,s.y,1,1);}ctx.globalAlpha=1;ctx.save();ctx.translate((Math.random()-.5)*game.shake*10,(Math.random()-.5)*game.shake*10);for(const a of game.enemies){ctx.strokeStyle='#a8f4ff';ctx.lineWidth=2;asteroid(a);ctx.stroke();}for(const p of game.shots){ctx.strokeStyle='#ffe99a';ctx.beginPath();ctx.moveTo(p.px,p.py);ctx.lineTo(p.x,p.y);ctx.stroke();}for(const p of game.particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);}ctx.globalAlpha=1;ground();drawTurret();ctx.restore();if(game.flash){ctx.fillStyle=`rgba(255,100,80,${game.flash*.25})`;ctx.fillRect(0,0,w,h);}hud();}
    function hud(){ctx.fillStyle='#c7eef2';ctx.font='600 12px ui-monospace,monospace';ctx.fillText(`SCORE ${String(game.score).padStart(6,'0')}`,24,30);ctx.fillText(`WAVE ${String(game.wave).padStart(2,'0')}`,24,50);ctx.fillText(`BASE ${'█'.repeat(game.base)}${'░'.repeat(Core.BASE_HEALTH-game.base)}`,24,70);ctx.textAlign='right';ctx.fillText(`COMBO x${game.combo}`,game.width-24,30);ctx.textAlign='center';if(game.state==='TITLE'||game.state==='COUNTDOWN'||game.state==='GAMEOVER'){const lost=game.state==='GAMEOVER';ctx.fillStyle='#e8fbff';ctx.font=`700 ${Math.min(70,game.width*.075)}px ui-monospace,monospace`;ctx.fillText(lost?'OUTPOST LOST':'NEBU STRIKE',game.width/2,game.height*.31);ctx.fillStyle='#8be8fb';ctx.font='15px ui-monospace,monospace';ctx.fillText(lost?`SCORE ${game.score} · WAVE ${game.wave} · ENTER TO RESTART`:'DEEP SPACE DEFENSE',game.width/2,game.height*.37);ctx.fillStyle='#ffd88e';if(game.state==='COUNTDOWN'){const n=Math.max(1,Math.ceil(game.countdown));ctx.fillText('SYSTEM ONLINE',game.width/2,game.height*.45);ctx.fillText('DEFENSE GRID ACTIVE',game.width/2,game.height*.49);ctx.fillText(`WAVE 01 · INCOMING · ${n}`,game.width/2,game.height*.55);}else ctx.fillText('PLANETARY DEFENSE SYSTEM ONLINE · ENTER / CLICK TO START',game.width/2,game.height*.47);if(game.state==='TITLE')ctx.fillText('MOUSE AIM · CLICK FIRE · A / D AIM · SPACE FIRE',game.width/2,game.height*.53);ctx.textAlign='left';}}
    function frame(now){rafId=null;if(lifecycle!==Lifecycle.RUNNING)return;const old=game.state,score=game.score,base=game.base,combo=game.combo,shot=game.shots.length;Core.update(game,keys,Math.min(.05,(now-last)/1000||0));last=now;if(game.shots.length>shot)sfx('fire');if(game.score>score)sfx(game.combo>combo?'combo':'destroy');if(game.base<base)sfx('impact');if(old==='COUNTDOWN'&&game.state==='PLAYING')sfx('wave');if(old!=='GAMEOVER'&&game.state==='GAMEOVER'){sfx('over');stopMusic();}draw();request();}function request(){if(lifecycle===Lifecycle.RUNNING&&rafId===null)rafId=win.requestAnimationFrame(frame);}
    function begin(){if(game&&(game.state==='TITLE'||game.state==='GAMEOVER')){Core.start(game);startMusic();sfx('wave');}}
    const pointer=e=>{const p=e.touches?.[0]||e,r=canvas.getBoundingClientRect();keys.aimX=p.clientX-r.left;keys.aimY=p.clientY-r.top;},down=e=>{pointer(e);keys.fire=true;begin();},up=()=>keys.fire=false;
    const keydown=e=>{if(['ArrowLeft','ArrowRight',' ','a','d','Enter'].includes(e.key))e.preventDefault();if(e.key==='Enter')begin();if(e.key.toLowerCase()==='r'){Core.start(game);startMusic();}keys.left=keys.left||e.key==='ArrowLeft'||e.key.toLowerCase()==='a';keys.right=keys.right||e.key==='ArrowRight'||e.key.toLowerCase()==='d';keys.fire=keys.fire||e.key===' ';},keyup=e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')keys.left=false;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')keys.right=false;if(e.key===' ')keys.fire=false;};
    const restart=()=>{Core.start(game);startMusic();},fullscreen=()=>screen.requestFullscreen?.(),musicToggle=()=>{musicEnabled=!musicEnabled;if(!musicEnabled)stopMusic();else if(game?.state==='PLAYING'||game?.state==='COUNTDOWN')startMusic();const b=doc.querySelector('#gameMusic');if(b){b.textContent=`MUSIC ${musicEnabled?'ON':'OFF'}`;b.setAttribute('aria-pressed',musicEnabled);}},sfxToggle=()=>{sfxEnabled=!sfxEnabled;const b=doc.querySelector('#gameSfx');if(b){b.textContent=`SFX ${sfxEnabled?'ON':'OFF'}`;b.setAttribute('aria-pressed',sfxEnabled);}};
    function attach(){if(attached)return;win.addEventListener('resize',resize);win.addEventListener('keydown',keydown);win.addEventListener('keyup',keyup);canvas.addEventListener('mousemove',pointer);canvas.addEventListener('mousedown',down);canvas.addEventListener('click',begin);win.addEventListener('mouseup',up);canvas.addEventListener('touchstart',down,{passive:true});canvas.addEventListener('touchmove',down,{passive:true});canvas.addEventListener('touchend',up);doc.querySelector('#gameRestart').addEventListener('click',restart);doc.querySelector('#gameFullscreen').addEventListener('click',fullscreen);doc.querySelector('#gameMusic')?.addEventListener('click',musicToggle);doc.querySelector('#gameSfx')?.addEventListener('click',sfxToggle);attached=true;}
    function detach(){if(!attached)return;win.removeEventListener('resize',resize);win.removeEventListener('keydown',keydown);win.removeEventListener('keyup',keyup);canvas.removeEventListener('mousemove',pointer);canvas.removeEventListener('mousedown',down);canvas.removeEventListener('click',begin);win.removeEventListener('mouseup',up);canvas.removeEventListener('touchstart',down);canvas.removeEventListener('touchmove',down);canvas.removeEventListener('touchend',up);doc.querySelector('#gameRestart').removeEventListener('click',restart);doc.querySelector('#gameFullscreen').removeEventListener('click',fullscreen);doc.querySelector('#gameMusic')?.removeEventListener('click',musicToggle);doc.querySelector('#gameSfx')?.removeEventListener('click',sfxToggle);attached=false;}
    function launch(){if(lifecycle===Lifecycle.INITIALIZING||lifecycle===Lifecycle.RUNNING)return false;counts.launchCount++;lifecycle=Lifecycle.INITIALIZING;canvas=doc.querySelector('#gameCanvas');screen=doc.querySelector('#gameScreen');ctx=canvas.getContext('2d');game=Core.createGame();keys={};last=0;attach();resize();lifecycle=Lifecycle.RUNNING;counts.gameInitCount++;counts.rafStartCount++;request();return true;}function stop(){if(lifecycle!==Lifecycle.RUNNING&&lifecycle!==Lifecycle.INITIALIZING)return;lifecycle=Lifecycle.STOPPED;if(rafId!==null)win.cancelAnimationFrame(rafId);rafId=null;stopMusic();detach();}return{launch,stop,destroy:stop,getLifecycle:()=>lifecycle,getCounts:()=>({...counts}),getMusicCounts:()=>({...musicCounts,running:musicRunning}),getGame:()=>game,Lifecycle};
  }return{createGameView,Lifecycle};
});
