(function(root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (root) root.NebuStrikeView = api;
})(typeof window !== 'undefined' ? window : globalThis, function() {
  'use strict';

  const Lifecycle = Object.freeze({ UNINITIALIZED: 'UNINITIALIZED', INITIALIZING: 'INITIALIZING', RUNNING: 'RUNNING', STOPPED: 'STOPPED' });
  const finite = value => Number.isFinite(value);

  function createGameView({ window: win, document: doc, Core }) {
    let lifecycle = Lifecycle.UNINITIALIZED, game, canvas, ctx, screen, rafId = null, lastTime = 0;
    let keys = {}, attached = false, pixelRatio = 1, stars = [], terrain = [], frameNumber = 0, lastContract = null, lastRenderLayers = [];
    const counts = { launchCount: 0, gameInitCount: 0, rafStartCount: 0, rafScheduledCount: 0, rafCallbackCount: 0, resizeCount: 0, renderCount: 0, renderFrameCount: 0, canvasWidth: 0, canvasHeight: 0, contextAvailable: false, turretDrawCalls: 0, hudDrawCalls: 0, backingStoreResets: 0, canvasConnected: true, canvasMatchesDOM: true, contextMatchesCanvas: true, visibleWidth: 0, visibleHeight: 0 };

    function makeLayout(width, height) {
      // Deterministic coordinates are the only view cache. No offscreen canvases or assets exist.
      stars = Array.from({ length: 180 }, (_, i) => ({ x: (i * 97.31) % width, y: (i * 53.17) % (height * .78), alpha: .12 + (i % 7) * .075, size: i % 37 === 0 ? 2 : i % 11 === 0 ? 1.4 : .8 }));
      terrain = Array.from({ length: 23 }, (_, i) => ({ x: i * width / 22, y: game.groundY + ((i * 19) % 25) - 12 - (i % 5 === 0 ? 8 : 0) }));
    }
    function resize() {
      if (!canvas || !ctx || !game) return;
      counts.resizeCount++;
      const rect = screen.getBoundingClientRect(), width = Math.max(1, Math.round(rect.width || win.innerWidth || canvas.clientWidth || 1));
      const height = Math.max(1, Math.round(rect.height || ((win.innerHeight || canvas.clientHeight || 1) - 56)));
      const ratio = Math.min(win.devicePixelRatio || 1, 2), backingWidth = Math.round(width * ratio), backingHeight = Math.round(height * ratio);
      counts.visibleWidth = width; counts.visibleHeight = height;
      if (canvas.width === backingWidth && canvas.height === backingHeight && pixelRatio === ratio && game.width === width && game.height === height) return;
      pixelRatio = ratio; canvas.width = backingWidth; canvas.height = backingHeight; canvas.style.width = `${width}px`; canvas.style.height = `${height}px`;
      game.width = width; game.height = height; game.groundY = height - Math.round(height * .19); game.ground = { visible: true, height: height - game.groundY };
      counts.canvasWidth = backingWidth; counts.canvasHeight = backingHeight; counts.backingStoreResets++; makeLayout(width, height);
    }
    function resetContext() { ctx.setTransform(1, 0, 0, 1, 0, 0); ctx.globalAlpha = 1; ctx.globalCompositeOperation = 'source-over'; if ('filter' in ctx) ctx.filter = 'none'; ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0); }
    function drawBackground() {
      const gradient = ctx.createLinearGradient(0, 0, 0, game.height); gradient.addColorStop(0, '#01040c'); gradient.addColorStop(1, '#071527'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, game.width, game.height);
      for (const band of [{ x: game.width * .22, y: game.height * .2, r: game.width * .32 }, { x: game.width * .78, y: game.height * .42, r: game.width * .25 }]) { const haze = ctx.createRadialGradient(band.x, band.y, 0, band.x, band.y, band.r); haze.addColorStop(0, 'rgba(25,72,118,.13)'); haze.addColorStop(1, 'rgba(4,13,31,0)'); ctx.fillStyle = haze; ctx.fillRect(band.x - band.r, band.y - band.r, band.r * 2, band.r * 2); }
      for (const star of stars) { ctx.globalAlpha = star.alpha; ctx.fillStyle = star.size > 1.5 ? '#e9fbff' : '#9fd6ef'; ctx.fillRect(star.x, star.y, star.size, star.size); } ctx.globalAlpha = 1;
    }
    function drawGround() { const y = game.groundY; ctx.fillStyle = '#091821'; ctx.beginPath(); ctx.moveTo(0, game.height); ctx.lineTo(0, terrain[0].y); terrain.forEach(p => ctx.lineTo(p.x, p.y)); ctx.lineTo(game.width, game.height); ctx.closePath(); ctx.fill(); ctx.strokeStyle = '#4b8d98'; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#03090e'; ctx.fillRect(0, y + 30, game.width, game.height - y - 30); ctx.fillStyle = '#18313a'; for (let i = 2; i < terrain.length; i += 5) { const p = terrain[i]; ctx.beginPath(); ctx.ellipse(p.x, y + 37, 18, 5, 0, 0, Math.PI * 2); ctx.fill(); } }
    function drawBaseStructures() { const y = game.groundY, w = game.width; ctx.fillStyle = '#15303a'; ctx.fillRect(w * .17, y + 9, 45, 18); ctx.fillRect(w * .76, y + 7, 36, 20); ctx.strokeStyle = '#87f4ff'; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(w * .2, y + 9); ctx.lineTo(w * .2, y - 20); ctx.lineTo(w * .225, y + 9); ctx.moveTo(w * .78, y + 7); ctx.lineTo(w * .78, y - 24); ctx.stroke(); ctx.fillStyle = '#7dfff0'; [w * .18, w * .22, w * .76, w * .8].forEach(x => ctx.fillRect(x, y + 15, 3, 3)); }
    function drawAsteroid(a) { ctx.save(); ctx.translate(a.x, a.y); ctx.rotate(a.angle || 0); ctx.beginPath(); (a.shape || []).forEach(([x, y], i) => i ? ctx.lineTo(x, y) : ctx.moveTo(x, y)); if (!(a.shape || []).length) ctx.arc(0, 0, a.size, 0, Math.PI * 2); ctx.closePath(); const shade = ctx.createRadialGradient(-a.size * .35, -a.size * .35, 1, 0, 0, a.size); shade.addColorStop(0, '#7b898c'); shade.addColorStop(.55, '#39464c'); shade.addColorStop(1, '#10181e'); ctx.fillStyle = shade; ctx.fill(); ctx.strokeStyle = '#65d8e5'; ctx.lineWidth = Math.max(1, a.size * .04); ctx.stroke(); ctx.fillStyle = 'rgba(8,14,18,.48)'; for (const c of (a.visual?.craters || []).slice(0, 4)) { ctx.beginPath(); ctx.arc(Math.cos(c[0]) * a.size * c[1], Math.sin(c[0]) * a.size * c[1], a.size * c[2], 0, Math.PI * 2); ctx.fill(); } ctx.restore(); }
    function drawEntities() { for (const a of game.enemies) drawAsteroid(a); for (const p of game.shots) { ctx.strokeStyle = 'rgba(73,224,255,.28)'; ctx.lineWidth = 7; ctx.beginPath(); ctx.moveTo(p.px, p.py); ctx.lineTo(p.x, p.y); ctx.stroke(); ctx.fillStyle = '#fff8ce'; ctx.beginPath(); ctx.arc(p.x, p.y, 2.5, 0, Math.PI * 2); ctx.fill(); } }
    function drawTurret() { const t = game.turret, x = game.width / 2, y = game.groundY - 16; counts.turretDrawCalls++; lastContract.turretDrawn = true; lastContract.turretAnchorX = x; lastContract.turretAnchorY = y; ctx.save(); ctx.translate(x, y); ctx.fillStyle = 'rgba(65,221,246,.16)'; ctx.beginPath(); ctx.ellipse(0, 19, 72, 20, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#12232b'; ctx.beginPath(); ctx.ellipse(0, 18, 62, 17, 0, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#6be9f5'; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#274550'; ctx.fillRect(-39, 0, 78, 18); ctx.fillStyle = '#345b67'; ctx.fillRect(-28, -13, 56, 17); ctx.fillStyle = '#7dfff0'; ctx.fillRect(-24, 7, 7, 3); ctx.fillRect(17, 7, 7, 3); ctx.rotate(t.angle); ctx.translate(-Math.max(0, t.recoil) * 7, 0); ctx.fillStyle = '#315a67'; ctx.fillRect(-16, -14, 36, 28); ctx.fillStyle = '#476f7a'; ctx.fillRect(13, -8, 55, 16); ctx.fillStyle = '#0c1a20'; ctx.fillRect(25, -4, 45, 8); ctx.strokeStyle = '#8cf4ff'; ctx.strokeRect(13, -8, 55, 16); ctx.fillStyle = t.heat > .45 ? '#ff9d59' : '#80ecf6'; ctx.fillRect(62, -5, 13, 10); if (t.fire > 0) { ctx.fillStyle = 'rgba(255,197,106,.58)'; ctx.beginPath(); ctx.arc(77, 0, 13, 0, Math.PI * 2); ctx.fill(); } ctx.restore(); }
    function drawEffects() { for (const p of game.particles) { ctx.globalAlpha = Math.min(1, p.life * 2); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, 2.5, 2.5); } ctx.globalAlpha = 1; if (game.flash) { ctx.fillStyle = `rgba(255,100,80,${game.flash * .22})`; ctx.fillRect(0, 0, game.width, game.height); } }
    function drawHUD() { counts.hudDrawCalls++; lastContract.hudDrawn = true; ctx.fillStyle = '#c7eef2'; ctx.font = '600 12px ui-monospace, monospace'; ctx.fillText(`SCORE ${String(game.score).padStart(6, '0')}`, 24, 30); ctx.fillText(`WAVE ${String(game.wave).padStart(2, '0')}`, 24, 50); ctx.fillText(`BASE ${'█'.repeat(game.base)}${'░'.repeat(Core.BASE_HEALTH - game.base)}`, 24, 70); ctx.textAlign = 'right'; ctx.fillText(`COMBO x${game.combo}`, game.width - 24, 30); ctx.textAlign = 'left'; }
    function drawOverlay() { if (game.state === 'PLAYING') return; const middle = game.width / 2; ctx.textAlign = 'center'; ctx.fillStyle = '#e8fbff'; ctx.font = `700 ${Math.min(70, game.width * .075)}px ui-monospace, monospace`; ctx.fillText(game.state === 'GAMEOVER' ? 'OUTPOST LOST' : 'NEBU STRIKE', middle, game.height * .31); ctx.font = '15px ui-monospace, monospace'; ctx.fillStyle = '#8be8fb'; if (game.state === 'TITLE') { ctx.fillText('DEEP SPACE DEFENSE', middle, game.height * .37); ctx.fillText('PLANETARY DEFENSE SYSTEM ONLINE', middle, game.height * .47); ctx.fillText('ENTER / CLICK TO START', middle, game.height * .53); } else if (game.state === 'COUNTDOWN') { ctx.fillText(`WAVE ${String(Math.max(1, game.wave + 1)).padStart(2, '0')} · INCOMING`, middle, game.height * .43); ctx.font = '700 48px ui-monospace, monospace'; ctx.fillText(String(Math.max(1, Math.ceil(game.countdown))), middle, game.height * .55); } else ctx.fillText(`SCORE ${game.score} · WAVE ${game.wave} · BEST ${game.best} · ENTER TO RESTART`, middle, game.height * .47); ctx.textAlign = 'left'; }
    function render() { if (!canvas || !ctx || !game) return; frameNumber++; counts.canvasConnected = typeof canvas.isConnected !== 'boolean' || canvas.isConnected; counts.canvasMatchesDOM = doc.querySelector('#gameCanvas') === canvas; counts.contextMatchesCanvas = !ctx.canvas || ctx.canvas === canvas; lastContract = { canvasWidth: canvas.width, canvasHeight: canvas.height, groundY: game.groundY, turretAnchorX: null, turretAnchorY: null, turretDrawn: false, hudDrawn: false, backgroundDrawn: false, groundDrawn: false, frameNumber }; lastRenderLayers = []; resetContext(); lastRenderLayers.push('clear'); drawBackground(); lastRenderLayers.push('background'); lastContract.backgroundDrawn = true; drawGround(); lastRenderLayers.push('ground'); lastContract.groundDrawn = true; drawBaseStructures(); lastRenderLayers.push('baseStructures'); drawEntities(); lastRenderLayers.push('gameplayEntities'); drawTurret(); lastRenderLayers.push('turret'); drawEffects(); lastRenderLayers.push('effects'); drawHUD(); lastRenderLayers.push('hud'); drawOverlay(); lastRenderLayers.push('stateOverlay'); }
    function request() { if (lifecycle === Lifecycle.RUNNING && rafId === null) { counts.rafScheduledCount++; rafId = win.requestAnimationFrame(frame); } }
    function frame(now) { rafId = null; counts.rafCallbackCount++; if (lifecycle !== Lifecycle.RUNNING) return; Core.update(game, keys, Math.min(.05, ((now - lastTime) / 1000) || 0)); lastTime = now; render(); counts.renderCount++; counts.renderFrameCount++; request(); }
    function begin() { if (game && (game.state === 'TITLE' || game.state === 'GAMEOVER')) Core.start(game); }
    function pointer(event) { const p = event.touches?.[0] || event, r = canvas.getBoundingClientRect(); keys.aimX = p.clientX - r.left; keys.aimY = p.clientY - r.top; }
    const down = event => { pointer(event); keys.fire = true; begin(); }, up = () => { keys.fire = false; };
    function keydown(event) { const key = event.key.toLowerCase(); if (['arrowleft', 'arrowright', ' ', 'a', 'd', 'enter'].includes(key)) event.preventDefault(); if (key === 'enter') begin(); if (key === 'r') restart(); keys.left = key === 'arrowleft' || key === 'a' || keys.left; keys.right = key === 'arrowright' || key === 'd' || keys.right; keys.fire = key === ' ' || keys.fire; }
    function keyup(event) { const key = event.key.toLowerCase(); if (key === 'arrowleft' || key === 'a') keys.left = false; if (key === 'arrowright' || key === 'd') keys.right = false; if (key === ' ') keys.fire = false; }
    function restart() { if (game) Core.start(game); }
    function attach() { if (attached) return; win.addEventListener('resize', resize); win.addEventListener('keydown', keydown); win.addEventListener('keyup', keyup); canvas.addEventListener('mousemove', pointer); canvas.addEventListener('mousedown', down); canvas.addEventListener('click', begin); win.addEventListener('mouseup', up); canvas.addEventListener('touchstart', down, { passive: true }); canvas.addEventListener('touchmove', down, { passive: true }); canvas.addEventListener('touchend', up); doc.querySelector('#gameRestart').addEventListener('click', restart); doc.querySelector('#gameFullscreen').addEventListener('click', () => screen.requestFullscreen?.()); attached = true; }
    function detach() { if (!attached) return; win.removeEventListener('resize', resize); win.removeEventListener('keydown', keydown); win.removeEventListener('keyup', keyup); canvas.removeEventListener('mousemove', pointer); canvas.removeEventListener('mousedown', down); canvas.removeEventListener('click', begin); win.removeEventListener('mouseup', up); canvas.removeEventListener('touchstart', down); canvas.removeEventListener('touchmove', down); canvas.removeEventListener('touchend', up); doc.querySelector('#gameRestart').removeEventListener('click', restart); attached = false; }
    function launch() { if (lifecycle === Lifecycle.INITIALIZING || lifecycle === Lifecycle.RUNNING) return false; lifecycle = Lifecycle.INITIALIZING; counts.launchCount++; canvas = doc.querySelector('#gameCanvas'); screen = doc.querySelector('#gameScreen'); ctx = canvas?.getContext('2d'); counts.contextAvailable = !!ctx; if (!ctx) { lifecycle = Lifecycle.STOPPED; return false; } game = Core.createGame(); keys = {}; lastTime = 0; attach(); resize(); lifecycle = Lifecycle.RUNNING; counts.gameInitCount++; counts.rafStartCount++; request(); return true; }
    function stop() { if (lifecycle !== Lifecycle.RUNNING && lifecycle !== Lifecycle.INITIALIZING) return; lifecycle = Lifecycle.STOPPED; if (rafId !== null) win.cancelAnimationFrame(rafId); rafId = null; detach(); }
    return { launch, stop, destroy: stop, restart, render, getLifecycle: () => lifecycle, getCounts: () => ({ ...counts }), getGame: () => game, getLastRenderLayers: () => [...lastRenderLayers], getLastRenderContract: () => lastContract && ({ ...lastContract }), getTurretRenderMetrics: () => ({ drawCalls: counts.turretDrawCalls, geometry: game && Core.turretGeometry(game) }), getHudDescriptor: () => ({ state: game?.state, score: true, wave: true, base: true, combo: true, terminal: true, music: true, sfx: true, restart: true, fullscreen: true }), getBackgroundMetrics: () => ({ cacheWidth: 0, cacheHeight: 0, buildCount: 0, procedural: true }), Lifecycle };
  }
  return { createGameView, Lifecycle };
});
