(() => {
  const api = window.LinuxGameTerminal, output = document.querySelector('#output'), input = document.querySelector('#terminalInput'), mission = document.querySelector('#mission'), launch = document.querySelector('#launchScreen');
  let state, steps, history = [], historyIndex = 0, launchTimer = null;
  const gameView = window.NebuStrikeView.createGameView({ window, document, Core: window.NebuStrike });
  function print(text, className = '') { if (!text) return; const el = document.createElement('pre'); el.className = className; el.textContent = text; output.append(el); output.scrollTop = output.scrollHeight; }
  function drawMission() { mission.innerHTML = [['01','UPDATE PACKAGE INFORMATION',steps.updated],['02','SEARCH FOR A GAME',steps.searched],['03','INSTALL NEBU STRIKE',steps.installed],['04','VERIFY THE PACKAGE',state.installed],['05','LAUNCH GAME',steps.launched],['06','PLAY',steps.launched]].map(([n,t,done]) => `<li class="${done ? 'done' : ''}"><b>${n}</b> ${t}${done ? ' ✓' : ''}</li>`).join(''); }
  function prompt() { return `visitor@nebunix:${state.system.cwd.replace('/home/visitor', '~') || '/'}$`; }
  const controller = window.LinuxGameLab.createController(api, result => { state = result.state; steps = result.steps; print(`${prompt()} ${result.command}`, 'command'); document.querySelector('.terminal header strong').textContent = prompt().slice(0, -1); document.querySelector('.prompt').textContent = prompt(); if (result.action === 'clear') output.innerHTML = ''; else print(result.output); if (result.action === 'reset') { clearTimeout(launchTimer); gameView.stop(); launch.hidden = true; } if (result.action === 'launch') { clearTimeout(launchTimer); launchTimer = setTimeout(() => { launch.hidden = false; gameView.launch(); launch.focus(); }, 600); } drawMission(); });
  ({ state, steps } = controller.snapshot());
  function run(command, source) { return controller.submit(command, source); }
  input.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'l') { event.preventDefault(); output.innerHTML = ''; return; } if (event.key === 'Enter') { const value = input.value; if (value.trim()) { history.push(value); historyIndex = history.length; } input.value = ''; run(value); } else if (event.key === 'ArrowUp') { event.preventDefault(); if (history.length) input.value = history[historyIndex = Math.max(0, historyIndex - 1)]; } else if (event.key === 'ArrowDown') { event.preventDefault(); input.value = historyIndex < history.length - 1 ? history[++historyIndex] : ''; } });
  document.querySelector('#terminal').addEventListener('click', () => input.focus()); document.querySelectorAll('[data-command]').forEach(button => button.addEventListener('click', () => { const command = button.dataset.command; input.value = ''; run(command, 'helper'); input.focus(); })); document.querySelector('#returnTerminal').addEventListener('click', () => { clearTimeout(launchTimer); gameView.stop(); launch.hidden = true; input.focus(); }); document.querySelector('#resetSession').addEventListener('click', () => run('reset'));
  print('Nebunix GNU/Linux 12 (museum educational build)\nBROWSER-ONLY EDUCATIONAL SIMULATION\nCommands affect only temporary virtual state. No sudo privileges, real filesystem access, package downloads, telemetry, or network requests.\n\nType help to see available commands.'); drawMission(); input.focus();
})();
