(() => {
  'use strict';
  const STORAGE_KEY = 'computerMuseum.pcXtCommandDesk.v1';
  const SCHEMA_VERSION = 1;
  const DISK_CAPACITY = 10 * 1024 * 1024;
  const MAX_RENDERED_LINES = 900;
  const EDIT_MAX_BYTES = 64 * 1024;
  const BOOT = ['PC XT Command Desk','','Educational DOS Environment','Version 1.0','','Copyright (C) Dennis Hilk',''];
  const nowIso = () => '1992-04-06T08:00:00.000Z';
  const attrs = () => ({ readOnly: false, hidden: false, system: false, archive: true });
  const file = (content) => ({ type:'file', content, attributes: attrs(), createdAt: nowIso(), modifiedAt: nowIso() });
  const dir = (children = {}) => ({ type:'directory', children, attributes: attrs(), createdAt: nowIso(), modifiedAt: nowIso() });
  function defaultFs(){ return dir({
    'AUTOEXEC.BAT': file('@ECHO OFF\nPROMPT $P$G\nPATH C:\\DOS;C:\\UTIL\nSET TEMP=C:\\TMP\nSET BLASTER=A220 I5 D1 T4\n\nREM PC XT Command Desk\nREM Educational DOS configuration\nREM Files exist only inside this browser\n'),
    'CONFIG.SYS': file('FILES=30\nBUFFERS=20\nLASTDRIVE=Z\nDEVICE=C:\\DOS\\HIMEM.SYS\nDOS=HIGH,UMB\n\nREM Educational configuration example\n'),
    'README.TXT': file('PC XT Command Desk\n\nThis is an original educational DOS environment for the Computer Museum. It is not an emulator, not a virtual machine, and it does not run a real operating system.\n\nType HELP to see available commands. Use DIR to list directories, CD to move through them, and TYPE to read text files.\n\nAll files exist only inside this browser. Your PATH, SET variables, prompt format, and future file changes are stored locally for you. The website server and your real filesystem are never accessed.\n\nUse RESET to restore the original museum filesystem. RESET only removes the PC XT Command Desk localStorage record.\n'),
    DOS: dir({ 'HELP.TXT': file('PC XT Command Desk help files are original museum text. Try HELP, DIR, CD, TYPE, TREE, MEM, CHKDSK, PATH, SET, PROMPT, ECHO, VER, DATE, TIME, CLS and RESET. Configuration examples are educational and are not executable drivers.\n'), 'COMMANDS.TXT': file('Implemented commands inspect the virtual filesystem or stored environment state. Future maintenance commands such as COPY, DEL and REN are intentionally deferred. EDIT opens existing text files for browser-local changes.\n'), 'MEMORY.TXT': file('The MEM command reports a simulated educational memory model. It teaches conventional, upper and extended memory ideas without querying real hardware.\n') }),
    WINDOWS: dir({ 'WIN.INI': file('[windows]\nload=\nrun=\nbeep=yes\n\n[desktop]\nwallpaper=none\ntilewallpaper=0\n\n[extensions]\ntxt=notepad.exe ^.txt\n'), 'SYSTEM.INI': file('[boot]\nshell=progman.exe\ndrivers=mmsystem.dll\n\n[386Enh]\nwoafont=dosapp.fon\n\n[drivers]\nwave=simulated\n') }),
    GAMES: dir({ DOOM: dir({ 'README.TXT': file('This folder represents early 1990s shareware-era action games as a museum reference. No game executable, assets, levels, manual text or original files are included.\n') }), DUKE3D: dir({ 'README.TXT': file('This folder is an educational placeholder for mid-1990s PC game directory habits. It contains no game executable, copyrighted assets or original documentation.\n') }), PRINCE: dir({ 'README.TXT': file('This folder represents cinematic platform games often launched from DOS directories. It is museum text only; no original game files are included.\n') }), WOLF3D: dir({ 'README.TXT': file('This folder represents early first-person PC action games and command-line launch culture. No game binary, art, audio, maps or manuals are included.\n') }) }),
    UTIL: dir({ 'README.TXT': file('Utility folders commonly held helpers for disks, memory, archives or diagnostics. This exhibit includes only original explanatory text.\n') }),
    TMP: dir({})
  }); }
  function defaultState(){ return { schemaVersion:SCHEMA_VERSION, filesystem:defaultFs(), cwd:[], environment:{ TEMP:'C:\\TMP', BLASTER:'A220 I5 D1 T4' }, path:'C:\\DOS;C:\\UTIL', promptFormat:'$P$G', echo:true }; }
  function validNode(n, depth=0){ if(!n || depth>30 || !['file','directory'].includes(n.type)) return false; if(n.type==='file') return typeof n.content==='string' && n.attributes && typeof n.createdAt==='string'; if(!n.children || typeof n.children!=='object') return false; return Object.keys(n.children).every(k=>k===k.toUpperCase() && validNode(n.children[k], depth+1)); }
  function validateState(s){ return s && s.schemaVersion===SCHEMA_VERSION && validNode(s.filesystem) && Array.isArray(s.cwd) && s.cwd.every(x=>typeof x==='string') && s.environment && typeof s.environment==='object' && typeof s.path==='string' && typeof s.promptFormat==='string'; }
  function loadState(){ try{ const raw=localStorage.getItem(STORAGE_KEY); if(!raw) return defaultState(); const parsed=JSON.parse(raw); return validateState(parsed) ? parsed : defaultState(); }catch{ return defaultState(); } }
  function saveState(state){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
  function canonical(parts){ return 'C:\\' + parts.join('\\'); }
  function splitCommand(line){ const t=line.trim(); if(!t) return { command:'', args:'' }; const m=t.match(/^([A-Za-z]+)(.*)$/); return m ? { command:m[1].toUpperCase(), args:m[2].trim() } : { command:t.toUpperCase(), args:'' }; }
  function firstArg(args){ const s=args.trim(); if(!s) return ''; if(s[0]==='"'){ const end=s.indexOf('"',1); return end>=0?s.slice(1,end):s.slice(1); } return s.split(/\s+/)[0]; }
  function normalizePath(input, cwd=[]){ let raw=(input||'').trim(); raw=firstArg(raw); if(!raw) return { parts:[...cwd] }; raw=raw.replace(/\//g,'\\'); raw=raw.replace(/^CD\\/i,'\\'); let base=[...cwd]; if(/^C:/i.test(raw)){ raw=raw.slice(2); base=[]; } if(raw.startsWith('\\')) base=[]; const pieces=raw.split(/\\+/).filter(Boolean); for(const piece of pieces){ if(piece==='.') continue; if(piece==='..') base.pop(); else base.push(piece.toUpperCase()); } return { parts:base }; }
  function lookup(fs, parts){ let node=fs; for(const part of parts){ if(!node || node.type!=='directory') return null; const key=Object.keys(node.children).find(k=>k.toUpperCase()===part.toUpperCase()); if(!key) return null; node=node.children[key]; } return node; }
  function bytes(s){ return new TextEncoder().encode(s).length; }
  function isPlainText(content){ return typeof content==='string' && !/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(content); }
  function canEditNode(node){ if(!node || node.type==='directory') return { ok:false, reason:node?'Cannot edit a directory':'File not found' }; if(node.type!=='file' || !isPlainText(node.content)) return { ok:false, reason:'File type not supported by EDIT' }; if(bytes(node.content)>EDIT_MAX_BYTES) return { ok:false, reason:'File too large for EDIT v1 (64 KiB limit)' }; return { ok:true }; }
  function isEditorDirty(original, current){ return original !== current; }
  function writeFileContent(node, content, modifiedAt=new Date().toISOString()){ if(!node || node.type!=='file' || typeof content!=='string') return false; node.content=content; node.modifiedAt=modifiedAt; return true; }
  function walk(node, visit, seen=new Set()){ if(!node || seen.has(node)) return; seen.add(node); visit(node); if(node.type==='directory') Object.values(node.children).forEach(child=>walk(child, visit, seen)); }
  function stats(fs){ let files=0, dirs=0, used=0; walk(fs, n=>{ if(n.type==='directory') dirs++; else { files++; used+=bytes(n.content); } }); return {files, dirs, used, free:Math.max(0, DISK_CAPACITY-used)}; }
  function fmtDate(d=new Date()){ return `${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}-${d.getFullYear()}`; }
  function fmtTime(d=new Date()){ return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`; }
  function renderPromptFormat(state){ return state.promptFormat.slice(0,80).replace(/\$\$/g,'\0').replace(/\$P/gi,canonical(state.cwd)).replace(/\$G/gi,'>').replace(/\$D/gi,fmtDate()).replace(/\$T/gi,fmtTime()).replace(/\$_/gi,'\n').replace(/\0/g,'$'); }
  const api = { STORAGE_KEY, EDIT_MAX_BYTES, defaultState, validateState, normalizePath, lookup, stats, renderPromptFormat, splitCommand, bytes, isPlainText, canEditNode, isEditorDirty, writeFileContent, saveState };
  if(typeof module!=='undefined') module.exports = api;
  if(typeof document==='undefined') return;
  const shell=document.querySelector('.pcxt-shell'), start=document.getElementById('pcxtStart'), term=document.getElementById('pcxtTerminal'), input=document.getElementById('pcxtInput'), stage=document.querySelector('.pcxt-stage');
  let state=loadState(), current='', cursor=0, history=[], hist=-1, active=false, lines=0;
  const editor={ active:false, path:'', node:null, original:'', wrap:null, textarea:null, status:null, dirty:null };
  function setBeforeUnload(enabled){ window.onbeforeunload = enabled ? (e=>{ e.preventDefault(); e.returnValue=''; return ''; }) : null; }
  function updateEditorDirtyState(message){ if(!editor.active) return; const dirty=isEditorDirty(editor.original, editor.textarea.value); editor.dirty.textContent=dirty?'Unsaved changes':'Saved'; editor.dirty.classList.toggle('is-dirty',dirty); if(message) editor.status.textContent=message; setBeforeUnload(dirty); }
  function closeEditor(discard=false){ if(!editor.active) return; if(!discard && isEditorDirty(editor.original, editor.textarea.value) && !confirm('Discard unsaved changes to '+editor.path+'?')){ editor.textarea.focus(); return; } setBeforeUnload(false); editor.wrap.remove(); Object.assign(editor,{ active:false, path:'', node:null, original:'', wrap:null, textarea:null, status:null, dirty:null }); term.hidden=false; input.disabled=false; focus(); }
  function saveEditor(){ if(!editor.active) return; const content=editor.textarea.value; if(bytes(content)>EDIT_MAX_BYTES){ updateEditorDirtyState('File too large for EDIT v1 (64 KiB limit). Not saved.'); return; } if(!writeFileContent(editor.node, content)){ updateEditorDirtyState('File type not supported by EDIT'); return; } persist(); editor.original=content; updateEditorDirtyState('Saved '+editor.path); }
  function openEditor(args){ if(!args.trim()) return out('Usage: EDIT <filename>'); const r=resolve(args); const check=canEditNode(r.node); if(!check.ok) return out(check.reason); term.hidden=true; input.disabled=true; const wrap=document.createElement('section'); wrap.className='pcxt-editor'; wrap.setAttribute('aria-label','PC XT Text Editor v1'); wrap.innerHTML='<header class="pcxt-editor-header"><div><strong>PC XT Text Editor v1</strong><span></span></div><b>Saved</b></header><p class="pcxt-editor-workflow">Press Esc to return to the DOS prompt before using COMPUTER MUSEUM.</p><label class="pcxt-editor-label" for="pcxtEditorText">File text</label><textarea id="pcxtEditorText" spellcheck="false" wrap="off"></textarea><footer><span class="pcxt-editor-help"><span>CTRL+S Save</span><span class="pcxt-editor-exit">ESC Exit Editor</span></span><output aria-live="polite">Ready</output><div><button type="button">SAVE</button><button type="button">EXIT</button></div></footer>'; stage.insertBefore(wrap, term); editor.active=true; editor.path=r.path; editor.node=r.node; editor.original=r.node.content; editor.wrap=wrap; editor.textarea=wrap.querySelector('textarea'); editor.status=wrap.querySelector('output'); editor.dirty=wrap.querySelector('b'); wrap.querySelector('span').textContent=r.path; editor.textarea.value=r.node.content; editor.textarea.addEventListener('input',()=>updateEditorDirtyState()); editor.textarea.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey) && e.key.toLowerCase()==='s'){ e.preventDefault(); saveEditor(); } else if(e.key==='Escape'){ e.preventDefault(); closeEditor(); } }); const buttons=wrap.querySelectorAll('button'); buttons[0].addEventListener('click',saveEditor); buttons[1].addEventListener('click',()=>closeEditor()); updateEditorDirtyState('Ready'); editor.textarea.focus(); }
  function append(text=''){ term.appendChild(document.createTextNode(String(text)+'\n')); lines += String(text).split('\n').length; while(lines>MAX_RENDERED_LINES && term.firstChild){ term.removeChild(term.firstChild); lines--; } scroll(); }
  function clear(){ term.textContent=''; lines=0; }
  function scroll(){ term.scrollTop=term.scrollHeight; }
  function live(){ return document.getElementById('pcxtLivePrompt'); }
  function drawPrompt(){ const old=live(); if(old) old.remove(); const span=document.createElement('span'); span.id='pcxtLivePrompt'; const before=current.slice(0,cursor), at=current[cursor]||' ', after=current.slice(cursor+(current[cursor]?1:0)); span.append(document.createTextNode(renderPromptFormat(state)+before)); const c=document.createElement('span'); c.className='pcxt-cursor'; c.textContent=at; span.append(c, document.createTextNode(after)); term.appendChild(span); scroll(); }
  function redraw(){ const l=live(); if(l) l.remove(); drawPrompt(); }
  function focus(){ if(active) input.focus({preventScroll:true}); }
  function persist(){ saveState(state); }
  function out(s=''){ append(s); }
  function resolve(args){ const p=normalizePath(args,state.cwd); return { parts:p.parts, node:lookup(state.filesystem,p.parts), path:canonical(p.parts) }; }
  function pad(s,n){ return String(s).padStart(n); }
  const commands = new Map();
  function reg(name, aliases, syntax, desc, fn){ const c={name,aliases,syntax,desc,fn}; [name,...aliases].forEach(a=>commands.set(a,c)); }
  reg('DIR',[],'DIR [path]','List actual virtual directory contents.',args=>{ const r=resolve(args); if(!r.node) return out('Directory not found'); if(r.node.type!=='directory') return out('Path is not a directory'); out(' Directory of '+r.path); out(''); let fc=0, dc=0, total=0; Object.keys(r.node.children).sort().forEach(k=>{ const n=r.node.children[k]; if(n.type==='directory'){dc++; out(`${k.padEnd(12)} <DIR>`);} else {fc++; const size=bytes(n.content); total+=size; out(`${k.padEnd(12)} ${pad(size,8)} bytes`);} }); out(''); out(`${pad(fc,4)} file(s) ${total} bytes`); out(`${pad(dc,4)} dir(s)  ${stats(state.filesystem).free} bytes free`); });
  reg('CD',['CHDIR'],'CD [path]','Show or change the current directory.',args=>{ if(!args.trim()) return out(canonical(state.cwd)); const target=args.toUpperCase().startsWith('CD\\')?args.slice(2):args; const r=resolve(target); if(!r.node) return out('Directory not found'); if(r.node.type!=='directory') return out('Path is not a directory'); state.cwd=r.parts; persist(); });
  reg('TYPE',[],'TYPE file','Display a stored text file.',args=>{ const r=resolve(args); if(!r.node) return out('File not found'); if(r.node.type==='directory') return out('Access not applicable to a directory'); out(r.node.content.replace(/\n$/,'')); });
  reg('TREE',[],'TREE [path]','Display a recursive tree from the actual filesystem.',args=>{ const r=resolve(args); if(!r.node) return out('Directory not found'); if(r.node.type!=='directory') return out('Path is not a directory'); out(r.path); const seen=new Set(); function rec(n,prefix){ if(seen.has(n)) return out(prefix+'[cycle skipped]'); seen.add(n); Object.keys(n.children).sort().forEach((k,i,a)=>{ const last=i===a.length-1, child=n.children[k]; out(prefix+(last?'└── ':'├── ')+k); if(child.type==='directory') rec(child,prefix+(last?'    ':'│   ')); }); } rec(r.node,''); });
  reg('CLS',[],'CLS','Clear the terminal display.',()=>{ clear(); });
  reg('EDIT',[],'EDIT <file>','Open an existing text file in the PC XT text editor.',openEditor);
  reg('HELP',[],'HELP [command]','Show command help.',args=>{ const key=firstArg(args).toUpperCase(); const c=commands.get(key); if(c) return out(`${c.name}\nSyntax: ${c.syntax}\n${c.desc}${c.name==='MEM'?'\nNote: MEM uses a simulated educational memory model.':''}${c.name==='EDIT'?'\nExisting plain-text files only. Ctrl+S saves. Esc exits. Unsaved changes require confirmation.':''}`); out('PC XT Command Desk commands:\n'); [...new Set(commands.values())].sort((a,b)=>a.name.localeCompare(b.name)).forEach(c=>out(`${c.syntax.padEnd(18)} ${c.desc}`)); out('\nFuture file maintenance commands such as COPY, DEL and REN are not available in Version 1.0.'); });
  reg('VER',[],'VER','Show environment identity.',()=>out('PC XT Command Desk\nEducational DOS Environment\nVersion 1.0\nCopyright (C) Dennis Hilk'));
  reg('DATE',[],'DATE','Show local browser date without changing it.',()=>out('Current local date: '+fmtDate()+' (informational only)'));
  reg('TIME',[],'TIME','Show local browser time without changing it.',()=>out('Current local time: '+fmtTime()+' (informational only)'));
  reg('MEM',[],'MEM','Show simulated memory information.',()=>{ const envUse=Math.ceil(JSON.stringify(state.environment).length/32), rows=[['Conventional',640,176+envUse],['Upper',96,38],['Extended',8192,1024]]; out('Memory Type        Total       Used       Free'); out('----------------  --------   --------   --------'); rows.forEach(r=>out(`${r[0].padEnd(16)} ${pad(r[1]+'K',8)}   ${pad(r[2]+'K',8)}   ${pad((r[1]-r[2])+'K',8)}`)); out('\nLargest executable program size: '+(rows[0][1]-rows[0][2])+'K'); out('Simulated educational memory model; no real hardware is inspected.'); });
  reg('CHKDSK',[],'CHKDSK','Inspect the virtual filesystem.',()=>{ const s=stats(state.filesystem); out('PC XT virtual disk status'); out(`${s.dirs} directorie(s)`); out(`${s.files} file(s)`); out(`${s.used} stored text byte(s)`); out(`${DISK_CAPACITY} byte simulated capacity`); out(`${s.free} byte(s) free`); out('Local filesystem status: browser-local data only'); });
  reg('PATH',[],'PATH [value]','Show or set executable search path.',args=>{ if(!args.trim()) return out('PATH='+state.path); state.path=args.trim().slice(0,240); persist(); out('PATH='+state.path); });
  reg('SET',[],'SET [NAME=value]','Show, assign or remove environment variables.',args=>{ if(!args.trim()){ Object.keys(state.environment).sort().forEach(k=>out(`${k}=${state.environment[k]}`)); return; } const i=args.indexOf('='); if(i<1) return out('Invalid syntax'); const name=args.slice(0,i).trim().toUpperCase(); if(!/^[A-Z][A-Z0-9_]{0,30}$/.test(name)) return out('Invalid environment variable name'); const val=args.slice(i+1).slice(0,240); if(val==='') delete state.environment[name]; else state.environment[name]=val; persist(); });
  reg('PROMPT',[],'PROMPT [format]','Show or set prompt using $P $G $D $T $$ $_.',args=>{ if(!args.trim()) return out('PROMPT='+state.promptFormat); state.promptFormat=args.slice(0,80); persist(); });
  reg('ECHO',[],'ECHO [text|ON|OFF|.]','Display text or set simulated echo state.',args=>{ const a=args.trim(); if(!a) return out(state.echo?'ECHO is on':'ECHO is off'); if(a.toUpperCase()==='ON'){state.echo=true; persist(); return;} if(a.toUpperCase()==='OFF'){state.echo=false; persist(); return;} if(a==='.') return out(''); out(args); });
  reg('RESET',[],'RESET','Confirm and restore only PC XT browser-local data.',()=>{ if(confirm('Reset PC XT Command Desk? This will delete only browser-local PC XT changes stored under '+STORAGE_KEY+'. It will not clear BASIC or other site storage.')){ localStorage.removeItem(STORAGE_KEY); state=defaultState(); clear(); BOOT.forEach(out); out('PC XT Command Desk reset complete.'); } else out('Reset cancelled.'); });
  const deferred = new Set('MD MKDIR RD RMDIR COPY DEL ERASE REN RENAME ATTRIB'.split(' '));
  function run(line){ if(editor.active) return; const shown=renderPromptFormat(state)+line; append(shown); const {command,args}=splitCommand(line); if(!command) return drawPrompt(); const c=commands.get(command); if(c) c.fn(args); else if(deferred.has(command)) out('Command not available in PC XT Command Desk Version 1.0'); else out('Bad command or file name'); drawPrompt(); }
  function enter(){ const line=current; if(line.trim()) { history.push(line); hist=history.length; } current=''; cursor=0; const l=live(); if(l)l.remove(); run(line); persist(); }
  function startTerminal(){ active=true; shell.classList.add('is-terminal-active'); clear(); BOOT.forEach(out); drawPrompt(); focus(); }
  start.addEventListener('click',startTerminal); term.addEventListener('click',focus); input.addEventListener('input',()=>{ if(editor.active){ input.value=''; return; } current=current.slice(0,cursor)+input.value+current.slice(cursor); cursor+=input.value.length; input.value=''; redraw(); }); input.addEventListener('keydown',e=>{ if(editor.active) return; if(e.ctrlKey||e.metaKey||e.altKey) return; if(e.key==='Enter'){e.preventDefault(); enter();} else if(e.key==='Backspace'){e.preventDefault(); if(cursor>0){current=current.slice(0,cursor-1)+current.slice(cursor); cursor--; redraw();}} else if(e.key==='Delete'){e.preventDefault(); current=current.slice(0,cursor)+current.slice(cursor+1); redraw();} else if(e.key==='ArrowLeft'){e.preventDefault(); cursor=Math.max(0,cursor-1); redraw();} else if(e.key==='ArrowRight'){e.preventDefault(); cursor=Math.min(current.length,cursor+1); redraw();} else if(e.key==='Home'){e.preventDefault(); cursor=0; redraw();} else if(e.key==='End'){e.preventDefault(); cursor=current.length; redraw();} else if(e.key==='ArrowUp'){e.preventDefault(); if(history.length){ hist=Math.max(0,hist-1); current=history[hist]||''; cursor=current.length; redraw(); }} else if(e.key==='ArrowDown'){e.preventDefault(); if(history.length){ hist=Math.min(history.length,hist+1); current=history[hist]||''; cursor=current.length; redraw(); }} });
})();
