(()=>{const {Enigma,alphabet}=window.EnigmaCore, q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];const layout=['QWERTZUIO','ASDFGHJK','PYXCVBNML'];let machine=new Enigma(), input='',output='',chosen=null,busy=false,sound=false,ctx;
const rotors=q('#rotors'), lamps=q('#lamps'), keys=q('#keys'), plugs=q('#plugs');function optionHtml(){return ['I','II','III','IV','V'].map(x=>`<option>${x}</option>`).join('')}
function build(){rotors.innerHTML=[0,1,2].map(i=>`<div class="rotor"><b>${['LEFT','MIDDLE','RIGHT'][i]} · <span id="rt${i}">${machine.order[i]}</span></b><div class="wheel"><button data-rot="${i}" data-d="-1" aria-label="Turn ${i+1} rotor backward">‹</button><output id="pos${i}">A</output><button data-rot="${i}" data-d="1" aria-label="Turn ${i+1} rotor forward">›</button></div><small>RING 01</small></div>`).join('');layout.flatMap(x=>[...x]).forEach(c=>{lamps.insertAdjacentHTML('beforeend',`<output class="lamp" data-letter="${c}" aria-label="Lamp ${c}">${c}</output>`);keys.insertAdjacentHTML('beforeend',`<button class="enigma-key" data-letter="${c}" aria-label="Encode ${c}">${c}</button>`);plugs.insertAdjacentHTML('beforeend',`<button class="socket" data-letter="${c}" aria-pressed="false" aria-label="Plugboard socket ${c}">${c}</button>`)});qa('.enigma-settings select[data-slot]').forEach((s,i)=>{s.innerHTML=optionHtml();s.value=machine.order[i]});render()}
function render(){machine.rotors.forEach((r,i)=>{q('#pos'+i).textContent=alphabet[r.pos];q('#rt'+i).textContent=r.name});q('#plug-status').textContent=`${machine.pairs.length} / 10 PAIRS`;qa('.socket').forEach(x=>{let l=x.dataset.letter;x.classList.toggle('paired',machine.pairs.some(p=>p.includes(l)));x.classList.toggle('selected',l===chosen)})}
function tone(f,d=.035){if(!sound)return;ctx||=new AudioContext();let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g).connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.stop(ctx.currentTime+d)}
function format(s){return s.replace(/(.{5})/g,'$1 ').trim()||'—'}function encode(letter){if(busy)return;busy=true;let k=q(`.enigma-key[data-letter="${letter}"]`);k.classList.add('down');tone(105);let r=machine.encipher(letter);input+=letter;output+=r.output;render();q('#input').textContent=format(input);q('#output').textContent=format(output);q('#result').textContent=`${letter} → ${r.output}`;let lamp=q(`.lamp[data-letter="${r.output}"]`);lamp.classList.add('lit');if(q('#path-panel').hidden===false)showPath(r);if(r.stepped.double)q('#step-note').textContent='DOUBLE STEP';setTimeout(()=>{k.classList.remove('down');lamp.classList.remove('lit');busy=false},180);}
function showPath(r){q('#path-list').innerHTML=['KEY '+r.input,...r.route.map(x=>`${x.stage.toUpperCase()} · ${x.letter}`),'LAMP '+r.output].map((x,i)=>`<li style="animation-delay:${i*35}ms">${x}</li>`).join('')}
keys.addEventListener('click',e=>{let l=e.target.dataset.letter;if(l)encode(l)});document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|TEXTAREA|SELECT|BUTTON/.test(document.activeElement.tagName))return;let l=e.key.toUpperCase();if(alphabet.includes(l)){e.preventDefault();encode(l)}});rotors.addEventListener('click',e=>{let b=e.target.closest('[data-rot]');if(!b)return;let r=machine.rotors[b.dataset.rot];r.pos=(r.pos+26+Number(b.dataset.d))%26;machine.starts[b.dataset.rot]=r.pos;tone(80);render()});plugs.addEventListener('click',e=>{let b=e.target.closest('.socket');if(!b)return;let l=b.dataset.letter;if(machine.pairs.some(p=>p.includes(l))){machine.setPlugboard(machine.pairs.filter(p=>!p.includes(l)));chosen=null}else if(!chosen)chosen=l;else if(chosen!==l){try{machine.setPlugboard([...machine.pairs,chosen+l])}catch(err){q('#plug-status').textContent=err.message}chosen=null}render()});
q('#clear-plugs').onclick=()=>{machine.setPlugboard([]);chosen=null;render()};q('#clear').onclick=()=>{input=output='';q('#input').textContent=q('#output').textContent='—'};q('#reset').onclick=()=>{machine.reset();render();q('#result').textContent='RESET'};q('#settings-toggle').onclick=()=>q('#settings').hidden=!q('#settings').hidden;q('#reflector').onchange=e=>machine.reflector=e.target.value;q('#rings').onchange=e=>{machine.rings=[Number(e.target.value),Number(e.target.value),Number(e.target.value)];machine.reset();render()};qa('.enigma-settings select[data-slot]').forEach(s=>s.onchange=e=>{machine.order[e.target.dataset.slot]=e.target.value;machine.reset();build()});qa('.mode button').forEach(b=>b.onclick=()=>{qa('.mode button').forEach(x=>x.classList.toggle('active',x===b));q('#path-panel').hidden=b.dataset.mode!=='path'});q('#sound').onclick=e=>{sound=!sound;e.target.textContent=sound?'SOUND ON':'SOUND OFF';e.target.setAttribute('aria-pressed',sound);if(sound){ctx||=new AudioContext();ctx.resume();tone(190)}};q('#demo').onclick=()=>{q('#result').textContent='TYPE HELLO, NOTE OUTPUT, RESET, THEN TYPE IT BACK.'};build()})();
