(function(root,factory){const api=factory();if(typeof module!=='undefined')module.exports=api;root.ExchangeCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const NUMBERS=['201','204','214','225','301','318','381','402','417','503','537','612'];
function fresh(){return {subscribers:Object.fromEntries(NUMBERS.map(n=>[n,{state:'IDLE',busy:false}])),trunks:{'TRUNK 01':'IDLE','TRUNK 02':'IDLE','TRUNK 03':'IDLE'},cords:['A','B','C'].map(id=>({id,answer:null,calling:null,state:'IDLE'})),mission:0,step:'READY',message:'SYSTEM READY — BEGIN TRAINING.',completed:0};}
function cord(s,id){return s.cords.find(c=>c.id===id)} function target(s,x){return s.subscribers[x]||null}
function incoming(s,n){if(!target(s,n)||target(s,n).busy)return false;target(s,n).state='CALLING';return true}
function plug(s,id,side,to){const c=cord(s,id), t=target(s,to);if(!c)return false;if(side==='answer'){if(!t||t.state!=='CALLING'||c.answer)return fail(s,'NOT YET — ANSWER A CALLING SUBSCRIBER FIRST.');c.answer=to;c.state='ANSWERED';t.state='ANSWERED';return true}if(side==='calling'){if(!c.answer)return fail(s,'NOT YET — ANSWER THE CALLER FIRST.');if(c.calling)return false;if(to.startsWith('TRUNK')){if(s.trunks[to]!=='IDLE')return fail(s,'TRUNK IS BUSY.');c.calling=to;c.state='DESTINATION';s.trunks[to]='SEIZED';return true}if(!t||t.busy||t.state==='CONNECTED')return fail(s,'LINE '+to+' IS BUSY.');if(to===c.answer)return fail(s,'SELECT A DIFFERENT DESTINATION.');c.calling=to;c.state='DESTINATION';t.state='RINGING';return true}return false}
function ring(s,id){const c=cord(s,id);if(!c||!c.answer||!c.calling||c.state!=='DESTINATION')return fail(s,'RINGING REQUIRES A VALID DESTINATION.');c.state='RINGING';if(s.subscribers[c.calling])s.subscribers[c.calling].state='RINGING';return true}
function answer(s,id){const c=cord(s,id);if(!c||c.state!=='RINGING')return false;c.state='CONNECTED';s.subscribers[c.answer].state='CONNECTED';s.subscribers[c.answer].busy=true;if(s.subscribers[c.calling]){s.subscribers[c.calling].state='CONNECTED';s.subscribers[c.calling].busy=true}else s.trunks[c.calling]='CONNECTED';return true}
function disconnect(s,id){const c=cord(s,id);if(!c||c.state!=='CONNECTED')return false;c.state='DISCONNECT';if(s.subscribers[c.answer])s.subscribers[c.answer].state='DISCONNECT';if(s.subscribers[c.calling])s.subscribers[c.calling].state='DISCONNECT';return true}
function clear(s,id){const c=cord(s,id);if(!c)return false;[c.answer,c.calling].forEach(x=>{if(s.subscribers[x])Object.assign(s.subscribers[x],{state:'IDLE',busy:false});if(s.trunks[x])s.trunks[x]='IDLE'});Object.assign(c,{answer:null,calling:null,state:'IDLE'});return true}
function fail(s,msg){s.message=msg;return false} function reset(s){Object.assign(s,fresh());return s}
return {NUMBERS,fresh,incoming,plug,ring,answer,disconnect,clear,reset};});
