(function(){
const C=window.ExchangeCore;let s=C.fresh(),timer=null;
const names={201:'MUSEUM OFFICE',204:'LIBRARY',214:'WORKSHOP',225:'RAIL STATION',301:'HOTEL',318:'OBSERVATORY',381:'ARCHIVE',402:'PRINT ROOM',417:'STUDIO',503:'DEPOT',537:'READING ROOM',612:'LABORATORY'};
const $=x=>document.querySelector(x),guided=()=>s.mission===1&&C.guide(s),hot=x=>guided()&&C.guide(s).highlight.includes(x)?' guide-target':'';
let audio;
function audioContext(){try{if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;const ctx=new A(),master=ctx.createGain(),limiter=ctx.createDynamicsCompressor();master.gain.value=.78;limiter.threshold.value=-10;limiter.knee.value=8;limiter.ratio.value=12;master.connect(limiter).connect(ctx.destination);audio={ctx,master};}if(audio.ctx.state==='suspended')audio.ctx.resume();return audio}catch(_){return null}}
function tone(a,frequency,duration,gain,type,when=0,slide){const o=a.ctx.createOscillator(),g=a.ctx.createGain(),t=a.ctx.currentTime+when;o.type=type;o.frequency.setValueAtTime(frequency,t);if(slide)o.frequency.exponentialRampToValueAtTime(slide,t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(a.master);o.start(t);o.stop(t+duration+.02)}
function noise(a,duration,gain,when=0){const b=a.ctx.createBuffer(1,Math.ceil(a.ctx.sampleRate*duration),a.ctx.sampleRate),d=b.getChannelData(0),src=a.ctx.createBufferSource(),g=a.ctx.createGain(),t=a.ctx.currentTime+when;for(let i=0;i<d.length;i++)d[i]=(i%7-3)/3*Math.exp(-i/d.length*7);src.buffer=b;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(g).connect(a.master);src.start(t)}
function sound(kind){const a=audioContext();if(!a)return;const v=kind==='insert'?1.03:.76;if(kind==='insert'){noise(a,.035,.26*v);tone(a,105,.075,.23*v,'triangle',0,72);tone(a,1740,.018,.1*v,'square',.004,980)}else if(kind==='remove'){noise(a,.022,.17*v);tone(a,220,.04,.13*v,'triangle',0,145)}else if(kind==='relay'){noise(a,.012,.13*v);tone(a,840,.025,.09*v,'square',0,470)}else if(kind==='clear'){noise(a,.04,.24*v);tone(a,150,.075,.2*v,'triangle',0,82);tone(a,620,.025,.08*v,'square',.012,370)}else if(kind==='ring'){[0,.42].forEach(t=>{tone(a,440,.12,.14*v,'sine',t,410);tone(a,480,.12,.11*v,'sine',t,452);noise(a,.018,.08*v,t+.01)})}}
function render(){const g=guided();const bank=$('#subscriberBank');bank.innerHTML=C.NUMBERS.map(n=>`<button class="station ${s.subscribers[n].state.toLowerCase()}${hot('jack:'+n)}" data-jack="${n}" aria-label="Jack ${n}, ${s.subscribers[n].state}"><i></i><strong>${n}</strong><small>${names[n]} · ${s.subscribers[n].state}</small><b class="jack">●</b></button>`).join('');$('#cords').innerHTML=s.cords.map(c=>`<div class="cord ${c.state.toLowerCase()}"><button data-plug="${c.id}:answer" class="plug${hot('plug:'+c.id+':answer')}">ANSWER<br>${c.id}</button><span class="wire">${c.answer||'—'} ━━━━━ ${c.calling||'—'}</span><button data-plug="${c.id}:calling" class="plug${hot('plug:'+c.id+':calling')}">CALL<br>${c.id}</button><button class="ring${hot('ring:'+c.id)}" data-ring="${c.id}">RING</button><button class="clear${hot('clear:'+c.id)}" data-clear="${c.id}">CLEAR</button><small>${c.state}</small></div>`).join('');$('#trunks').innerHTML=Object.entries(s.trunks).map(([n,v])=>`<button data-jack="${n}" class="trunk ${v.toLowerCase()}">${n}<small>${v}</small></button>`).join('');$('#message').textContent=g?g.instruction:s.message;$('#mission').textContent=g?`MISSION 01 — FIRST CONNECTION\n${g.step}\n\n${g.detail}\n\n${g.instruction}`:'GUIDED OPERATOR TRAINING\n\nBEGIN TRAINING to learn one complete cord-switchboard connection.';$('#stats').textContent=`WAITING ${Object.values(s.subscribers).filter(x=>x.state==='CALLING').length} · ACTIVE ${s.cords.filter(c=>c.state==='CONNECTED').length}`}
function begin(){clearTimeout(timer);C.guidedStart(s);sound('relay');render()}
document.addEventListener('click',e=>{const p=e.target.closest('[data-plug]'),j=e.target.closest('[data-jack]'),r=e.target.closest('[data-ring]'),cl=e.target.closest('[data-clear]');if(e.target.id==='begin')return begin();if(e.target.id==='reset'){clearTimeout(timer);C.reset(s);return render()}if(!s.mission)return;if(p){if(C.guidedSelect(s,p.dataset.plug)){sound('relay');render()}return}if(j){const [id,side]=s.step==='ANSWER_JACK'?['A','answer']:s.step==='DESTINATION_JACK'?['A','calling']:[];if(id&&C.guidedPlug(s,id,side,j.dataset.jack)){sound('insert');render()}return}if(r&&C.guidedRing(s,r.dataset.ring)){sound('ring');render();clearTimeout(timer);timer=setTimeout(()=>{if(C.guidedConnected(s,r.dataset.ring)){sound('relay');render();timer=setTimeout(()=>{if(C.guidedDisconnect(s,r.dataset.ring)){sound('relay');render()}},2400)}},900);return}if(cl&&C.guidedClear(s,cl.dataset.clear)){sound('clear');render()}});render();
})();
