(function(){
const C=window.ExchangeCore;let s=C.fresh(),timer=null,selected=null;
const names={201:'MUSEUM OFFICE',204:'LIBRARY',214:'WORKSHOP',225:'RAIL STATION',301:'HOTEL',318:'OBSERVATORY',381:'ARCHIVE',402:'PRINT ROOM',417:'STUDIO',503:'DEPOT',537:'READING ROOM',612:'LABORATORY'};
const $=x=>document.querySelector(x),guided=()=>s.mission===1&&C.guide(s),hot=x=>guided()&&C.guide(s).highlight.includes(x)?' guide-target':'',stateClass=x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
let audio;function audioContext(){try{if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;const ctx=new A(),master=ctx.createGain(),limiter=ctx.createDynamicsCompressor();master.gain.value=.78;limiter.threshold.value=-10;limiter.knee.value=8;limiter.ratio.value=12;master.connect(limiter).connect(ctx.destination);audio={ctx,master};}if(audio.ctx.state==='suspended')audio.ctx.resume();return audio}catch(_){return null}}
function tone(a,f,d,g,type,w=0,slide){const o=a.ctx.createOscillator(),v=a.ctx.createGain(),t=a.ctx.currentTime+w;o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(slide,t+d);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.004);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v).connect(a.master);o.start(t);o.stop(t+d+.02)}function noise(a,d,g,w=0){const b=a.ctx.createBuffer(1,Math.ceil(a.ctx.sampleRate*d),a.ctx.sampleRate),x=b.getChannelData(0),q=a.ctx.createBufferSource(),v=a.ctx.createGain(),t=a.ctx.currentTime+w;for(let i=0;i<x.length;i++)x[i]=(i%7-3)/3*Math.exp(-i/x.length*7);q.buffer=b;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);q.connect(v).connect(a.master);q.start(t)}function sound(k){const a=audioContext();if(!a)return;if(k==='lift'){noise(a,.018,.11);tone(a,260,.035,.1,'triangle',0,180)}else if(k==='insert'){noise(a,.035,.26);tone(a,105,.075,.23,'triangle',0,72)}else if(k==='clear'){noise(a,.03,.2);tone(a,150,.07,.18,'triangle',0,82);noise(a,.03,.18,.09)}else if(k==='relay'){noise(a,.012,.13);tone(a,840,.025,.09,'square',0,470)}else if(k==='ring'){[0,.42].forEach(t=>{tone(a,440,.12,.14,'sine',t,410);tone(a,480,.12,.11,'sine',t,452)})}}
function render(){const g=guided(),bank=$('#subscriberBank');bank.innerHTML=C.NUMBERS.map(n=>`<button class="station ${stateClass(s.subscribers[n].state)}${hot('jack:'+n)}" data-jack="${n}" data-subscriber-state="${s.subscribers[n].state}" aria-label="Insert selected plug into jack ${n}; ${s.subscribers[n].state}"><i></i><strong>${n}</strong><small>${names[n]} · ${s.subscribers[n].state}</small><b class="jack" aria-hidden="true">●</b></button>`).join('');$('#cords').innerHTML=s.cords.map(c=>`<div class="cord ${stateClass(c.state)}"><button data-plug="${c.id}:answer" class="plug${selected===c.id+':answer'?' selected':''}${c.answer?' seated':''}${hot('plug:'+c.id+':answer')}" aria-pressed="${selected===c.id+':answer'}">ANSWER<br>${c.id}</button><span class="wire">${c.answer||'REST'} · CORD ${c.id} · ${c.calling||'REST'}</span><button data-plug="${c.id}:calling" class="plug${selected===c.id+':calling'?' selected':''}${c.calling?' seated':''}${hot('plug:'+c.id+':calling')}" aria-pressed="${selected===c.id+':calling'}">CALL<br>${c.id}</button><button class="ring${hot('ring:'+c.id)}" data-ring="${c.id}">RING</button><button class="clear${hot('clear:'+c.id)}" data-clear="${c.id}">CLEAR</button><small>${c.state}</small></div>`).join('');$('#trunks').innerHTML=Object.entries(s.trunks).map(([n,v])=>`<button data-jack="${n}" class="trunk ${v.toLowerCase()}">${n}<small>${v}</small></button>`).join('');$('#message').textContent=g?g.instruction:s.message;$('#mission').textContent=g?`MISSION 01 — FIRST CONNECTION\n${g.step}\n\n${g.detail}\n\n${g.instruction}`:'GUIDED OPERATOR TRAINING\n\nBEGIN TRAINING to learn one complete cord-switchboard connection.';$('#stats').textContent=`WAITING ${Object.values(s.subscribers).filter(x=>x.state==='CALLING').length} · ACTIVE ${s.cords.filter(c=>c.state==='CONNECTED').length}`;requestAnimationFrame(drawCords)}
function drawCords(){const svg=$('#cordLayer'),board=$('.board');if(!svg||!board)return;const box=board.getBoundingClientRect(),point=el=>{const r=el.getBoundingClientRect();return {x:r.left+r.width/2-box.left,y:r.top+r.height/2-box.top}};svg.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);svg.innerHTML='';s.cords.forEach(c=>[['answer',c.answer],['calling',c.calling]].forEach(([side,destination])=>{if(!destination)return;const from=point(document.querySelector(`[data-plug="${c.id}:${side}"]`)),to=point(document.querySelector(`[data-jack="${destination}"]`));const bend=Math.max(50,Math.abs(to.x-from.x)*.28),d=`M ${from.x} ${from.y} C ${from.x+(to.x>from.x?bend:-bend)} ${from.y}, ${to.x-(to.x>from.x?bend:-bend)} ${to.y}, ${to.x} ${to.y}`;svg.insertAdjacentHTML('beforeend',`<path class="cord-path" d="${d}"/><path class="cord-path highlight" d="${d}"/>`)}))}
function begin(){clearTimeout(timer);selected=null;C.guidedStart(s);sound('relay');render()}function selectPlug(value){const [id,side]=value.split(':');if(s.mission&& !C.guidedSelect(s,'plug:'+value))return;selected=value;sound('lift');render()}function insertJack(destination){if(!selected)return;const [id,side]=selected.split(':');const ok=s.mission?C.guidedPlug(s,id,side,destination):C.plug(s,id,side,destination);if(ok){selected=null;sound('insert');if(side==='answer')sound('relay');render()}}
function activate(e){const p=e.target.closest('[data-plug]'),j=e.target.closest('[data-jack]'),r=e.target.closest('[data-ring]'),cl=e.target.closest('[data-clear]');if(e.target.id==='begin')return begin();if(e.target.id==='reset'){clearTimeout(timer);selected=null;C.reset(s);return render()}if(p)return selectPlug(p.dataset.plug);if(j)return insertJack(j.dataset.jack);if(r&&(!s.mission||C.guidedRing(s,r.dataset.ring))){if(!s.mission)C.ring(s,r.dataset.ring);sound('ring');render();if(s.mission){clearTimeout(timer);timer=setTimeout(()=>{if(C.guidedConnected(s,r.dataset.ring)){sound('relay');render();timer=setTimeout(()=>{if(C.guidedDisconnect(s,r.dataset.ring)){sound('relay');render()}},2400)}},900)}return}if(cl){const ok=s.mission?C.guidedClear(s,cl.dataset.clear):C.clear(s,cl.dataset.clear);if(ok){selected=null;sound('clear');render()}}}
document.addEventListener('click',activate);
// A drag is an optional desktop shortcut; click/tap remains the primary, accessible path.
document.addEventListener('pointerdown',e=>{const p=e.target.closest('[data-plug]');if(p&&e.pointerType!=='touch'){selectPlug(p.dataset.plug);e.preventDefault()}});
document.addEventListener('pointerup',e=>{if(!selected||e.pointerType==='touch')return;const j=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-jack]');if(j)insertJack(j.dataset.jack)});
window.addEventListener('resize',drawCords);window.addEventListener('orientationchange',drawCords);window.ExchangeUI={activate,getState:()=>s,getSelected:()=>selected,begin,render};render();
})();
