document.addEventListener('DOMContentLoaded',()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],A=window.AESLab,D=window.DESLab;let dr=0,ds=D.encrypt('0123456789ABCDEF','133457799BBCDFF1',true),as=0,trace=A.encrypt(A.hex('00112233445566778899AABBCCDDEEFF'),A.hex('000102030405060708090A0B0C0D0E0F'),true),flip=0;
$$('.bit-cells[data-count]').forEach(x=>{for(let i=0;i<+x.dataset.count;i++){let b=document.createElement('i');b.textContent=i%2;b.className='bit';x.append(b)}});
function sound(f=420){try{let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.08);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch(e){}}
function show(id){$$('.daa-station').forEach(x=>x.hidden=x.id!==id);$$('.daa-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.s===id));}$$('.daa-tabs button').forEach(x=>x.onclick=()=>show(x.dataset.s));show('basics');
function des(){let x=dr?ds[dr-1]:{left:'L0',right:'R0'};$('#des-left').textContent=x.left;$('#des-right').textContent=x.right;$('#des-count').textContent=`ROUND ${String(dr).padStart(2,'0')} / 16`;$('#des-readout').textContent=dr?`Round ${dr}: F(R${dr-1}, K${dr}) is XORed with L${dr-1}; the halves swap.`:'Load the known DES vector 0123456789ABCDEF.';if(dr===16)$('#des-result').textContent=D.encrypt('0123456789ABCDEF','133457799BBCDFF1');}$('#des-step').onclick=()=>{dr=Math.min(16,dr+1);des();sound(180)};$('#des-run').onclick=()=>{dr=16;des();sound(240)};$('#des-reset').onclick=()=>{dr=0;des()};des();
function matrix(s){let box=$('#aes-state');box.replaceChildren(...[...s].map((x,i)=>{let b=document.createElement('button');b.textContent=x.toString(16).padStart(2,'0').toUpperCase();b.setAttribute('aria-label',`State byte ${i}: ${b.textContent}`);b.onclick=()=>$('#aes-byte').textContent=`INPUT BYTE ${b.textContent} → S-BOX → ${A.S[x].toString(16).padStart(2,'0').toUpperCase()}`;return b}));}function aes(){let x=as?trace[as-1]:{round:0,stage:'INITIAL STATE',state:A.hex('00112233445566778899AABBCCDDEEFF')};matrix(x.state);$('#aes-count').textContent=`ROUND ${String(x.round).padStart(2,'0')} / 10`;$('#aes-stage').textContent=`${x.stage} · Round ${x.round}${x.round===10?' — final round has no MixColumns.':''}`}$('#aes-step').onclick=()=>{as=Math.min(trace.length,as+1);aes();sound(520)};$('#aes-auto').onclick=()=>{as=trace.length;aes();sound(660)};$('#aes-reset').onclick=()=>{as=0;aes()};$('#aes-example').onclick=()=>{as=0;aes()};aes();
function time(){let n=2**56/+$('#rate').value;let f=x=>x>31557600?`${(x/31557600).toExponential(3)} years` : x>86400?`${(x/86400).toFixed(1)} days` : x>3600?`${(x/3600).toFixed(1)} hours`:`${x.toFixed(1)} seconds`;$('#key-time').textContent=`EXPECTED: ${f(n/2)} · FULL KEYSPACE: ${f(n)}`}$('#rate').onchange=time;time();
function avalanche(){let p=A.hex('00112233445566778899AABBCCDDEEFF'),k=A.hex('000102030405060708090A0B0C0D0E0F'),a=A.encrypt(p,k),q=p.slice();q[flip%128>>3]^=1<<(flip%8);let b=A.encrypt(q,k),bits=[];for(let i=0;i<16;i++)for(let n=7;n>=0;n--)bits.push(((a[i]>>n)&1)!==((b[i]>>n)&1));$('#distance').textContent=`HAMMING DISTANCE: ${bits.filter(Boolean).length} / 128 OUTPUT BITS CHANGED`;let x=$('#avalanche-bits');x.replaceChildren(...bits.map(v=>{let i=document.createElement('i');i.textContent=v?'×':'·';i.className='bit '+(v?'changed':'');return i}));}$('#flip').onclick=()=>{flip++;avalanche();sound(330)};avalanche();
let tour=0,st=['basics','des','des','wall','tdea','competition','aes','aes','compare'];$('#tour').onclick=()=>{tour=0;$('#tour-note').hidden=false;next()};function next(){let msgs=['Start with a fixed-size block: the block size and key size are different.','DES splits the block into left and right halves.','Step a Feistel round: the right side drives a function, then the halves exchange.','The 56-bit keyspace became searchable with specialized hardware.','Triple DES extended DES with EDE compatibility—not a final destination.','NIST selected Rijndael after an open evaluation.','AES works on a 4 × 4 byte state; step through its transformations.','Notice the final AES round omits MixColumns.','Flip a bit and compare the real AES ciphertexts.'];show(st[tour]);$('#tour-note').innerHTML=`<b>GUIDED TOUR ${tour+1} / ${msgs.length}</b><p>${msgs[tour]}</p><button>${tour+1===msgs.length?'FINISH':'NEXT →'}</button>`;$('#tour-note button').onclick=()=>{if(++tour<msgs.length)next();else $('#tour-note').hidden=true}}});
