(function () {
  const { VirtualSystem, Shell, defaultCommands } = window.LinuxAcademy;
  const $ = selector => document.querySelector(selector); const output = $('#terminalOutput'), input = $('#terminalInput'), prompt = $('#prompt'), tree = $('#tree'), context = $('#context'), mission = $('#missionList'), guidance = $('#guidance'), announcer = $('#announcer');
  const directoryNotes = { '/': 'Root of the active filesystem tree—not a drive letter or necessarily one physical disk.', '/bin': 'Essential command/program location in traditional Unix/Linux layouts; many modern distributions merge it into /usr.', '/etc': 'System-wide configuration.', '/home': 'User home directories.', '/home/museum': 'Your fictional Academy user home directory.', '/tmp': 'Temporary files.', '/var': 'Variable data such as logs, caches, queues, and application state.', '/var/log': 'System and application log location in many Linux systems.' };
  let system, shell, history, historyIndex, progress;
  const write = lines => { const block = document.createElement('pre'); block.className = 'terminal-text'; block.textContent = lines.join('\n'); output.append(block); };
  const promptText = () => `museum@linux:${system.cwd === system.homeDirectory ? '~' : system.cwd}$`;
  function renderTree() { tree.replaceChildren(); const visit = (node, path, depth) => { const line = document.createElement('div'); line.style.paddingLeft = `${depth * 1.05}em`; if (node.type === 'directory') { const button = document.createElement('button'); button.type = 'button'; button.textContent = `${path === '/' ? '/' : '├── ' + path.split('/').pop()}`; button.dataset.path = path; if (path === system.cwd) { button.className = 'current'; button.setAttribute('aria-current', 'location'); } line.append(button); } else line.textContent = `├── ${path.split('/').pop()}`; tree.append(line); if (node.type === 'directory') Object.keys(node.children).sort((a, b) => a.localeCompare(b)).forEach(name => visit(node.children[name], path === '/' ? `/${name}` : `${path}/${name}`, depth + 1)); }; visit(system.fileSystem.root, '/', 0); context.textContent = `${system.cwd} — ${directoryNotes[system.cwd] || 'A directory in the fictional Academy filesystem.'}`; }
  function render() { prompt.textContent = promptText(); const labels = [['root', 'REACH THE ROOT /'], ['home', 'FIND /HOME/MUSEUM'], ['documents', 'ENTER DOCUMENTS WITH A RELATIVE PATH'], ['logs', 'VISIT /VAR/LOG WITH AN ABSOLUTE PATH']]; mission.innerHTML = labels.map(([key, label]) => `<li class="${progress[key] ? 'complete' : ''}">[${progress[key] ? 'X' : ' '}] ${label}</li>`).join(''); const done = Object.values(progress).every(Boolean); $('#completion').hidden = !done; guidance.textContent = done ? 'Explore freely. Try cd ~, ls, and cat README.txt.' : !progress.root ? 'MISSION 1: TRY cd /  THEN pwd' : !progress.home ? 'MISSION 2: FROM /, TRY cd home · ls · cd museum' : !progress.documents ? 'MISSION 3: FROM HOME, TRY cd Documents' : 'MISSION 4: TRY cd /var/log'; renderTree(); }
  function updateProgress(result) { if (!result.success || result.command !== 'cd') return; if (system.cwd === '/') progress.root = true; if (progress.root && system.cwd === '/home/museum') progress.home = true; if (progress.home && system.cwd === '/home/museum/Documents') progress.documents = true; if (progress.documents && system.cwd === '/var/log') progress.logs = true; }
  function welcome() { write(['LINUX TERMINAL ACADEMY', 'LAB 02 — FILESYSTEM EXPLORER', '', 'MISSION: LEARN HOW LINUX ORGANIZES FILES.', 'EVERYTHING BEGINS AT /', '', 'You start in /home/museum.', 'Try: cd /']); }
  function reset() { system = new VirtualSystem(); shell = new Shell(system, { allowedCommands: [...defaultCommands, 'cat'] }); history = []; historyIndex = 0; progress = { root: false, home: false, documents: false, logs: false }; output.replaceChildren(); welcome(); render(); input.value = ''; input.focus(); announcer.textContent = 'Lab reset. You are in /home/museum.'; }
  function run(raw) { const value = raw.trim(); if (!value) return; write([`${promptText()} ${value}`]); history.push(value); historyIndex = history.length; const result = shell.execute(value); if (result.clear) output.replaceChildren(); else if (result.output.length) write(result.output); updateProgress(result); render(); input.value = ''; input.focus(); announcer.textContent = result.success ? `${result.command} completed. Current directory: ${system.cwd}.` : result.output.join(' '); }
  input.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); run(input.value); } if (event.key === 'ArrowUp') { event.preventDefault(); if (history.length) { historyIndex = Math.max(0, historyIndex - 1); input.value = history[historyIndex]; } } if (event.key === 'ArrowDown') { event.preventDefault(); historyIndex = Math.min(history.length, historyIndex + 1); input.value = history[historyIndex] || ''; } });
  document.addEventListener('keydown', event => { if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); run('clear'); } }); $('#terminal').addEventListener('click', () => input.focus()); document.querySelectorAll('[data-command]').forEach(button => button.addEventListener('click', () => run(button.dataset.command))); tree.addEventListener('click', event => { const button = event.target.closest('button[data-path]'); if (button) run(`cd ${button.dataset.path}`); }); $('#hintButton').addEventListener('click', () => { announcer.textContent = guidance.textContent; }); $('#resetButton').addEventListener('click', reset); reset();
})();
